### ISSUE TITLE
能否增加是否为南大核心的提示？

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/zotero-updateifsE#1]
唯问数据库里只有是否为北大核心的信息
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/13982749/173026744-0511ee94-c2e2-42ac-9843-b657b3f970e0.png">
我看easyscholar的期刊类别信息很全，所以可否增加是否为CSSCI的信息？
<img width="676" alt="image" src="https://user-images.githubusercontent.com/13982749/173026808-e929a6c8-e0f7-4675-a315-ba0c46cafb56.png">

感谢

**Comment by redleafnew** [comment]
这个是用的easyScholar的数据。

**Comment by redleafnew** [comment]
看readme

**Comment by fredericky123** [comment]
这个readme和justsience是一样的吧
<img width="872" alt="image" src="https://user-images.githubusercontent.com/13982749/173027773-dacb7be7-6d56-40ef-951c-f437a4b26607.png">

没看出来怎么更新是否为CSSCI
另外，我测试0.0.1怎么匹配不到期刊 比如 ”科研管理“ ”研究与发展管理“

**Comment by redleafnew** [comment]
南大核心即是

**Comment by fredericky123** [comment]
> 南大核心即是

没懂唉 即是什么哈

**Comment by fredericky123** [comment]
<img width="258" alt="image" src="https://user-images.githubusercontent.com/13982749/173031078-43e59130-0453-4994-9657-220f84aae9f0.png">

我的期刊信息里 没有 南大核心 或者CSSCI

**Comment by redleafnew** [comment]
![zotero_o60i6r4fcf](https://user-images.githubusercontent.com/22135631/173031637-8ce10621-3f67-4448-b780-87964d0aa3da.png)
![zotero_5bvIASIjeU](https://user-images.githubusercontent.com/22135631/173031752-9e8a37ff-6e46-4f19-9488-1b0cbdc79c61.png)

**Comment by redleafnew** [comment]
在release重新下载安装吧

**Comment by fredericky123** [comment]
重新安装后 匹配到了却没有写作extra里

**Comment by redleafnew** [comment]
对于Extra中原来有内容的可能有问题，清除一下原来内容。

**Comment by fredericky123** [comment]
>  ![zotero_5bvIASIjeU](https://user-images.githubusercontent.com/22135631/173031752-9e8a37ff-6e46-4f19-9488-1b0cbdc79c61.png)

extra已经清空了
难道因为这些个显示 我都没有勾选？
如果勾选后就能显示，如果不勾选就不会显示

<img width="215" alt="image" src="https://user-images.githubusercontent.com/13982749/173035086-0fb1d5ac-68c7-4b31-9735-bf0733bfed9e.png">
<img width="506" alt="image" src="https://user-images.githubusercontent.com/13982749/173035124-825c20fb-fb03-4afd-8578-0d9cbdc4b17d.png">

**Comment by redleafnew** [comment]
是的。

**Comment by fredericky123** [comment]
我还是希望像以前一样，期刊的这些信息只全部保存在extra而不保存在call number等，这个有办法么？
感谢！

**Comment by redleafnew** [comment]
这个版本没有做这个功能。

**Comment by fredericky123** [comment]
<img width="525" alt="image" src="https://user-images.githubusercontent.com/13982749/173036679-293910f2-1149-4264-9b42-323c8f63c91c.png">

能否在这些选项里加个empty
这样就可以让指定信息保存到extra了

**Comment by fredericky123** [comment]
比如，如果增加一个field叫null,由于zotero没有这个field，就不会增加，同时是不是这个信息可以保存在了extra?

**Comment by redleafnew** [comment]
唯问版的也有南大核心好像。

**Comment by fredericky123** [comment]
有吗？我看原始网站貌似没有披露这个信息

**Comment by redleafnew** [comment]
南大核心和北大核心放在一个字段了，但Extra中好像还是最早版本的信息，忘了有没有了。

**Comment by fredericky123** [comment]
> 南大核心和北大核心放在一个字段了，但Extra中好像还是最早版本的信息，忘了有没有了。

其实我之前不太理解那个字段，北大/南大核心，这是两个list，如何判断有没有南大呢？
这是唯问的信息，好像没有包含南大
http://sci.justscience.cn/index.html?q=%E7%A7%91%E7%A0%94%E7%AE%A1%E7%90%86&sci=0

**Comment by redleafnew** [comment]
南大核心不是从唯问获致的，是从cnki中得到的

**Comment by fredericky123** [comment]
<img width="520" alt="image" src="https://user-images.githubusercontent.com/13982749/173042910-8d6e7681-c39f-4af7-97c8-8b45ffab4735.png">

这是唯问那个插件的设置，所以不知道北大/南大，究竟显示的是哪个数据库的？
在extra也没有南大的显示
<img width="283" alt="image" src="https://user-images.githubusercontent.com/13982749/173043173-f609e076-0ad1-454f-bf7a-a8fe65fa383c.png">

所以劳烦看看在easy的数据源中包含南大的提示呀！
感谢1

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.0.2

**Comment by fredericky123** [comment]
很完美，不过咨询一下，那个中文期刊EI是什么list哎

**Comment by redleafnew** [comment]
https://www.ei.org.cn/post/eiwhy.html

**Comment by fredericky123** [comment]
EI还是我知道的那个ei，不过ei竟然收录中文期刊，我是第一次知道
