### ISSUE TITLE
建议在文档里添加“增加”的字段说明

### ISSUE THREAD

**Issue by wybert** [redleafnew/zotero-updateifsE#10]
感谢开放这个插件，我有一个问题：

插件抓取的信息时候会添加到特定的字段，不同字段对应的是什么？

下面是我的一个截图，
<img width="305" alt="image" src="https://user-images.githubusercontent.com/5254627/181296637-705377f3-af17-4a97-8ef6-d6a9e732355e.png">
`Archive` 和 `Cell number`等这些从字段名字无法直接联想到分区和影响因子

1. 能够修改字段的名字
2. 建议说明字段的含义

**Comment by redleafnew** [comment]
哪个字段显示什么内容是自己设置的哦，见
![FAc3thcCNz](https://user-images.githubusercontent.com/22135631/181390053-b13b98e3-97b3-4e3e-a674-d00a9019c888.png)
![zotero_7CSDOBhXzT](https://user-images.githubusercontent.com/22135631/181390060-14c2239a-def8-425d-b49a-12c50fb1d439.png)

**Comment by wybert** [comment]
❤️👍多谢了，建议把这个添加到 readme
