### ISSUE TITLE
作者大大，绿青蛙和 style 插件有冲突，列宽设置会有问题，请问下能修复吗？感谢！

### ISSUE THREAD

**Issue by Zhangxigu** [redleafnew/zotero-updateifsE#102]

**Comment by redleafnew** [comment]
等待Zotero升级应该可以解决。

**Comment by Zhangxigu** [comment]
好的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: redleafnew ***@***.***&gt;
发送时间: 2023年8月19日 21:03
收件人: redleafnew/zotero-updateifsE ***@***.***&gt;
抄送: Zhangxigu ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [redleafnew/zotero-updateifsE] 作者大大，绿青蛙和 style 插件有冲突，列宽设置会有问题，请问下能修复吗？感谢！ (Issue #102)





 
等待Zotero升级应该可以解决。

**Comment by XoYaPeng** [comment]
这个问题困扰我好久，我还以为是别的插件出问题，今天又试了下，才发现是新的绿青蛙哈哈哈。已经退回到16版了
