### ISSUE TITLE
更新条目原数据时会自动调用 zotfile 进行重命名工作？

### ISSUE THREAD

**Issue by liut14** [redleafnew/zotero-updateifsE#104]
如图，点击更新条目原数据
![image](https://github.com/redleafnew/zotero-updateifsE/assets/52646263/8a36e483-873c-41c1-9340-ab3fd3a3dead)
发现每次都会调用文件重命名。不知道是不是绿青蛙就是这样设计的。还是条目更新的操作自动触发了 zotfile 进行重命名操作？
![image](https://github.com/redleafnew/zotero-updateifsE/assets/52646263/70e3f7bd-6c90-46d5-8fc9-67718765917a)

另外想问一下作者大大，这个更新条目原数据是更新的那些原数据啊？因为我之前是endnoted的使用者，所以想提一个不成熟的建议。比如更新原数据时，能否像endnote一样列出一个对比，然后让使用者自行选择更新哪些数据？
![image](https://github.com/redleafnew/zotero-updateifsE/assets/52646263/d380c83f-5ea4-4e30-ab6f-965e9eef31b0)

**Comment by redleafnew** [comment]
应该是触发了ZotFile的操作。

更新元数据代码借用的
https://getquicker.net/Sharedaction?code=78da8f40-e73a-46e8-da6b-08da76a0d1ac
https://getquicker.net/Sharedaction?code=305c5f6e-4f15-445c-996a-08dace1ee4e7
这两个动作。

更复杂的操作我也不会了。

**Comment by northword** [comment]
对于外文期刊，系通过 DOI 更新，DOI 返回什么内容，就更新哪些。

插件没有调用 Zotfile 的行为，系 Zotfile 监听。

差异化合并窗格官方做了，https://github.com/zotero/zotero/pull/1582 ，虽然没有合并的时间，但插件可能不会在这个功能上划分很多精力。

**Comment by redleafnew** [comment]
> 对于外文期刊，系通过 DOI 更新，DOI 返回什么内容，就更新哪些。
> 
> 插件没有调用 Zotfile 的行为，系 Zotfile 监听。
> 
> 差异化合并窗格官方做了，[zotero/zotero#1582](https://github.com/zotero/zotero/pull/1582) ，虽然没有合并的时间，但插件可能不会在这个功能上划分很多精力。

插件就是个应急的试用方案，官方的等待很久了，也提了很长时间了。
