### ISSUE TITLE
beta7 on macbookpro IF shows incorrect data

### ISSUE THREAD

**Issue by LIZSK** [redleafnew/zotero-updateifsE#106]
你好！我的zotero beta7 在MacBookpro上使用这个插件，会出现2个IF。其中一个没有数据，另一个一直显示-1，请问有办法解决吗？谢谢！
<img width="336" alt="Screenshot 2023-09-07 at 22 36 42" src="https://github.com/redleafnew/zotero-updateifsE/assets/129670832/ba0a0c32-08c3-461f-b3f0-90a5c381fffd">

**Comment by redleafnew** [comment]
Mac的我不懂，不过你是不是装了多个类似的插件，有可能冲突了。如Zotero style，可以禁用下，只保留green frog。

**Comment by northword** [comment]
请使用最新的zotero beta版本和插件版本测试后再继续反馈。
