### ISSUE TITLE
插件更新的AJG期刊分级数据不准确

### ISSUE THREAD

**Issue by skymagician** [redleafnew/zotero-updateifsE#107]
比如 American Economic Review 一直都是4*的，但是插件更新的结果却是3。不知道是 easyscholar 数据的问题，还是插件的问题。

**Comment by redleafnew** [comment]
用easyScholar网页查询是多少？

**Comment by skymagician** [comment]
查询不了，只有订阅会员才能查。
________________________________

**Comment by redleafnew** [comment]
选中条目，运行一下这些代码，看结果是不是正确的?

```
var items = ZoteroPane.getSelectedItems();
  var item = items[0]; 
  let secretKey = Zotero.Prefs.get('extensions.zotero.greenfrog.secretkey', true);
  //publicationTitle =encodeURIComponent(item.getField('publicationTitle'));
  var publicationTitle = Zotero.ItemTypes.getName(item.itemTypeID) == 'journalArticle' ?
      encodeURIComponent(item.getField('publicationTitle')) :
      encodeURIComponent(item.getField('conferenceName') );
   
  var url = `https://easyscholar.cc/open/getPublicationRank?secretKey=${secretKey}&publicationName=${publicationTitle}`;
  let req = await Zotero.HTTP.request('GET', url, { responseType: 'json' });
  return req.response;
```

**Comment by skymagician** [comment]
> 选中条目，运行一下这些代码，看结果是不是正确的?
> 
> ```
> var items = ZoteroPane.getSelectedItems();
>   var item = items[0]; 
>   let secretKey = Zotero.Prefs.get('extensions.zotero.greenfrog.secretkey', true);
>   //publicationTitle =encodeURIComponent(item.getField('publicationTitle'));
>   var publicationTitle = Zotero.ItemTypes.getName(item.itemTypeID) == 'journalArticle' ?
>       encodeURIComponent(item.getField('publicationTitle')) :
>       encodeURIComponent(item.getField('conferenceName') );
>    
>   var url = `https://easyscholar.cc/open/getPublicationRank?secretKey=${secretKey}&publicationName=${publicationTitle}`;
>   let req = await Zotero.HTTP.request('GET', url, { responseType: 'json' });
>   return req.response;
> ```

去哪里运行？怎么运行这些代码？

**Comment by redleafnew** [comment]
Tools-Developer-Run JS

**Comment by skymagician** [comment]
> Tools-Developer-Run JS

运行了，easy scholar 的数据没问题，是插件的问题

**Comment by skymagician** [comment]
{
    "code": 200
    "msg": "SUCCESS"
    "data": {
        "customRank": {
            "rankInfo": []
            "rank": []
        }
        "officialRank": {
            "all": {
                "swufe": "A+"
                "cufe": "AAA"
                "uibe": "A"
                "sdufe": "特类期刊"
                "xdu": "1类贡献度"
                "swjtu": "A++"
                "ruc": "A+"
                "cug": "经济学T1"
                "sciif": "10.7"
                "ssci": "Q1"
                "sciUp": "经济学1区"
                "ajg": "4*"
                "sciif5": "12.7"
                "fms": "A"
                "jci": "3.51"
                "ft50": "FT50"
            }
            "select": {
                "swufe": "A+"
                "cufe": "AAA"
                "uibe": "A"
                "sdufe": "特类期刊"
                "xdu": "1类贡献度"
                "swjtu": "A++"
                "ruc": "A+"
                "cug": "经济学T1"
                "sciif": "10.7"
                "ssci": "Q1"
                "sciUp": "经济学1区"
                "ajg": "4*"
                "sciif5": "12.7"
                "fms": "A"
                "jci": "3.51"
                "ft50": "FT50"
            }
        }
    }
}

**Comment by skymagician** [comment]
插件返回的影响因子也不对

**Comment by redleafnew** [comment]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/22135631/ebb3279b-d1cf-46ec-b36a-b38030c105c6)

是这个结果吗？

**Comment by skymagician** [comment]
> ![image](https://user-images.githubusercontent.com/22135631/266819471-ebb3279b-d1cf-46ec-b36a-b38030c105c6.png)
> 
> 是这个结果吗？

是的，我这边现在也好了。
