### ISSUE TITLE
会议论文的信息更新

### ISSUE THREAD

**Issue by wangxn2** [redleafnew/zotero-updateifsE#108]
如何更新会议论文的信息呢？
载入后，会议名称那里会自动填写，但是更新期刊信息失败。
例如：会议名称：KDD '23: The 29th ACM SIGKDD Conference on Knowledge Discovery and Data Mining
请问是会议名称的信息不对，还是需要在easyscholar上设置什么？

**Comment by redleafnew** [comment]
会议论文（需要将会议名称填入Conference Name字段），
可以在easyScholar网站上查询一下，能不能显示。
