### ISSUE TITLE
在使用PDF translate翻译，并标红的时候会自动在右下角弹出更新提示

### ISSUE THREAD

**Issue by MoLiShang** [redleafnew/zotero-updateifsE#109]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/37530126/935999ea-9e7a-4882-8828-b2544f4b44ab)

**Comment by MoLiShang** [comment]
green fog没有识别这个新增的条目是文献还是只是笔记，当设置里面关闭添加条目时更新期刊信息这个选项后就不会出现这种问题了，建议加一个判断

**Comment by redleafnew** [comment]
增加普通笔记时好像不会提示呢

**Comment by MoLiShang** [comment]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/37530126/c4247717-abda-4b9e-8816-0764db0afb88)
greenfog和pdf translate键冲突了，只要在首选项里面把这个勾选掉就可以了
