### ISSUE TITLE
问题反馈：开启添加条目时更新按钮，每次开启zotero自动更新全部文献影响因子

### ISSUE THREAD

**Issue by Sifan798** [redleafnew/zotero-updateifsE#11]
![image](https://user-images.githubusercontent.com/59358565/182823493-8e5c65dd-8c3d-4665-a7c0-5c7a301a058a.png)
如上图，当打开“添加条目时自动更新期刊信息”按钮后，每次开启zotero都会自动更新文献库内所有文献的信息，如下图。
<img width="188" alt="打开软件大量更新" src="https://user-images.githubusercontent.com/59358565/182823958-e4b77e7e-9689-436d-bb67-3a23e56dfc92.png">

**Comment by redleafnew** [comment]
每次启动都会再更新一遍？

**Comment by Sifan798** [comment]
不是，开机后第一次打开就会全部更新，而且提醒未查询到期刊信息。

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by redleafnew** [comment]
那就关闭吧，原来的设计是添加条目时会自动更新，更新一次就可以了

**Comment by Sifan798** [comment]
对，原来关闭担心新添加文献无法自动更新。有bug的话就手动吧
________________________________

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifs 用这个有相同问题吗？

**Comment by Sifan798** [comment]
好速度！明天我试一下
________________________________

**Comment by Sifan798** [comment]
经过测试，唯问不会出现这种情况。easyScholar在开机后首次打开zotero后还会出现全部更新文献信息的情况。
