### ISSUE TITLE
快捷键切换

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/zotero-updateifsE#111]
自动切换题目title的快捷键目前mac为command+T，而zotero pdf translate翻译的快捷键也是command+T
为避免冲突，本插件的切换title的快捷键能否改为option+command+t，对应win的alt+ctrl+T

**Comment by redleafnew** [comment]
`T`可以换为其它的啊，

`option`我不知道`modifiers`是什么？

**Comment by fredericky123** [comment]
也好的，我关注一下option的modifiers等确定了 来报
不知道comamd+哪个比较适合代表翻译

**Comment by redleafnew** [comment]
不行就拼音
`F`an `Y`i

**Comment by fredericky123** [comment]
稍等一下下哈，我在论坛上提问了，等有人回复就行啦

**Comment by fredericky123** [comment]
https://github.com/windingwind/zotero-actions-tags
这里是可以自定义设置快捷键的，比如command键，但是我不知道在哪里查询记录下来的modifier键
韩老师能知道在哪里找不

**Comment by redleafnew** [comment]
在Zotero的高级设置里应该可以找到。

**Comment by fredericky123** [comment]
<img width="990" alt="image" src="https://github.com/redleafnew/zotero-updateifsE/assets/13982749/c5edbdd8-8022-45ee-b020-a0f8ac29f10a">
我搜出来这个
韩老师能在win下试试怎么找到代码，确定快捷键modifier么

**Comment by redleafnew** [comment]
我也搞不清楚。

**Comment by fredericky123** [comment]
@windingwind 大佬能帮忙回答下这个困扰了问题不

**Comment by redleafnew** [comment]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/22135631/94d8a3cb-f913-414f-8f28-c60402ac5c86)
win下就是这样显示的

**Comment by fredericky123** [comment]
<img width="919" alt="image" src="https://github.com/redleafnew/zotero-updateifsE/assets/13982749/d0fecae1-5cc3-4e8d-b760-12e2f243390c">
这是option+command+T的显示

**Comment by redleafnew** [comment]
搞不懂啊，太复杂了
