### ISSUE TITLE
xpi组件文件损坏无法安装

### ISSUE THREAD

**Issue by ZIMOF** [redleafnew/zotero-updateifsE#112]
显示附加组件损坏无法安装

**Comment by redleafnew** [comment]
Zotero哪个版本，看readme，选择合适的版本。

**Comment by ZIMOF** [comment]
Zotero6.0.27,下载0.13.0的插件仍然显示下图



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/zotero-updateifsE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月21日(星期四) 下午3:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redleafnew/zotero-updateifsE] xpi组件文件损坏无法安装 (Issue #112)





 
Zotero哪个版本，看readme，选择合适的版本。

**Comment by redleafnew** [comment]
可能你的Zotero有问题吧，我刚试了一下没有问题。可以运行 安装路径\zotero.exe -p，新建一个profie试试。

**Comment by ZIMOF** [comment]
好的我再试试，谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/zotero-updateifsE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月21日(星期四) 下午4:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redleafnew/zotero-updateifsE] xpi组件文件损坏无法安装 (Issue #112)





 
可能你的Zotero有问题吧，我刚试了一下没有问题。可以运行 安装路径\zotero.exe -p，新建一个profie试试。
