### ISSUE TITLE
发现数据更新不准确的情况

### ISSUE THREAD

**Issue by llity** [redleafnew/zotero-updateifsE#12]
数据库和本地更新结果出差。更新的时候会从正确的数据，突然变成错误的数据。
<img width="781" alt="image" src="https://user-images.githubusercontent.com/11771112/190835932-f7b6d21d-dfe2-42b6-b43e-96520ef6efd3.png">

**Comment by llity** [comment]
test GIF
![Sep-17-2022 10-00-55](https://user-images.githubusercontent.com/11771112/190836184-18b0c3e4-4a7d-4c43-ad42-ba6fabd1821f.gif)

**Comment by redleafnew** [comment]
产生这个错误的原因是这个期刊在https://navi.cnki.net/knavi/ 也能查到，所以将这两个字段替换成了综合影响因子和复合影响因子。我回头做一个判断，是期刊名是中文的再进行更新综合影响因子和复合影响因子。

**Comment by redleafnew** [comment]
或是现在将这两个选项禁用
![image](https://user-images.githubusercontent.com/22135631/190838708-5fdf7d06-d716-41e3-b1e3-5f587c2405a5.png)

**Comment by llity** [comment]
设置后可行，但不完全行，中文期刊需要判断一下。

**Comment by llity** [comment]
谢谢，这样的杂志比较少。

**Comment by llity** [comment]
这样在国内单位主办的期刊，能否同时显示中英文相关信息呢？比如前面是英文索引，后面是中文索引信息。谢谢

**Comment by redleafnew** [comment]
可以设置一下，下面的显示的字段，不与上面的冲突。但是不好办，Zotero可以借用的字段比较少，官方推荐的是都显示的Extra中。

**Comment by llity** [comment]
确实也是，有冲突。

**Comment by redleafnew** [comment]
外文期刊大家大都只关注影响因子而不是综合和复合影响因子吧，所以还是屏蔽后者吧。

**Comment by llity** [comment]
可行

**Comment by redleafnew** [comment]
更新试试。

**Comment by llity** [comment]
<img width="619" alt="image" src="https://user-images.githubusercontent.com/11771112/190848991-0b540cc6-4bb0-46b8-9f4a-a0c539d38b29.png">
这两个字段没办法正确更新

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/190854885-80e57fed-aad9-4f60-a524-b08f93b387f3.png)
得到这个数据，正确更新指什么？

**Comment by llity** [comment]
<img width="849" alt="image" src="https://user-images.githubusercontent.com/11771112/190855540-16d38c12-07b0-469d-8e92-194719a3ecd5.png">
应该是Q1和农林科学1区吧

**Comment by redleafnew** [comment]
哦，原因和综合影响因子一样。把下面中文的禁用就可以了。我一会儿再修改一下，如果是英文期刊不获取这些信息。

**Comment by llity** [comment]
中文的禁用了，那中文文献查不到是不是核心期刊了？

**Comment by redleafnew** [comment]
是的，我想办法做了判断，英文期刊就不再获取这两个数据了。

**Comment by redleafnew** [comment]
我设置一下只有期刊名中有中文才写入北大核心、南大核心、CSCD和科技核心字段

**Comment by llity** [comment]
好呢，谢谢。这样就完善了 :)

**Comment by redleafnew** [comment]
升级了。

**Comment by llity** [comment]
测试完美，可以关闭了

**Comment by llity** [comment]
> 可以设置一下，下面的显示的字段，不与上面的冲突。但是不好办，Zotero可以借用的字段比较少，官方推荐的是都显示的Extra中。

我发现有插件创建了自己的自定义字段，不知道是否能考虑一下。https://github.com/scitedotai/scite-zotero-plugin
![image](https://user-images.githubusercontent.com/11771112/190940833-15a7a282-f04e-47db-9590-be1fc575e107.png)

**Comment by redleafnew** [comment]
比较复杂，后面有时间再说了。
