### ISSUE TITLE
Can not install greenfrog.xpi because of the incompatibility

### ISSUE THREAD

**Issue by yhWu815** [redleafnew/zotero-updateifsE#121]
OS information: Windows 11 professional 22H2, x86_64
Zotero Version: 6.0.30
Greenfrog version: 0.16.03

Error: 无法安装插件“%S”。它可能无法与该版本的 Zotero 兼容。

![安装报错](https://github.com/redleafnew/zotero-updateifsE/assets/83410263/650cf83c-71b1-4a81-9caa-78b3dcf420e3)
![zotero版本](https://github.com/redleafnew/zotero-updateifsE/assets/83410263/d6c3d08d-9c1c-4f2b-8933-b3218b5e547d)

**Comment by redleafnew** [comment]
看看readme，最新版本只兼容7.0，找兼容6.0的版本。

**Comment by yhWu815** [comment]
已解决，谢谢
