### ISSUE TITLE
无法安装，显示不兼容

### ISSUE THREAD

**Issue by Ares960826** [redleafnew/zotero-updateifsE#122]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/80300117/479a24be-e52a-4055-ab73-06ef1ef1766b)

无法安装，显示不兼容，但是我的Zotero已经是最新版的了

![image](https://github.com/redleafnew/zotero-updateifsE/assets/80300117/c065d772-983f-4637-bf1e-8c40d2fe4cbe)

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/issues/121
