### ISSUE TITLE
更新元数据后信息栏显示问题

### ISSUE THREAD

**Issue by zhangshd** [redleafnew/zotero-updateifsE#124]
更新元数据后，显示的信息但凡有出现上下标或者其他类似特殊格式的时候，会导致格式不整洁，影响阅读
![Snipaste_2023-11-22_15-12-51](https://github.com/redleafnew/zotero-updateifsE/assets/23273686/40db35c1-8f32-4c0b-aa78-1b9c54ec9f70)

**Comment by zhangshd** [comment]
建议把上下标等特殊格式直接清除

**Comment by redleafnew** [comment]
标题中的是必要的，在word中显示需要。

**Comment by zhangshd** [comment]
> 建议把上下标等特殊格式直接清除

那是否可以把摘要中的特殊格式去掉或者优化一下显示呢？现在这个样子是不太方便预览摘要的 @redleafnew

**Comment by redleafnew** [comment]
需要哪些，可以尝试写一些脚本，利用Zotero Actions&Tags解决。

**Comment by zhangshd** [comment]
> 需要哪些，可以尝试写一些脚本，利用Zotero Actions&Tags解决。

主要就是上下标的问题

**Comment by redleafnew** [comment]
给我几个例子吧
JSON格式。

**Comment by zhangshd** [comment]
[
[bad_cases.zip](https://github.com/redleafnew/zotero-updateifsE/files/13447114/bad_cases.zip)
](url)

> 给我几个例子吧 JSON格式。

[bad_cases.zip](https://github.com/redleafnew/zotero-updateifsE/files/13447116/bad_cases.zip)

**Comment by redleafnew** [comment]
我抽时间试试。

**Comment by zhangshd** [comment]
感谢作者！

**Comment by redleafnew** [comment]
其实主要的问题是里面空格太多吧，

**Comment by zhangshd** [comment]
> 其实主要的问题是里面空格太多吧，

是的，不过不是普通的空格，不知道为啥在转换的时候产生那么多换行符

**Comment by redleafnew** [comment]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/22135631/b1724427-1584-4217-84e8-372a9d81348d)
形成这样可以吗？

**Comment by zhangshd** [comment]
> ![image](https://user-images.githubusercontent.com/22135631/285165485-b1724427-1584-4217-84e8-372a9d81348d.png) 形成这样可以吗？

我觉得很OK了，赞呀

**Comment by redleafnew** [comment]
脚本：https://github.com/windingwind/zotero-actions-tags/discussions/196

**Comment by redleafnew** [comment]
**替换不可恢复，替换前注意备份数据。**
