### ISSUE TITLE
插件安装失败，显示“无法安装插件“%S”。它可能无法与该版本的 Zotero 兼容。”

### ISSUE THREAD

**Issue by Brandon-hao** [redleafnew/zotero-updateifsE#127]
安装失败，显示“无法安装插件“%S”。它可能无法与该版本的 Zotero 兼容。”

**Comment by redleafnew** [comment]
看readme。

**Comment by Brandon-hao** [comment]
谢谢你，没想到我前段时间在官网下载的zotero竟然也是zotero 6，怪我不太仔细
注意：The latest version only supports Zotero 7.0, Zotero 6.0 users could download [0.13.0](https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.13.0)。
