### ISSUE TITLE
有分区加载不出来

### ISSUE THREAD

**Issue by CocoTang1024** [redleafnew/zotero-updateifsE#129]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/75608560/583b6574-5203-48a1-9dd3-adb279ea2214)
上面更新分区的时候报错
下面在访问www.webofscience.com的时候，分区是可以显示的
![image](https://github.com/redleafnew/zotero-updateifsE/assets/75608560/021101c8-0714-4441-94fa-59c76f469395)

**Comment by redleafnew** [comment]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/22135631/7beb2c14-5132-487f-8817-498668052ae4)

**Comment by CocoTang1024** [comment]
请问这个可以自己添加吗，我这个刷新了还是报错
![image](https://github.com/redleafnew/zotero-updateifsE/assets/75608560/e549fb49-6faf-4776-8189-1386cec7b2cc)

**Comment by CocoTang1024** [comment]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/75608560/3597c4e4-b4f2-4b78-b28a-4bad4ef0a691)
因为我看是有两篇可以加载出来的

**Comment by redleafnew** [comment]
期刊名称明显不一样啊。根据期刊名称来的。APPLIED SCIENCES-BASEL

**Comment by CocoTang1024** [comment]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/75608560/33b8a69f-5749-4bc3-a4d7-58d6417f3800)
但是这个我网页直接用的就是easyscholar的插件是可以显示出来的，期刊名称也是这个(APPLIED SCIENCES-BASEL)。有点不太明白😵

**Comment by CocoTang1024** [comment]
您看这个就是可以出来的影响因子以及分区啥的

**Comment by redleafnew** [comment]
把不能检索到的条目JSON格式上传一下。

**Comment by CocoTang1024** [comment]
[导出的条目.json](https://github.com/redleafnew/zotero-updateifsE/files/13873706/default.json)
这个就是

**Comment by redleafnew** [comment]
这个期刊是没有的。

可以在Zotero中运行这段代码，有结果的才可以显示：

```
var items = ZoteroPane.getSelectedItems();
  var item = items[0]; 
  let secretKey = Zotero.Prefs.get('extensions.zotero.greenfrog.secretkey', true);
  //publicationTitle =encodeURIComponent(item.getField('publicationTitle'));
  var publicationTitle = Zotero.ItemTypes.getName(item.itemTypeID) == 'journalArticle' ?
      encodeURIComponent(item.getField('publicationTitle')) :
      encodeURIComponent(item.getField('conferenceName') );
   
  var url = `https://easyscholar.cc/open/getPublicationRank?secretKey=${secretKey}&publicationName=${publicationTitle}`;
  let req = await Zotero.HTTP.request('GET', url, { responseType: 'json' });
  return req.response;
```

**Comment by redleafnew** [comment]
如果对结果有疑问，可以向easyScholar反馈，接口是他提供的。

**Comment by CocoTang1024** [comment]
好

**Comment by CocoTang1024** [comment]
问题已解决，需要在期刊名称后加上–basel，如下
![image](https://github.com/redleafnew/zotero-updateifsE/assets/75608560/3c03431d-da9c-4b31-bc38-7e73308e1d75)
原来识别到的
![image](https://github.com/redleafnew/zotero-updateifsE/assets/75608560/343a5c07-95b9-4617-b846-4f11fa8b7b35)
需要修改成
![image](https://github.com/redleafnew/zotero-updateifsE/assets/75608560/84319524-72b4-424f-b821-36cd80d48d72)
接着重新更新
![image](https://github.com/redleafnew/zotero-updateifsE/assets/75608560/7ba97657-34d5-4815-8c77-311b8bf8577d)
发现显示出来了
感谢❤

**Comment by redleafnew** [comment]
对，这两个应该是两本期刊。
