### ISSUE TITLE
Does not downloads file from sci-hub

### ISSUE THREAD

**Issue by mahmutelmas06** [redleafnew/zotero-updateifsE#130]
All field updated after i click update metadata but doesnt download pdf attachment. It opens only sci-hub web page.

I use latest addon version and zotero 7 beta.
I use Firefox if it is related.

**Comment by redleafnew** [comment]
The code update metadata was sourced from https://getquicker.net/Sharedaction?code=78da8f40-e73a-46e8-da6b-08da76a0d1ac, I think it can not download the attachment.

**Comment by mahmutelmas06** [comment]
There is an addon called fetch pdf linked here https://github.com/syt2/zotero-scipdf
It can download pdf very well. Maybe you could use its code

**Comment by redleafnew** [comment]
I don't think greenfrog has the plan to download pdf, sorry.
