### ISSUE TITLE
最近绿青蛙即显示更新条目成功，有显示更新信息失败。。。

### ISSUE THREAD

**Issue by lastzod** [redleafnew/zotero-updateifsE#131]
最近用zotero 下载文献， 绿青蛙的插件，每一篇文章都是显示更新 成功，然后就显示从easyscholar 更新期刊信息失败。

我的easyscholar 开通的是永久会员。

我又按照获取秘钥的教程，重新获取了好几次密钥。

但是问题依然没有解决。

不过最后zotero里的论文相关信息，倒是没什么问题。

不过我怀疑绿青蛙是在用以前的数据库更新或者获取相关论文信息，如果再过一段时间，可能就会出现获取信息失败的问题了吧。

我截图了上传到附件中。。。第一次反馈问题，不知道我的操作对不对。
![微信截图_20240122232246](https://github.com/redleafnew/zotero-updateifsE/assets/151750673/cc220144-8a69-41fe-b76e-b443deab963c)

![微信截图_20240122232246](https://github.com/redleafnew/zotero-updateifsE/assets/151750673/f0a5c18f-b8f8-42db-a7ed-bd496ead50db)

**Comment by redleafnew** [comment]
两个更新的可能不是一个东西？
什么时候出现的？右击条目的时候？
条目信息JSON格式发一下？

**Comment by lastzod** [comment]
没有，我是不会操作，把同样的图片，上传了2次。。。
元旦前用的时候还好好的，我不是天天都用zotero，所以过了元旦，有一天，用的时候，出现这个问题，到现在还是这样。。。

**Comment by lastzod** [comment]
不是右击条目的时候，是用茉莉花自动获取知网文献的时候，右下角就会出现这个提示。

**Comment by lastzod** [comment]
以前，茉莉花，每获取一篇文献，右下角只会出现更新条目成功的提示，我不知道这里发留言怎么下一行，敲回车就直接发出去了

**Comment by lastzod** [comment]
现在是先出现，更新条目成功的提示，这个提示还没有消失，第二个，从easyscholar 更新期刊信息失败的提示就出现了。

**Comment by redleafnew** [comment]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/22135631/aba44e56-d9bc-4b7e-a619-87a4cfe9ef25)
有可能期刊的问题，把这个选项不选，在添加文献时应该就没有这个提示了

**Comment by lastzod** [comment]
从去年年底到现在，知网貌似一直在调整内部的什么，12月到元旦，茉莉花出现了好长时间无法抓取的情况，不过最近貌似好多了，基本都能抓了。我是怕知网调整，或者easyscholar 因为知网的调整，出现了什么问题，导致绿青蛙会提示出现错误。所以反馈一下，如果可能，还是希望保留这个选项。谢谢你啦。。。如果麻烦，就算了。。

**Comment by lastzod** [comment]
![微信截图_20240124224115](https://github.com/redleafnew/zotero-updateifsE/assets/151750673/c2fa4711-0389-45bc-bb3f-bc754dea116d)
![微信截图_20240124224131](https://github.com/redleafnew/zotero-updateifsE/assets/151750673/e6917fbd-80ce-4b2a-b3aa-8e52990e4542)
我怎么看我的选项和你的不太一样，我用的zotero6，你用的是zotero7 ？

**Comment by lastzod** [comment]
查了一下，你应该用的是zotero7，0.13.0这个，你不再维护更新了么？

**Comment by redleafnew** [comment]
Zotero 7估计快发布了。现在仅最新版本Greenforg的可能会维护。支持Zotero6的版本不再维护了。

**Comment by lastzod** [comment]
好的，谢谢你了

**Comment by lastzod** [comment]
其实，zotero的参考文献的哪个插件，也出现了问题，该有的参考文献倒是能抓取到，但是会抓取更多不是参考文献的信息，放到参考文献里，例如一个文献就17个参考文献，但是插件抓取出来的参考文献会有50多个。所以，我觉得是知网改版，对各个插件影响都比较大，或者说，对所有差价，多多少少都有一些影响。。。

**Comment by lastzod** [comment]
不知道能否加你的WX或者其他平台（例如小红书，哔哩哔哩）的账号为好友，以后也方便找你请教，这个网站，我每次都得搭梯子才能上来。。。

**Comment by redleafnew** [comment]
知乎上有专栏 软件随心
https://zhuanlan.zhihu.com/c_1071081428967743488

**Comment by CarbonArt** [comment]
自从我换了电脑以后，我zotero里面所有的期刊用这个easy scholar更新时，都是出现"easyscholar查不到此期刊的等级信息".......

**Comment by redleafnew** [comment]
运行这个代码，看看提示什么。
```
  // var items = ZoteroPane.getSelectedItems();
  var items = Zotero.getActiveZoteroPane().getSelectedItems();
  var item = items[0]; 
  let secretKey = Zotero.Prefs.get('extensions.zotero.greenfrog.secretkey', true);
  //publicationTitle =encodeURIComponent(item.getField('publicationTitle'));
  var publicationTitle = Zotero.ItemTypes.getName(item.itemTypeID) == 'journalArticle' ?
      encodeURIComponent(item.getField('publicationTitle')) :
      encodeURIComponent(item.getField('conferenceName') );
   
  var url = `https://easyscholar.cc/open/getPublicationRank?secretKey=${secretKey}&publicationName=${publicationTitle}`;
  let req = await Zotero.HTTP.request('GET', url, { responseType: 'json' });
  return req.response['data']["officialRank"]["all"]
```

**Comment by CarbonArt** [comment]
我发现原因了，是我easyscholar的问题！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月11日(周四) 下午3:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [redleafnew/zotero-updateifsE] 最近绿青蛙即显示更新条目成功，有显示更新信息失败。。。 (Issue #131)




 
运行这个代码，看看提示什么。
   // var items = ZoteroPane.getSelectedItems();   var items = Zotero.getActiveZoteroPane().getSelectedItems();   var item = items[0];    let secretKey = Zotero.Prefs.get('extensions.zotero.greenfrog.secretkey', true);   //publicationTitle =encodeURIComponent(item.getField('publicationTitle'));   var publicationTitle = Zotero.ItemTypes.getName(item.itemTypeID) == 'journalArticle' ?       encodeURIComponent(item.getField('publicationTitle')) :       encodeURIComponent(item.getField('conferenceName') );       var url = `https://easyscholar.cc/open/getPublicationRank?secretKey=${secretKey}&amp;publicationName=${publicationTitle}`;   let req = await Zotero.HTTP.request('GET', url, { responseType: 'json' });   return req.response['data']["officialRank"]["all"]

**Comment by lastzod** [comment]
谢谢你的一直关心我提出的问题，不过我不懂程序，没办法帮你运行代码，真是不好意思了。




知足常乐
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "redleafnew/zotero-updateifsE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月12日(星期五) 晚上6:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [redleafnew/zotero-updateifsE] 最近绿青蛙即显示更新条目成功，有显示更新信息失败。。。 (Issue #131)





 我发现原因了，是我easyscholar的问题！ 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2024年7月11日(周四) 下午3:00 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [redleafnew/zotero-updateifsE] 最近绿青蛙即显示更新条目成功，有显示更新信息失败。。。 (Issue #131) 
 
 
 
 
   
 运行这个代码，看看提示什么。 
    // var items = ZoteroPane.getSelectedItems();   var items = Zotero.getActiveZoteroPane().getSelectedItems();   var item = items[0];    let secretKey = Zotero.Prefs.get('extensions.zotero.greenfrog.secretkey', true);   //publicationTitle =encodeURIComponent(item.getField('publicationTitle'));   var publicationTitle = Zotero.ItemTypes.getName(item.itemTypeID) == 'journalArticle' ?       encodeURIComponent(item.getField('publicationTitle')) :       encodeURIComponent(item.getField('conferenceName') );       var url = `https://easyscholar.cc/open/getPublicationRank?secretKey=${secretKey}&amp;amp;publicationName=${publicationTitle}`;   let req = await Zotero.HTTP.request('GET', url, { responseType: 'json' });   return req.response['data']["officialRank"]["all"]
