### ISSUE TITLE
无法正常更新

### ISSUE THREAD

**Issue by zzzyzh** [redleafnew/zotero-updateifsE#135]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/89450146/64fdbf0c-5754-4730-aefa-8ba1eb5f5467)

我安装了大佬提供的两种不同版本的用于更新期刊的插件，但是对于一个条目来说，我这边从唯问更新和greenfrog的更新meta始终为灰色……

同时，如果我点击从easy scholar更新会一直提示 x 更新失败……

我使用的是 zotero6.0 插件下载的也是6.0 对应的版本

**Comment by redleafnew** [comment]
唯问的和6.0的不再更新了

**Comment by zzzyzh** [comment]
mac 似乎无法下载 zotero7，请问有什么别的途径吗

**Comment by redleafnew** [comment]
Mac的不了解了。
