### ISSUE TITLE
对于批量查询卡顿的建议

### ISSUE THREAD

**Issue by xiaoxstz** [redleafnew/zotero-updateifsE#136]
如果选中多个，开始批量查询，就会很卡。

我估计代码里，对每一个期刊进行一次一次循环。对此，我有以下两条建议

1.  批量查询前，先按照期刊进行分组。
    * 这样，查询次数就等于涉及到的期刊数，而不是等于文献数。可以大大减少循环次数。
    * 查询到结果，就批量更新改组的数据到Zotero。因为同一组的这些信息完全相同啊
1.  可以在本地建一个数据库，将查询过的期刊数据给存下来，这样可以大大减少卡顿调用easyScholar接口的次数

**Comment by redleafnew** [comment]
没有多少时间来维护插件了。不建议批量获取，服务器会有负担，而且期刊数据是会变的。

**Comment by xiaoxstz** [comment]
期刊数据更新频率很低的，再怎么也不会超过每天更新好几次吧。

* 一周更新一次就够了，程序里面做查询时，看看该文献的publication数据的上一次更新时间，就可以判断出来是否需要联网查询
