### ISSUE TITLE
新方向：利用zotero做项目管理

### ISSUE THREAD

**Issue by linfengtongxue70** [redleafnew/zotero-updateifsE#137]
尊敬的开发者，我注意到您的插件可以在zotero的列中出现更多的信息，比如【中科院升级版】、【南农核心】等等，这是原本zotero所没有的。而最近，我发现可以基于zotero来做项目管理。由于zotero在左侧栏文件夹树状图，这样的体验比传统的用系统文件夹分类更加简单高效。中间栏可以添加条目作为项目简介，并且将对应的文件包括word，PPT，项目照片等等加入到条目中，更加一目了然；同时，中间又可以显示多条列，可以比较不同项目之间的差异，比如实验方法，实验参数等等。总之，我认为这是一个很好的项目管理软件。

但是，目前zotero不支持自定义列的名字，这大大压制了zotero成为一个好的项目管理软件。我想问，您是否计划在未来支持用户自定义列的内容呢，我希望在未来有更多的自定义的表头。

如您有计划实现我这个想法，希望您不要忘记同时更新一下zotero6的插件。就目前而言，我认为zoteto6仍然是比zotero7 beta好用的。

感谢您看到这里，祝您生活愉快。

**Comment by redleafnew** [comment]
自定义列在Zotero论坛上从Zotero 5大概就开始讨论了。现在多余的列是基于“工具箱”实现的，如果有兴趣，可以查看一下源代码，Fork一下，增加自己需要的功能，也不麻烦，有开发者的微信群，里面有工具箱的作者在。我没有多余精力了。
还是要适应Zotero 7吧，原计划去年年底发布7的正式版的。
