### ISSUE TITLE
绿青蛙能否追加设置影响因子储存位置

### ISSUE THREAD

**Issue by baichacha** [redleafnew/zotero-updateifsE#138]
绿青蛙是一个非常强大期刊关键信息查询的插件，为科研事业舔砖加瓦，为大家提供了许多便利，十分感谢作者的付出。
我了解到 green frog 是Zotero Update IFs 的升级，但原来储存位置的设置提供了许多便利。能否重新将这个功能添加回来。
将获取JCR分区、中科院分区、影响因子和5年影响因子及中文期刊等，并分别写入到档案、存档位置、馆藏目录、索书号、版权字段（**可进行设置是否显示和存贮位置**）
不胜感激！

**Comment by redleafnew** [comment]
现在的更方便，可以设置多余的列，Zotero官方不推荐借用其它字段。

**Comment by redleafnew** [comment]
如果你用Quicker，我可以编写一个动作给你。
