### ISSUE TITLE
信息栏没有更新

### ISSUE THREAD

**Issue by monster150** [redleafnew/zotero-updateifsE#139]
开发者您好，很高兴我从最初就一直在使用这个插件，我很感谢他对我文献等级的筛选，对您表示感谢。然而，我昨天由于重新安装了插件后，我的条目信息栏勾选JCR分区、影响因子等列后，并没有出现对应的数据，我进行了删除“其他"重新进行更新期刊信息 它依然没有得到反应，我应该如何操作，我有2300多篇文献，以前他们都是显示的。非常感谢您
![image](https://github.com/redleafnew/zotero-updateifsE/assets/80930858/427add66-45ef-4c59-9bb1-ae3c7440e519)

**Comment by redleafnew** [comment]
请提供一下测试的条目，在条目上右击，导出，JSON格式，只导出不能显示的即可。

我看Extra中有内容，只是列上不显示吗？

**Comment by monster150** [comment]
是的，是所有文献条目，任何数据库的文献都是，因此我无法提供条目，包括旧的删除 新条目添加。此外，在其他 是都有显示，只是在列中不显示。此外，我在查询后发现是否与zotero style有关，我有安装他们，但昨天以前是可以正常显示的，是否是我重新安装插件后的问题。
![image](https://github.com/redleafnew/zotero-updateifsE/assets/80930858/2b26c9d8-b769-4415-a2de-f3c8885471ad)

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/commit/5abaab61cbc89bd8e086c5182f61554f00bbcad3

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.17.2

**Comment by monster150** [comment]
我在使用您的最新版本后，现在它们可以正常工作了，我很高兴我的所有文献都能使用了，我非常感谢您的开发，我差点失去我最喜欢的文献排序了。再次对您表示感谢！！！ps现在您可以关闭这个对话了，祝您一切顺利
