### ISSUE TITLE
有些期刊不会更新缩写

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/zotero-updateifsE#14]
如导入的这个文章：
https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2022&filename=YJYF202204008&uniplatform=NZKPT&v=gXWUzNm4NIekcQQ-KcLUbOLYReaDxlI48KvUqk8v4ySRZLbf11GJ0baj_JA_uyYh
已经设置了在数据库查询不到时，使用全称更新英文和中文的期刊缩写，如上文章却没有更新，而如下文章却可以更新，不知道问题在哪里
https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2022&filename=DJKX202202009&uniplatform=NZKPT&v=64cp1CFHHgASe-NmLgJTrU2RIzu6aR3TbZeuDrXtqd43W7De1xx4eK34zoNp9w0f

**Comment by redleafnew** [comment]
期刊缩写只是针对外文期刊名称的。

**Comment by fredericky123** [comment]
主页介绍里不是有这个功能么“可以设置如果英语或中文条目期刊缩写查询不到时是否用全称代替”
其实对于中文期刊，都想用全称替代期刊缩写，这样和英文文献放一起的时候，这一栏信息不会为空
<img width="273" alt="image" src="https://user-images.githubusercontent.com/13982749/196016233-8825357d-734c-4dee-90ea-6d3319ad4ad6.png">
图中为空的是中文期刊，但是有些中文的期刊缩写又能通过这个插件补全，不知道为啥如此

**Comment by redleafnew** [comment]
我这都是可以的，你把不行的期刊名称临时复制为可以更新的试试。

**Comment by fredericky123** [comment]
啊 是可以的 找到原因了 是用错插件导致的 下图圈中的右键显示内容好像是delitem插件的，应该点击从escholar更新期刊信息那个

<img width="342" alt="image" src="https://user-images.githubusercontent.com/13982749/196018715-42409833-888a-4490-a8fb-a33dd38e3258.png">

可否更新下delitem插件，将那个过时的update abbreviation删除，谢谢啦

**Comment by redleafnew** [comment]
已删除，其实两个期刊缩写的来源是不同的。

**Comment by fredericky123** [comment]
感谢如此速度！意外发现这个item用茉莉花导入后，用update from easyscholar无法更新中文缩写，您能复现吗
https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2022&filename=QHGP202203005&uniplatform=NZKPT&v=KvyuwKbI9aqD4VAJ7r_ddfvPtWwNMylAFKL3ngkr1ft5BEnL1EjPhu_-WbgMv9V-

**Comment by redleafnew** [comment]
插件的逻辑是如果在EasyScholarhttps://easyscholar.cc/paperQuery.html中找到记录才更新缩写的，这个期刊检索不到。可以给他提个建议，https://easyscholar.cc/index.html#contact。

**Comment by fredericky123** [comment]
英文期刊的话，去easyscholar检索；如果是中文期刊能否直接用全称更新缩写呢？

**Comment by redleafnew** [comment]
中文期刊也可以到EasyScholar检索，如果检索到，更新期刊缩写时会用全称替代。

**Comment by fredericky123** [comment]
那就是easyscholar的中文期刊不全了，我还想着中文不用检索了，直接替代；如果是学位论文的话，直接用university替换期刊缩写

**Comment by redleafnew** [comment]
可以写一段代码实现。
核心代码：
```
var university = item.getField('university');
var pubT = item.getField('publicationTitle');

item.setField('journalAbbreviation', pubT);
```
再加循环

**Comment by redleafnew** [comment]
可以到https://github.com/redleafnew/zotero-javascripts提需求
