### ISSUE TITLE
绿青蛙转换标题为sentence case存在问题

### ISSUE THREAD

**Issue by ramonmi** [redleafnew/zotero-updateifsE#141]
例如H2会被改成h2

**Comment by redleafnew** [comment]
这些属于特殊情况，如果遇到的多，我可以修改源代码，还有哪些情况，我一起修改一下。

**Comment by ramonmi** [comment]
暂时没遇到其他的，再遇到了报告给您

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.17.3

**Comment by ramonmi** [comment]
非常感谢，我经过尝试，发现对于化学元素加脚标，例如Fe<sub>2</sub>这一类的，均会变为小写，以钙钛矿相关文献最为常遇到，想请您看看是否可以通过代码规避这类问题。Ni，Sr，La，Ti，Co，Mo等

**Comment by northword** [comment]
韩老师也许可以使用官方的 sentenceCase 接口，该接口经过 bbt 作者更新后已经支持了除化学式外的绝大部分情况。

另外，[linter 插件](https://github.com/northword/zotero-format-metadata) 已针对化学式问题进行了适配。

**Comment by redleafnew** [comment]
> 非常感谢，我经过尝试，发现对于化学元素加脚标，例如Fe2这一类的，均会变为小写，以钙钛矿相关文献最为常遇到，想请您看看是否可以通过代码规避这类问题。Ni，Sr，La，Ti，Co，Mo等

可以是可以，但是如果单词中也有这些字母，也会转变，除非严格匹配。

**Comment by redleafnew** [comment]
如Opinion

**Comment by redleafnew** [comment]
> 韩老师也许可以使用官方的 sentenceCase 接口，该接口经过 bbt 作者更新后已经支持了除化学式外的绝大部分情况。
> 
> 另外，[linter 插件](https://github.com/northword/zotero-format-metadata) 已针对化学式问题进行了适配。

谢谢。我调用 `Zotero.Utilities.sentenceCase(title)`它

**Comment by redleafnew** [comment]
> > 非常感谢，我经过尝试，发现对于化学元素加脚标，例如Fe2这一类的，均会变为小写，以钙钛矿相关文献最为常遇到，想请您看看是否可以通过代码规避这类问题。Ni，Sr，La，Ti，Co，Mo等
> 
> 可以是可以，但是如果单词中也有这些字母，也会转变，除非严格匹配。

这些情况使用查找替换吧。
![image](https://github.com/redleafnew/zotero-updateifsE/assets/22135631/6b77991a-1eb6-4d54-894b-9038d61d3b57)
![image](https://github.com/redleafnew/zotero-updateifsE/assets/22135631/7db7ee75-8653-44a5-9a57-276937daae5d)

**Comment by ramonmi** [comment]
> > > 非常感谢，我经过尝试，发现对于化学元素加脚标，例如Fe2这一类的，均会变为小写，以钙钛矿相关文献最为常遇到，想请您看看是否可以通过代码规避这类问题。Ni，Sr，La，Ti，Co，Mo等
> > 
> > 
> > 可以是可以，但是如果单词中也有这些字母，也会转变，除非严格匹配。
> 
> 这些情况使用查找替换吧。 ![image](https://private-user-images.githubusercontent.com/22135631/313402311-6b77991a-1eb6-4d54-894b-9038d61d3b57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MDA4MjQsIm5iZiI6MTcxMDYwMDUyNCwicGF0aCI6Ii8yMjEzNTYzMS8zMTM0MDIzMTEtNmI3Nzk5MWEtMWViNi00ZDU0LTg5NGItOTAzOGQ2MWQzYjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE0NDg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMDUzMzJhODBiY2FlZDI3OGFkMzM1ZTVkNDg2NzdlOGY2MjQ5ZTRmOGFiZGEzYWI4OTMzMDNmYWU3ZWZhYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0pMFu4751CVkDJkd9FqAzTRGK79LIYsTtrGw0kaowrA) ![image](https://private-user-images.githubusercontent.com/22135631/313402346-7db7ee75-8653-44a5-9a57-276937daae5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MDA4MjQsIm5iZiI6MTcxMDYwMDUyNCwicGF0aCI6Ii8yMjEzNTYzMS8zMTM0MDIzNDYtN2RiN2VlNzUtODY1My00NGE1LTlhNTctMjc2OTM3ZGFhZTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE0NDg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNzY1ZjU5MTE3NzBkNjk5NTFkMTlkNTM2NzdiNDRjODYxMjEyN2UxZjYyYWVhZWE5ZDQ1NTRkZDc4NDY0MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cjmeHpuD30ppQ2_9RLJlMaDrlfzVCGESyCbk6-iHTE8)

好的，感谢提供解决思路
