### ISSUE TITLE
增加更新 期刊标签显示  sciUpTop	中科院升级版Top分区功能

### ISSUE THREAD

**Issue by shanleyao** [redleafnew/zotero-updateifsE#142]
建议增加更新 期刊标签显示  sciUpTop	中科院升级版Top分区功能
![微信截图_20240320104946](https://github.com/redleafnew/zotero-updateifsE/assets/50385618/3c29773b-3202-4b44-a33b-b946b9af0e90)

**Comment by redleafnew** [comment]
我抽时间搞一下。

**Comment by redleafnew** [comment]
有没有这些期刊的名称，TOP的、Small、ESI的期刊，我试试一下，最好导出为JSON我试试。

**Comment by redleafnew** [comment]
已更新，请下载最新版
