### ISSUE TITLE
绿青蛙对PDF的高亮标记做出反应，每次添加新的高亮标记，绿青蛙就显示抓取错误

### ISSUE THREAD

**Issue by pingping99** [redleafnew/zotero-updateifsE#143]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/63088567/352f1b4d-62e2-4361-b26d-99403c9bf453)
这是一个无关痛痒的BUG，不会引起实质性的错误，不过影响体验，希望开发者大大有时间的话可以优化一下，非常感谢！

**Comment by redleafnew** [comment]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/22135631/15ad87d1-c3e6-427e-980b-b6f4c3869798)
应该是触发新增条目了，可以试试先这把个禁用一下，有时间我再看看。

**Comment by pingping99** [comment]
谢谢大佬的回复，禁用后不再触发，但是这样就得手动为新增的条目获取期刊信息了，希望有时间能修复一下，祝生活愉快！

**Comment by redleafnew** [comment]
我没有用Zotero自带的阅读器，进行什么操作时会提示的，我用这个工作时没有提示更新啊
![image](https://github.com/redleafnew/zotero-updateifsE/assets/22135631/5c11cf7f-5a26-4b84-9ec2-325faf72292a)

**Comment by pingping99** [comment]
我使用的是自带的PDF阅读器，有可能是这个原因

**Comment by redleafnew** [comment]
我就是在自带阅读器中操作的，平时不用自带的，为了测试用了自带的。

**Comment by pingping99** [comment]
我把添加条目时更新期刊信息打开，还是会这样，可能和我之前装了zotero7有关系也不一定

**Comment by redleafnew** [comment]
我用的是针对Zotero 7.0的版本，你用的哪个版本？

**Comment by pingping99** [comment]
我用的是6
发自我的 iPhone

在 2024年3月30日，19:58，redleafnew ***@***.***> 写道：

﻿

我用的是针对Zotero 7.0的版本，你用的哪个版本？

**Comment by redleafnew** [comment]
针对6.0版本的不再更新维护了。

**Comment by pingping99** [comment]
好的，谢谢大佬解答
发自我的 iPhone

在 2024年3月30日，21:00，redleafnew ***@***.***> 写道：

﻿

针对6.0版本的不再更新维护了。
