### ISSUE TITLE
会议文章无法更新条目元数据

### ISSUE THREAD

**Issue by zhouzinan** [redleafnew/zotero-updateifsE#144]
您好，请问为什么我所有的会议论文下方的更新条目元数据按钮无法使用呢。是不是因为我缺少部分字段信息。
我的zotero版本是6.0.37，插件版本是0.13.0

**Comment by redleafnew** [comment]
只有期刊可以更新元数据，但现在好像也不太好用了。

**Comment by zhouzinan** [comment]
请问这和easyScholar提供的功能有关吗，以后还会有支持会议信息的更新吗？

**Comment by redleafnew** [comment]
这个功能不是easyScholar提供的，源代码来源于https://getquicker.net/Sharedaction?code=78da8f40-e73a-46e8-da6b-08da76a0d1ac  可以向ttchen老师反馈。

**Comment by zhouzinan** [comment]
谢谢您，我看到ttChen老师23.7.19号的更新日志中说明了已经可以支持会议论文了，请问updateifsE当前版本是还没有同步这个功能吗？

**Comment by redleafnew** [comment]
添加上DOI试试

**Comment by zhouzinan** [comment]
尝试了一下还是不可以，是该功能本身可能存在问题，还是没有updateifsE没有更新这个功能有关呢

**Comment by redleafnew** [comment]
针对6.0的版本不再维护了。试试ttchen那个quicker动作行不行。
