### ISSUE TITLE
easyscholar查不到此期刊的等级信息

### ISSUE THREAD

**Issue by CarbonArt** [redleafnew/zotero-updateifsE#145]
![错误信息](https://github.com/redleafnew/zotero-updateifsE/assets/128869949/f583536b-3126-4f50-8e27-0e1f85353c20)

**Comment by redleafnew** [comment]
在Zotero中选中条目，Tools-Developer-Run JS，看看结果是什么

```
var items = ZoteroPane.getSelectedItems();
  var item = items[0]; 
  let secretKey = Zotero.Prefs.get('extensions.zotero.greenfrog.secretkey', true);
  //publicationTitle =encodeURIComponent(item.getField('publicationTitle'));
  var publicationTitle = Zotero.ItemTypes.getName(item.itemTypeID) == 'journalArticle' ?
      encodeURIComponent(item.getField('publicationTitle')) :
      encodeURIComponent(item.getField('conferenceName') );
   
  var url = `https://easyscholar.cc/open/getPublicationRank?secretKey=${secretKey}&publicationName=${publicationTitle}`;
  let req = await Zotero.HTTP.request('GET', url, { responseType: 'json' });
  return req.response;
```

**Comment by CarbonArt** [comment]
复制运行后的结果：
![结果](https://github.com/redleafnew/zotero-updateifsE/assets/128869949/33a0b3e9-50c7-4b0e-86a6-63b2cacddbf6)

**Comment by redleafnew** [comment]
应该是期刊名称的问题，把文献条目的JSON格式发上来看看

**Comment by CarbonArt** [comment]
应该就是你说的期刊名称的问题，我手动修改了期刊的全称，然后之前的那个错误信息就没有出现，但是我发现还有其他问题，就是影响影子更新不出来，之前可以不知道从什么开始就不行了。
<img width="609" alt="image" src="https://github.com/redleafnew/zotero-updateifsE/assets/128869949/47205e4b-b29f-4a57-b4a1-618e5d15e397">

**Comment by redleafnew** [comment]
哪个期刊，把条目JSON发上来。

**Comment by CarbonArt** [comment]
怎么查看条目的JSON格式？

**Comment by redleafnew** [comment]
条目上右击，导出，JSON

**Comment by CarbonArt** [comment]
[Uploading 导出的条目.json…]()

**Comment by redleafnew** [comment]
无法下载，用记事本打开，把里面内容粘贴到这也可以

**Comment by CarbonArt** [comment]
![Uploading 1.png…]()
![Uploading 2.png…]()

**Comment by CarbonArt** [comment]
<html><head></head><body><div id="content"><div class="tabs tabs-tall "><nav class="tabs-navigation"><ul class="tabs-menu" role="tablist"><li class="tabs-menu-item json is-active" role="presentation"><span class="devtools-tab-line"></span></li></ul></nav></div></div><span class="devtools-tab-line"></span><span class="devtools-tab-line"></span><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"></div></div></div></div><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"><div class="devtools-separator"></div><div class="devtools-searchbox"><input class="searchBox devtools-filterinput" placeholder="过滤 JSON" value=""></div></div><div class="panelContent" id="json-scrolling-panel" tabindex="0">
  |  
-- | --
0 |  
id | "http://zotero.org/users/6480813/items/5BI9NSZY"
type | "article-journal"
abstract | "The α-umpolung of carbonyl compounds significantly expands the boundaries of traditional carbonyl chemistry. Despite various umpolung methods available today, reversing the inherent reactivity of carbonyls still remains a substantial challenge. In this article, we report the first use of sulfonium salts, in lieu of well-established hypervalent iodines, for the carbonyl umpolung event. The protocol enables the incorporation of a wide variety of heteroatom nucleophiles into the α-carbon of 2-oxazolines. The success of this investigation hinges on the following factors: (1) the use of sulfoxides, which are abundant, structurally diverse and tunable, and easily accessible, ensures the identification of a superior oxidant namely phenoxathiin sulfoxide for the umpolung reaction; (2) the “assembly/deprotonation” protocol previously developed for rearrangement reactions in our laboratory was successfully applied here for the construction of α-umpoled 2-oxazolines."
container-title | "Chemical Science"
DOI | "10.1039/D2SC00476C"
ISSN | "2041-6539"
issue | "18"
journalAbbreviation | "Chem. Sci."
language | "el"
note | "publisher: The Royal Society of Chemistry"
page | "5164-5170"
source | "pubs.rsc.org"
title | "Sulfur(IV)-mediated umpolung α-heterofunctionalization of 2-oxazolines"
URL | "https://pubs.rsc.org/en/content/articlelanding/2022/sc/d2sc00476c"
volume | "13"
author |  
0 |  
family | "Zhang"
given | "Qifeng"
1 |  
family | "Liang"
given | "Yuchen"
2 |  
family | "Li"
given | "Ruiqi"
3 |  
family | "Huang"
given | "Ziyi"
4 |  
family | "Kong"
given | "Lichun"
5 |  
family | "Du"
given | "Peng"
6 |  
family | "Peng"
given | "Bo"
accessed |  
date-parts |  
0 |  
0 | "2024"
1 | 2
2 | 20
issued |  
date-parts |  
0 |  
0 | "2022"
1 | 5
2 | 11

</div></div></div></div></body></html>

**Comment by redleafnew** [comment]
不要图片格式，我无法复制

**Comment by CarbonArt** [comment]
重新复制了，现在可以吗？

**Comment by redleafnew** [comment]
格式是乱的，我导入不到我的Zotero中

**Comment by CarbonArt** [comment]
[导出的条目.json](https://github.com/redleafnew/zotero-updateifsE/files/14892933/default.json)

**Comment by CarbonArt** [comment]
现在呢？

**Comment by redleafnew** [comment]
publisher: The Royal Society of Chemistry
JCR分区: Q1
中科院分区升级版: 化学1区
影响因子: 8.4
5年影响因子: 8.6
EI: 是
中科院升级版Top分区: 化学TOP
中科院升级版小类分区: 化学：综合1区
ESI: 化学
南农高质量: A

**Comment by CarbonArt** [comment]
那我这个问题的原因可能是什么？

**Comment by CarbonArt** [comment]
从easyscholar更新期刊信息，就是没有影响因子

**Comment by redleafnew** [comment]
哪没有影响因子？

**Comment by CarbonArt** [comment]
![Uploading 22.png…]()

**Comment by CarbonArt** [comment]
![Uploading 33.png…]()

**Comment by redleafnew** [comment]
图片看不到

**Comment by CarbonArt** [comment]
![44](https://github.com/redleafnew/zotero-updateifsE/assets/128869949/b06770f9-583b-4fe5-8040-ef4a6ed3b120)

**Comment by CarbonArt** [comment]
右侧栏-“其他”也没有影响因子信息

**Comment by redleafnew** [comment]
你用得哪个版本的GreenFrog和Zotero？

**Comment by CarbonArt** [comment]
greenfrog是0.18.0，zotero是7.0.0-beta.68

**Comment by redleafnew** [comment]
QQ：1361942015，安装Todesk远程看一下。
