### ISSUE TITLE
启动zotero提示错误信息

### ISSUE THREAD

**Issue by wulidede** [redleafnew/zotero-updateifsE#146]
当我启动zotero会出现错误信息，

> Error opening input stream (invalid filename?): jar:file:///C:/Users/zhanghd/AppData/Roaming/Zotero/Zotero/Profiles/f4aoo06c.zotero7/extensions/greenfrog@redleafnew.me.xpi!/bootstrap.js
<img width="1282" alt="1712107105961" src="https://github.com/redleafnew/zotero-updateifsE/assets/90752609/752a9435-3021-420a-91d5-6bd7867a1616">
点击“检查更新”，没有更新版本可用，只能退出

**Comment by redleafnew** [comment]
我也不知道是怎么回事？重新安装一下插件可以解决吗？

**Comment by wulidede** [comment]
但是我一启动zotero就弹窗这个，操作不了菜单栏

**Comment by wulidede** [comment]
有办法有命令行重装插件吗？

**Comment by redleafnew** [comment]
可以启动Zotero时，按住shift，禁用所有插件

**Comment by wulidede** [comment]
感谢大佬，禁用插件之后重装，目前可以正常使用了，本来都打算重装zotero了。
