### ISSUE TITLE
显示查询不到期刊等级（会议论文）

### ISSUE THREAD

**Issue by 1071189147** [redleafnew/zotero-updateifsE#147]
版本信息：
  zotero 7.0.0-beta.68+c31a40c74 (64-bit)
  green frog 0.18.
根据您其他的issues给的JS,得到以下：

{
    "code": 200
    "msg": "SUCCESS"
    "data": {
        "customRank": {
            "rankInfo": [
                "0": {
                    "uuid": "1614919989423271936"
                    "abbName": "CCF"
                    "oneRankText": "A"
                    "twoRankText": "B"
                    "threeRankText": "C"
                }
                "1": {
                    "uuid": "1676584188322156544"
                    "abbName": "CCF_CN"
                    "oneRankText": "A"
                    "twoRankText": "B"
                    "threeRankText": "C"
                }
            ]
            "rank": [
                "0": "1614919989423271936&&&1"
            ]
        }
        "officialRank": {
            "all": null
            "select": null
        }
    }
}

我在easyscholar的官方接口文档中看到：

> “customRank：
> rankInfo代表用户添加的数据集信息，可能包含多个，具体字段解释见附录2。
> **rank**代表该期刊在自定义数据集中的等级，结构构成为{{rankInfo.uuid}}&&&{{rank}}。首先通过split()函数获得uuid与rank，前者为数据集的uuid，通过此uuid前往rankInfo中寻找uuid相同的自定义数据集，获得其缩写；后者为等级，范围[1-5]，通过此范围前往自定义数据集中，获得对应的等级缩写。”
> 

**上面的返回结果中，官方的等级确实查询不到，为NULL，但是用户自定义的等级customRank ，显示是uuid为1614919989423271936中第一个:A**，

您看一下是否需要修改什么呢

**Comment by redleafnew** [comment]
想查在哪个数据库的等级。这个UUID是CCF的。

**Comment by 1071189147** [comment]
不好意思，是我没有表述清楚，就查这个CCF数据库等级就可以，

我发现easyscholar返回结果中有需要的信息，但是是在“customRank“用户自定义的里面，而不是在官方数据库中"officialRank"，

但是提示还是显示查询不到期刊等级，这种情况是greenfog的问题吗，或者我应该怎么做呢？

**Comment by redleafnew** [comment]
1. 在Green Frog设置中选中CCF可以吗？
2. 条目的JSON格式发一下（选中条目，右击，导出，选择JSON）。

**Comment by 1071189147** [comment]
1.:green frog 中之前已经选择了 中国计算机学会（即CCF），
2： [
	{
		"id": "sayedImprovedHandlingMotion2021a",
		"type": "paper-conference",
		"abstract": "We wish to detect speciﬁc categories of objects, for online vision systems that will run in the real world. Object detection is already very challenging. It is even harder when the images are blurred, from the camera being in a car or a hand-held phone. Most existing efforts either focused on sharp images, with easy to label ground truth, or they have treated motion blur as one of many generic corruptions.",
		"container-title": "2021 IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR)",
		"DOI": "10.1109/CVPR46437.2021.00175",
		"event-place": "Nashville, TN, USA",
		"event-title": "2021 IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR)",
		"ISBN": "978-1-66544-509-2",
		"language": "en",
		"license": "https://ieeexplore.ieee.org/Xplorehelp/downloads/license-information/IEEE.html",
		"page": "1706-1716",
		"publisher": "IEEE",
		"publisher-place": "Nashville, TN, USA",
		"source": "DOI.org (Crossref)",
		"title": "Improved handling of motion blur in online object detection",
		"URL": "https://ieeexplore.ieee.org/document/9578729/",
		"author": [
			{
				"family": "Sayed",
				"given": "Mohamed"
			},
			{
				"family": "Brostow",
				"given": "Gabriel"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2024",
					4,
					8
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2021",
					6
				]
			]
		}
	}
]

**Comment by redleafnew** [comment]
这个应该是在自定义数据集中，当前GreenFrog好像还不包括这个。

**Comment by 1071189147** [comment]
> 这个应该是在自定义数据集中，当前GreenFrog好像还不包括这个。

请问还可以添加吗？ＣＣＦ在计算机领域还挺权威的，我看已有四个自定义数据集，这个自定义数据集比ｅａｓｙｓｃｈｏｌａｒ官方的好用，这个自定义数据集采用模糊匹配方式，对会议的识别，相对官方的而言较为准确。

（像CVPR这个会议，官方数据库必须严格是“Computer Vision and Pattern Recognition”才能匹配上，但是这个自定义数据集只要包含就可以，论文导出时候，一般都会带上年份还有IEEE什么的，官方的基本都是失败）

如果您时间有限，需要协助的可以安排给我，我也可以写一些代码。

**Comment by redleafnew** [comment]
可以下载源代码后，搜索自`定义数据集`，参考已经有的来增加，现在只支持几个自定义的数据集。

**Comment by redleafnew** [comment]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/22135631/96ab55fa-dae2-4283-bc26-ce17ddfe841e)

**Comment by 1071189147** [comment]
好的，十分感谢，我尝试做一下，之后Commit您这边看一下
