### ISSUE TITLE
在安装时提示软件不兼容

### ISSUE THREAD

**Issue by zhang-lightning** [redleafnew/zotero-updateifsE#148]
当前zotero版本为6.0.36，我尝试安装了最近的5个release版本，都提示说该插件与当前版本不兼容。

原报错为：

无法安装插件“%S”。它可能无法与该版本的 Zotero 兼容。

调试日志如下：
-----------------------------
1712894047897	addons.xpi	WARN	Invalid XPI: Error: Extension is invalid (resource://gre/modules/addons/XPIInstall.jsm:307:11) JS Stack trace: loadManifestFromWebManifest@XPIInstall.jsm:307:11

[JavaScript Error: "1712894078313	addons.webextension.<unknown>	ERROR	Loading extension 'null': Reading manifest: Error processing applications: Unexpected property "zotero"" {file: "resource://gre/modules/Log.jsm" line: 797}]
App_append@resource://gre/modules/Log.jsm:797:9
log@resource://gre/modules/Log.jsm:435:7
error@resource://gre/modules/Log.jsm:443:5
_logMessage@resource://gre/modules/Extension.jsm:339:5
logError@resource://gre/modules/Extension.jsm:335:5
packagingError@resource://gre/modules/Extension.jsm:322:5
manifestError@resource://gre/modules/Extension.jsm:308:5
parseManifest@resource://gre/modules/Extension.jsm:569:7

1712894078314	addons.xpi	WARN	Invalid XPI: Error: Extension is invalid (resource://gre/modules/addons/XPIInstall.jsm:307:11) JS Stack trace: loadManifestFromWebManifest@XPIInstall.jsm:307:11

[JavaScript Error: "1712894097655	addons.webextension.<unknown>	ERROR	Loading extension 'null': Reading manifest: Error processing applications: Unexpected property "zotero"" {file: "resource://gre/modules/Log.jsm" line: 797}]
App_append@resource://gre/modules/Log.jsm:797:9
log@resource://gre/modules/Log.jsm:435:7
error@resource://gre/modules/Log.jsm:443:5
_logMessage@resource://gre/modules/Extension.jsm:339:5
logError@resource://gre/modules/Extension.jsm:335:5
packagingError@resource://gre/modules/Extension.jsm:322:5
manifestError@resource://gre/modules/Extension.jsm:308:5
parseManifest@resource://gre/modules/Extension.jsm:569:7

1712894097655	addons.xpi	WARN	Invalid XPI: Error: Extension is invalid (resource://gre/modules/addons/XPIInstall.jsm:307:11) JS Stack trace: loadManifestFromWebManifest@XPIInstall.jsm:307:11

[JavaScript Error: "1712894271820	addons.webextension.<unknown>	ERROR	Loading extension 'null': Reading manifest: Error processing applications: Unexpected property "zotero"" {file: "resource://gre/modules/Log.jsm" line: 797}]
App_append@resource://gre/modules/Log.jsm:797:9
log@resource://gre/modules/Log.jsm:435:7
error@resource://gre/modules/Log.jsm:443:5
_logMessage@resource://gre/modules/Extension.jsm:339:5
logError@resource://gre/modules/Extension.jsm:335:5
packagingError@resource://gre/modules/Extension.jsm:322:5
manifestError@resource://gre/modules/Extension.jsm:308:5
parseManifest@resource://gre/modules/Extension.jsm:569:7

1712894271820	addons.xpi	WARN	Invalid XPI: Error: Extension is invalid (resource://gre/modules/addons/XPIInstall.jsm:307:11) JS Stack trace: loadManifestFromWebManifest@XPIInstall.jsm:307:11

version => 6.0.36, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => zh-CN, appName => Zotero, appVersion => 6.0.36, extensions => Zotero LibreOffice Integration (6.0.4.SA.6.0.36, extension), Zotero Word for Windows Integration (6.0.4.SA.6.0.36, extension), Zotero Style (2.6.7, extension)

**Comment by redleafnew** [comment]
最新版仅支持Zotero 7.0, Zotero 6.0请下载[0.13.0](https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.13.0)。
