### ISSUE TITLE
无法从easyscholar获取到信息

### ISSUE THREAD

**Issue by RemWisteria** [redleafnew/zotero-updateifsE#149]
右键选择“从easyscholar更新期刊信息”后，期刊信息无法更新，且未弹出任何“成功/失败”的提示框。

我前往easyscholar的“开发接口”界面发现，每次在zotero中点击“从easyscholar更新期刊信息”后，调用次数都会正常增加。我将涉及的期刊在“开发接口”中进行了测试，可以正常返回信息。但在zotero中，无法正常更新数据。

zotero版本：7.0.0-beta.73+398454f85 (64-bit)
green frog版本：0.18.0(2024年3月29日)

**Comment by redleafnew** [comment]
好像是出问题了，等有时间了再修复。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.18.01

当前自定义数据集和南农高质量期刊无法获取，请先禁用，否则无法使用。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/tree/0.18.02

**Comment by yichenwang100** [comment]
牛啊！昨天还不能用，今天升级了就能用了
