### ISSUE TITLE
CCF分区支持

### ISSUE THREAD

**Issue by zxf8876983** [redleafnew/zotero-updateifsE#15]
请求增加CCF分区支持，https://www.ccf.org.cn/Academic_Evaluation/By_category/

**Comment by redleafnew** [comment]
插件数据来源于https://easyscholar.cc/，没有本地数据，你可以先请EasyScholar集成，再开放接口。

**Comment by redleafnew** [comment]
你能将数据转为json吗？https://github.com/gitpwj/Js_load_remote_json/blob/master/j.json类似，我考虑写一个quicker来完成。

**Comment by redleafnew** [comment]
https://getquicker.net/Sharedaction?code=f85864b1-9fd8-4fd4-7a13-08dad1ec0ec6

写入到Extra了。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.6.0 
已添加。
