### ISSUE TITLE
[Feature]期刊信息全局更新功能

### ISSUE THREAD

**Issue by nkh0472** [redleafnew/zotero-updateifsE#150]
在文献库包含大量条目的情况下，会面临期刊数据过期的情况。
希望能够添加一个手动触发的按钮，以实现对文献库中所有期刊信息的全局更新。

更新的功能实现类似 #136，即枚举文献库内的全部期刊，对每一种期刊进行一次查询，再批量更新所有该期刊的条目。
（虽然维护本地数据库缓存+对比更新是更加精细的方法，但需要的变动更大，必要性较低；好处是即使单篇导入文献时也可以匹配缓存，减少请求数）

近期我尝试通过高级搜索手动修正一些中科院分区不一致的数据，仅影响因子这一项就修正了数百个条目。
但对于文献库内条目数较少的期刊来说，可能根本没有机会发现不一致，因为它们的条目未包含更新后的信息。

预计这个功能的使用频率将至少每年一次，但不会非常高，因为中科院分区和JCR影响因子都是每年更新一次。
在大型文献库的情况下，通过手动筛选完成这项任务是不可能的。而如果全选所有条目，更新需要的时间、请求数量都会数倍增长。

作为参考，我的文献库总条目2104个（期刊1322个），但实际的期刊种类不过300多种。
如果是只进行300次左右的查询，按照easyscholar接口推荐的0.5秒一次的查询速度，其实2.5分钟就可以完成。

**Comment by redleafnew** [comment]
不搞这么复杂的功能了，这类信息也就是一个参考。如果觉得有问题，可以手动更新一下。
