### ISSUE TITLE
在一次打开后突然无法更新期刊信息

### ISSUE THREAD

**Issue by hexiovo** [redleafnew/zotero-updateifsE#151]
2024.4.14 登录后发现无法更新IF与IF（5 years），卸载重装后问题仍旧存在，右键选择更新后不提示失败或成功，无任何反应。
打开添加条目时更新，在进入后弹出更新失败。
![Q_RC)8~3R830JUB75)_1ZG2](https://github.com/redleafnew/zotero-updateifsE/assets/147052623/21aef1f0-a407-45cd-a399-a70c6c917b7c)
注：与文献无关，任何文献都会失败。
在网站中测试开放接口发现正常，调用次数加一
但若是在Zotero中进行右键选择更新（一篇文献），easyscholar中调用次数加四。

**Comment by redleafnew** [comment]
Zotero和Green Frog是哪个版本？

**Comment by hexiovo** [comment]
zotero是6，frog是0.13.0

**Comment by redleafnew** [comment]
针对6.0的不再维护了。

**Comment by hexiovo** [comment]
好的好的，麻烦啦，我更新下zotero吧
