### ISSUE TITLE
能显示ABDC排名吗？我们学校非常重视这个值

### ISSUE THREAD

**Issue by zzlb0224** [redleafnew/zotero-updateifsE#153]
能显示ABDC排名吗？我们学校非常重视这个值

**Comment by redleafnew** [comment]
哪个学校？easyScholar中这个数据提供吗？

**Comment by zzlb0224** [comment]
> 哪个学校？easyScholar中这个数据提供吗？

UCSI university
也可能是部分老师的要求，引用尽量使用带A的

**Comment by zzlb0224** [comment]
> 哪个学校？easyScholar中这个数据提供吗？

![image](https://github.com/redleafnew/zotero-updateifsE/assets/8912444/df8142e3-ad1e-45e8-b211-51bffb9df998)

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/pull/154  是你提的吗？我还没有看

**Comment by zzlb0224** [comment]
> #154 是你提的吗？我还没有看

是的，麻烦大佬审一审

**Comment by zzlb0224** [comment]
// 如果得到easyScholar、影响因子、法学数据或南农数据才算更新成功
        // 请问这里是不是只有配置了显示clsciLevel，才需要这样做检查？
        if (easyscholarData || chineseIFs ||
          clsciLevel || amiLevel || nssfLevel ||
          njauCore(item) || njauHighQuality) {
          if (emptyExtra) { item.setField('extra', '') }
          n++
        }

![image](https://github.com/redleafnew/zotero-updateifsE/assets/8912444/b79f3a43-07fc-4203-bb41-923560a8d34d)

**Comment by redleafnew** [comment]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/22135631/40f72d01-4577-4efa-9f50-b3ab63afc860)
为什么scopus的分类是这样？

**Comment by zzlb0224** [comment]
Scopus 字段只有 是/否，

"rank" 中包含了就是是，不然就是否

**Comment by zzlb0224** [comment]
抱歉，这里还有个bug，
应该是
 `       // Scopus
        if (Scopus && ScopusLevel != undefined) {
          ztoolkit.ExtraField.setExtraField(item, 'Scopus', "是");
        }
`

![image](https://github.com/redleafnew/zotero-updateifsE/assets/8912444/f12a789f-5574-490c-8ddb-70e83a08d83d)

**Comment by redleafnew** [comment]
我看好像差不多，在PR中更新一下

**Comment by redleafnew** [comment]
> ```
>     // 如果得到easyScholar、影响因子、法学数据或南农数据才算更新成功
>     // 请问这里是不是只有配置了显示clsciLevel，才需要这样做检查？
>     if (easyscholarData || chineseIFs ||
>       clsciLevel || amiLevel || nssfLevel ||
>       njauCore(item) || njauHighQuality) {
>       if (emptyExtra) { item.setField('extra', '') }
>       n++
>     }
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/8912444/323791281-b79f3a43-07fc-4203-bb41-923560a8d34d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0ODU1NTQsIm5iZiI6MTcxMzQ4NTI1NCwicGF0aCI6Ii84OTEyNDQ0LzMyMzc5MTI4MS1iNzlmM2E0My0wN2ZjLTQyMDMtYmI0MS05MjM1NjBhOGQzNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTlUMDAwNzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDJlZTFjMjg5YjhhNjk3N2I3YmIwNmM2MTFkODUwMTdhYmYyYTM0MmYzZTZiNWVjYjJlZjQyOTY0MTFiZWRmNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GT44RJatYOAixrQYspBSIsuYJZqywJ2ChONdBQtFbuY)

这个的意思是有其中一个有数据就算是一条数据更新了，<code>if</code>中可以增加<code>ScopusLevel</code>和<code>ABDCLevel</code>的检测

**Comment by redleafnew** [comment]
更新后告诉一下。

**Comment by redleafnew** [comment]
你编译、测试过效果吗？

**Comment by zzlb0224** [comment]
> 你编译、测试过效果吗？

我本地测试好了

**Comment by redleafnew** [comment]
我合并了，给我两个条目吧，我测试一下。

**Comment by redleafnew** [comment]
Scopus的我测试没有问题，
ADCB的给我一个条目吧

**Comment by redleafnew** [comment]
随便找了几，没有问题了。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.19.0
