### ISSUE TITLE
easyscholar查不到所有期刊的等级信息；更新不出影响影子，高效期刊分级等所有信息；

### ISSUE THREAD

**Issue by CarbonArt** [redleafnew/zotero-updateifsE#156]
我尝试用greenfrog更新不同期刊，都是出现easyscholar查不到此期刊的等级信息；

**Comment by redleafnew** [comment]
把期刊名称发上来试试。
或是运行以下代码，看看有无结果。
 ```
 // var items = ZoteroPane.getSelectedItems();
  var items = Zotero.getActiveZoteroPane().getSelectedItems();
  var item = items[0]; 
  let secretKey = Zotero.Prefs.get('extensions.zotero.greenfrog.secretkey', true);
  //publicationTitle =encodeURIComponent(item.getField('publicationTitle'));
  var publicationTitle = Zotero.ItemTypes.getName(item.itemTypeID) == 'journalArticle' ?
      encodeURIComponent(item.getField('publicationTitle')) :
      encodeURIComponent(item.getField('conferenceName') );
   
  var url = `https://easyscholar.cc/open/getPublicationRank?secretKey=${secretKey}&publicationName=${publicationTitle}`;
  let req = await Zotero.HTTP.request('GET', url, { responseType: 'json' });
  return req.response['data']["officialRank"]["all"]
```

**Comment by StarXian** [comment]
TypeError: req.response.data is null

**Comment by redleafnew** [comment]
> TypeError: req.response.data is null

哪个期刊，把条目复制过来。

**Comment by CarbonArt** [comment]
搞定了，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月2日(周五) 下午3:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [redleafnew/zotero-updateifsE] easyscholar查不到所有期刊的等级信息；更新不出影响影子，高效期刊分级等所有信息； (Issue #156)




  
TypeError: req.response.data is null
  
哪个期刊，把条目复制过来。

**Comment by alicejia123** [comment]
请问是怎么解决的呢？我也出现了这个问题

**Comment by redleafnew** [comment]
> 把期刊名称发上来试试。 或是运行以下代码，看看有无结果。
> 
> ```
> // var items = Zot
> ```

按这个试试。

**Comment by CarbonArt** [comment]
easyscholar本身的免费调用次数用光了，我重新申请了一个账户，如果你不想换。账户也可以买个会员。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月9日(周一) 上午9:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [redleafnew/zotero-updateifsE] easyscholar查不到所有期刊的等级信息；更新不出影响影子，高效期刊分级等所有信息； (Issue #156)




 
请问是怎么解决的呢？我也出现了这个问题

**Comment by alicejia123** [comment]
> > 把期刊名称发上来试试。 或是运行以下代码，看看有无结果。
> > ```
> > // var items = Zot
> > ```
> 
> 按这个试试。



> easyscholar本身的免费调用次数用光了，我重新申请了一个账户，如果你不想换。账户也可以买个会员。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年9月9日(周一) 上午9:42 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [redleafnew/zotero-updateifsE] easyscholar查不到所有期刊的等级信息；更新不出影响影子，高效期刊分级等所有信息； (Issue #156) 请问是怎么解决的呢？我也出现了这个问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

好的好的，感谢！
