### ISSUE TITLE
AJG分区

### ISSUE THREAD

**Issue by byhwsh** [redleafnew/zotero-updateifsE#16]
easyscholar有包括UTD 24，AJG和FT 50三个数据库，请问是否可使用这个插件获得这三个分区呢？

**Comment by redleafnew** [comment]
这是什么学科的，没有向easyScholar要接口。

**Comment by byhwsh** [comment]
> 这是什么学科的，没有向easyScholar要接口。

这三个都是管理类的。不清楚这个插件接easyscholar数据库的原理，因为easyscholar有这三类的分区显示，我以为可以直接调用。莽撞了莽撞了，哈哈哈哈，谢谢回复！

**Comment by redleafnew** [comment]
是参考唯问插件版，找作者友情提供的接口，也没有更多的字段写入了。

**Comment by redleafnew** [comment]
@byhwsh 能将这三个数据库转为json吗？类似https://github.com/gitpwj/Js_load_remote_json/blob/master/j.json

**Comment by redleafnew** [comment]
有这三个数据库文章的例子吗？

**Comment by redleafnew** [comment]
将返回的信息写入到哪个字段？

**Comment by byhwsh** [comment]
> 有这三个数据库文章的例子吗？

Bayesian ordinal regression for multiple criteria choice and ranking, **European Journal of Operational Research**, **AJG 4**

Hu, Jian, Junxuan Li, and Sanjay Mehrotra. ‘A Data-Driven Functionally Robust Approach for Simultaneous Pricing and Order Quantity Decisions with Unknown Demand Function’. **Operations Research** 67, no. 6 (November 2019): 1564–85. https://doi.org/10.1287/opre.2019.1849., 同时属于：**AJG 4,UTD 24, FT 50**

**Comment by byhwsh** [comment]
> 将返回的信息写入到哪个字段？

可以返回到rights?

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/204701151-ac3d81a9-245b-4fed-832d-d481061a4731.png)
我这怎么都不显示呢

**Comment by byhwsh** [comment]
> ![image](https://user-images.githubusercontent.com/22135631/204701151-ac3d81a9-245b-4fed-832d-d481061a4731.png) 我这怎么都不显示呢
可以在谷歌学术显示
<img width="547" alt="image" src="https://user-images.githubusercontent.com/93630761/204701291-d9741c78-c6c8-4629-92b4-e6bf09b98691.png">

**Comment by redleafnew** [comment]
文章主页也没有是吧。

**Comment by byhwsh** [comment]
> 文章主页也没有是吧。

嗯嗯，刚刚看了几篇论文，发现utd 24和ft 50两个分区的显示不会在文章主页显示，但是AJG可以在主页显示
<img width="564" alt="image" src="https://user-images.githubusercontent.com/93630761/204701772-1154a70f-efa5-4736-8cfc-c5c9cf67d85e.png">

**Comment by redleafnew** [comment]
我问一下作者的接口，写个quicker动作

**Comment by byhwsh** [comment]
> 我问一下作者的接口，写个quicker动作

感谢大佬！！！！！！

**Comment by redleafnew** [comment]
```
{
    "tempID": 2190
    "ajg": "4*"
    "ft50": "FT50"
    "utd24": "UTD24"
}
```
得到的结果如果是这样的，想写入的字段是什么样的？

**Comment by byhwsh** [comment]
> ```
> {
>     "tempID": 2190
>     "ajg": "4*"
>     "ft50": "FT50"
>     "utd24": "UTD24"
> }
> ```
> 
> 得到的结果如果是这样的，想写入的字段是什么样的？

我个人理想的情况是三者都显示在Rights字段，显示为：UTD 24；FT 50；AJG 4*

> ```
> {
>     "tempID": 2190
>     "ajg": "4*"
>     "ft50": "FT50"
>     "utd24": "UTD24"
> }
> ```
> 
> 得到的结果如果是这样的，想写入的字段是什么样的？

我个人理想的情况是三者都显示在Rights字段，显示为：UTD 24；FT 50；AJG 4*

**Comment by redleafnew** [comment]
已完成，等待审核。

**Comment by byhwsh** [comment]
> 已完成，等待审核。↳

这就是大佬的速度吗，太感谢了！！！！👍👍👍👍👍👍👍

**Comment by redleafnew** [comment]
https://getquicker.net/Sharedaction?code=d1edc903-d766-4181-79fe-08dad1ec0ec6

**Comment by byhwsh** [comment]
> https://getquicker.net/Sharedaction?code=d1edc903-d766-4181-79fe-08dad1ec0ec6↳
感谢！

**Comment by redleafnew** [comment]
UTD 24，AJG和FT 50这个三个有中文翻译名称吗？

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.6.0 
已添加。
