### ISSUE TITLE
更新条目按钮灰色无法点击

### ISSUE THREAD

**Issue by Marverlises** [redleafnew/zotero-updateifsE#164]
![image](https://github.com/user-attachments/assets/40e12b3d-9a58-4ae8-9a79-7694e2d0052d)
如图所示，我已经配置了easyScholar的密钥，但是无法点击/‘从easyScholar更新期刊信息/’

**Comment by redleafnew** [comment]
中文还是英文？英文DOI字段不能为空，中文题目不能为空。中文暂时可能用不了。

**Comment by Marverlises** [comment]
![image](https://github.com/user-attachments/assets/bdd9bfc5-7688-4e6c-8312-617b300ca051)
随便找了篇英文文献测试的

**Comment by thisisbaiy** [comment]
![Uploading image.png…]()
补充一下

**Comment by Marverlises** [comment]
![image](https://github.com/user-attachments/assets/8d8cf1a8-5e25-4bd5-86ca-d21c504b491a)
补充一下

**Comment by redleafnew** [comment]
DOI发一下

**Comment by Marverlises** [comment]
[10.48550/arXiv.1706.03762](http://doi.org/10.48550/arXiv.1706.03762)

**Comment by redleafnew** [comment]
![image](https://github.com/user-attachments/assets/7a7ecb50-6c5c-4ea2-af9f-d92d95e2c0c6)
这个DOI应该用Zotero无法导入，这是用导入DOI的方法显示的。

**Comment by redleafnew** [comment]
10.3136/fstr.11.135  你可以用这个试试

**Comment by Marverlises** [comment]
好的明白了，这个可以
![image](https://github.com/user-attachments/assets/370a036a-8bf5-4735-823c-8ec0757c4e0e)
好像大多数计算机领域的文章都不太能导入，不过还是感谢

**Comment by redleafnew** [comment]
代码是借用的这个动作：https://getquicker.net/Sharedaction?code=78da8f40-e73a-46e8-da6b-08da76a0d1ac

**Comment by Marverlises** [comment]
好的谢谢
