### ISSUE TITLE
所有信息导出时能否单独成列

### ISSUE THREAD

**Issue by LXSKING** [redleafnew/zotero-updateifsE#166]
影响因子、分区等信息，在zoter界面是单独成列，但在导出时，所有信息都聚在一列（其他）中。能否在导出时也单独成列，便于整理和统计。

**Comment by Izumiko** [comment]
同求，现在的信息都写在了元数据的`其他`项里面，能否像[scite-zotero-plugin](https://github.com/scitedotai/scite-zotero-plugin)一样，单独创建一个面板放置信息？

右下角那里
![](https://github.com/scitedotai/scite-zotero-plugin/raw/master/images/example-tally.png)

**Comment by redleafnew** [comment]
好像 style插件可以？
