### ISSUE TITLE
是否有可供actions & tag插件调用的api？避免每个条目都需要右击鼠标，选择更新期刊信息

### ISSUE THREAD

**Issue by ramonmi** [redleafnew/zotero-updateifsE#168]
- 如果有的话，应该怎么调用呢
- 如果没有，是否可以考虑增加，利用脚本实现easyscholar期刊信息和metadata更新，减少鼠标操作

**Comment by redleafnew** [comment]
可以参考https://getquicker.net/Sharedaction?code=d18a8cce-dc54-4eb9-7472-08db00d4e64a

**Comment by redleafnew** [comment]
https://getquicker.net/Sharedaction?code=f6297051-473e-4f4a-3472-08da7d9afa4f

**Comment by ramonmi** [comment]
好的，感谢回复
