### ISSUE TITLE
同步条目时，不要自动更新

### ISSUE THREAD

**Issue by zhikaiyici** [redleafnew/zotero-updateifsE#169]
在设置中开启”添加条目时更新期刊信息/缩写...“后，A端新添加的条目，在B端同步的行为会视为新添加，此时B端又会自动更新期刊信息/缩写...等，会将更改过的期刊缩写/条目标题等信息再次改回自动设置的内容。
可参考https://github.com/windingwind/zotero-actions-tags/commit/ea5d41a42ce382f20f5fb4d43e426c9be3a9f6b1

**Comment by redleafnew** [comment]
可以把自动更新关闭。
