### ISSUE TITLE
两个插件都安装过，现在用EasyscholarIF却用不了

### ISSUE THREAD

**Issue by philhsu1995** [redleafnew/zotero-updateifsE#17]
因为唯问IF插件这几天一直更新失败，发现是唯问的网站上不去。于是卸载了唯问IF插件，安装了EasyscholarIF插件。可能是因为在卸载安装的过程中，我在卸载唯问IF插件之后，没有重启zotero，又马上安装了EasyscholarIF插件。导致我安装完EasyscholarIF插件之后，发现里面的设置和唯问的一样，但是更新插件是失效的，更新影响因子没有任何反映。这该怎么解决呢？

**Comment by redleafnew** [comment]
设置确实和唯问一样的。不行把easyscholar也再卸载一下再重装。
所有的条目都没有办法更新吗？

**Comment by philhsu1995** [comment]
尝试了，卸载了之后再重装，更新if还是没有反应T_T，但是清除字段的功能倒是可以用，可能出了什么bug，我再试试好啦

**Comment by redleafnew** [comment]
所有的条目都没有办法更新吗？

**Comment by redleafnew** [comment]
可以新建一个profile试试，不过其他的插件也需要重装了。

**Comment by philhsu1995** [comment]
我没有新建profile，但是我这几天突然发现，EasyscholarIF插件可以用了！只要把[更新期刊缩写]取消勾选，关掉，就可以更新了！可能是不是有bug在里头，但是现在至少能用了。之前一直用唯问是因为唯问有中科院小分类，信息全一点。Easyscholar只有中科院大分类，大分类有点离谱，不如小分类更科学。不过Easyscholar更新速度确实快好多
