### ISSUE TITLE
之前其他项中复合/综合影响因子显示为英文缩写，项目栏无法识别；现在无法更新复合/综合影响因子（其他勾选项也不能更新）

### ISSUE THREAD

**Issue by tyleeee** [redleafnew/zotero-updateifsE#171]
<img width="808" alt="截屏2024-09-24 11 53 07" src="https://github.com/user-attachments/assets/705cc2f9-fc7a-49eb-bee4-d92a9c1ab099">
图1为最开始英文缩写但项目栏空
<img width="435" alt="截屏2024-09-24 11 53 53" src="https://github.com/user-attachments/assets/51ce776d-e576-4c38-af8b-cb072600342c">
图2为现在无法更新只显示部分期刊分类

**Comment by redleafnew** [comment]
试试最新版，看看综合、复合影响因子是否显示了。

**Comment by tyleeee** [comment]
> 试试最新版，看看综合、复合影响因子是否显示了。

可以更新了，非常感谢！！！
