### ISSUE TITLE
设置里面没有green frog插件的页面

### ISSUE THREAD

**Issue by minossssss** [redleafnew/zotero-updateifsE#172]
![image](https://github.com/user-attachments/assets/234acb3b-0f26-4d14-97c4-cb3357a01b43)

**Comment by redleafnew** [comment]
Zotero和GreenFrog都是最新版本吗？

**Comment by minossssss** [comment]
是的，昨天发现的。好像茉莉花也有一样的问题昨天修复了。

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月25日 13:16 |
| 收件人 | redleafnew/zotero-updateifsE ***@***.***> |
| 抄送人 | minossssss ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [redleafnew/zotero-updateifsE] 设置里面没有green frog插件的页面 (Issue #172) |

Zotero和GreenFrog都是最新版本吗？

**Comment by redleafnew** [comment]
等有时间了我升级一下工具箱试试。

**Comment by minossssss** [comment]
okok，谢谢大佬

**Comment by biostatYu** [comment]
我也遇到一样的问题了，安装后，设置里面还是没有插件

**Comment by Yume96** [comment]
同上，希望大佬能抽空调试一下，先谢谢了

**Comment by MadadamXie** [comment]
同上

**Comment by XCJ-LateFall** [comment]
同上，辛苦大佬调试一下，谢谢了

**Comment by redleafnew** [comment]
不好意思，这几天上课事情有些多。等有空了一定抓紧时间。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/v0.19.6
在各位大佬们的帮助下更新了一下，看看是否可以了。
