### ISSUE TITLE
有些期刊JCR分区不显示

### ISSUE THREAD

**Issue by xx22711** [redleafnew/zotero-updateifsE#177]
如图，期刊1、2、3JCR分区不正常显示，中科院分区是正常的，而且其他插件显示JCR分区是正常的。期刊4显示是正常的，不知道是咋回事，很长时间了
![期刊1](https://github.com/user-attachments/assets/5c7a255c-44c9-4bdc-8983-9b7ec4c6b574)
![期刊2](https://github.com/user-attachments/assets/f9901e14-a9cb-4a1d-8eaa-76a19f7bcdb7)
![期刊3](https://github.com/user-attachments/assets/16ef7898-e38f-42a5-a705-ec28a28c62ec)
![期刊4](https://github.com/user-attachments/assets/3aee09e2-0d92-4730-82a2-1c725346eeed)

**Comment by redleafnew** [comment]
具体哪个期刊不显示？

**Comment by redleafnew** [comment]
这些代码结果显示什么？
```
  // var items = ZoteroPane.getSelectedItems();
  var items = Zotero.getActiveZoteroPane().getSelectedItems();
  var item = items[0]; 
  let secretKey = Zotero.Prefs.get('extensions.zotero.greenfrog.secretkey', true);
  //publicationTitle =encodeURIComponent(item.getField('publicationTitle'));
  var publicationTitle = Zotero.ItemTypes.getName(item.itemTypeID) == 'journalArticle' ?
      encodeURIComponent(item.getField('publicationTitle')) :
      encodeURIComponent(item.getField('conferenceName') );
   
  var url = `https://easyscholar.cc/open/getPublicationRank?secretKey=${secretKey}&publicationName=${publicationTitle}`;
  let req = await Zotero.HTTP.request('GET', url, { responseType: 'json' });
  return req.response['data']["officialRank"]["all"]
```

**Comment by xx22711** [comment]
期刊1-3分别是Psychology Research and Behavior Management、Personality and Individual Differences、Aggression and Violent Behavior不显示JCR分区，期刊4是Perspectives in Psychiatric Care正常显示，Current Psychology、Scandinavian Journal of Educational Research、Psychology in the Schools、Mindfulness也不能正常显示，Psychology、Health & Medicine、Journal of Affective Disorders、European Psychiatry是正常的。还有很多没有一一列举了。代码要放到啥地方显示？不太懂

**Comment by xx22711** [comment]
期刊1-3分别是Psychology Research and Behavior Management、Personality and Individual Differences、Aggression and Violent Behavior不显示JCR分区，期刊4是Perspectives in Psychiatric Care正常显示，Current Psychology、Scandinavian Journal of Educational Research、Psychology in the Schools、Mindfulness也不能正常显示，Psychology、Health & Medicine、Journal of Affective Disorders、European Psychiatry是正常的。还有很多没有一一列举了。代码要放到啥地方显示？不太懂

**Comment by xx22711** [comment]
是在这里执行么？Personality and Individual Differences，对应的好像这个期刊
![结果](https://github.com/user-attachments/assets/871b8aba-bc4a-4d2b-afbf-21b04a725c2b)

**Comment by xx22711** [comment]
我看代码执行里好像有ssci的JCR分区，但是在前台就是不显示
![前台页面](https://github.com/user-attachments/assets/b7d4b3b6-2777-46c1-9ca8-211b163435c2)

**Comment by xx22711** [comment]
设置里JCR分区是勾上的
![设置](https://github.com/user-attachments/assets/27c2f2d5-6df1-4271-ad9e-49e6593cc8d7)
这是另外一本期刊Perspectives in Psychiatric Care的前台页面和后台执行代码截图，JCR就是正常的
![期刊前台](https://github.com/user-attachments/assets/ce35d683-4afe-41bc-9a75-b7c575de5e65)
![代码执行](https://github.com/user-attachments/assets/4ecd1b35-adcd-4abc-9019-4ee98f059a2b)

**Comment by xx22711** [comment]
我发现了，前台显示的JCR分区是SCI的，如果期刊只是SSCI期刊，就不显示JCR分区了，只有期刊是SCI期刊才显示，应该是前台数据抓取代码问题？

**Comment by redleafnew** [comment]
代码中JCR获取的应该是`sci`的值，需要`ssci`？如果也获取ssci，两个值不一样怎么办？

**Comment by xx22711** [comment]
可以分开SSCI和SCI，而不是统一成JCR，文科大多都是SSCI，理工科是SCI

**Comment by xx22711** [comment]
如果必须统一成JCR，是不是可以考虑用SCI or SSCI，有SCI分区的时候读取SCI分区，没有的时候读取SSCI，这样保证文科类单SSCI的能够显示JCR分区

**Comment by redleafnew** [comment]
我回头再加一个字段：`JCR (SSCI)`

**Comment by redleafnew** [comment]
还有其它期刊是这样的吗？我再测试一下，现在Perspectivesin Psychiatric Care可以了，如果同时有SCI和SSCI的JCR显示SCI的，仅有SSCI的就显示SSCI的JCR

Aggressionand Violent Behavior 是仅有SSCI JCR的是吧。

**Comment by xx22711** [comment]
抱歉，刚才一直登录不上，我看了下，单SSCI检索的都不不显示JCR分区，SCI和SSCI双检索的就会读取SCI的分区，可以看下这个期刊标签里的分区
![截图](https://github.com/user-attachments/assets/9f66774e-7d4e-4f20-8955-816b93437a27)

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/v0.19.12

**Comment by xx22711** [comment]
谢谢
