### ISSUE TITLE
能不能加个功能快速地填充重复的结果

### ISSUE THREAD

**Issue by HiCiChlid** [redleafnew/zotero-updateifsE#178]
有很多查询都是相同的期刊，但每次都要从网上查询出相应的结果，很慢。能不能把已经查过的结果存在本地数据库，然后相同的期刊快速调用本地，进行快速填充，加快速度？

**Comment by redleafnew** [comment]
期刊的数据每年会变，写入本地数据再对比会比较麻烦，当时设计也不是每次大批量更新数据，就是偶尔用一下，看一下期刊的情况。
