### ISSUE TITLE
中文期刊核心显示问题

### ISSUE THREAD

**Issue by Chikit-L** [redleafnew/zotero-updateifsE#18]
目前cscd显示为“核心库”，北大核心显示“中文核心期刊”。
建议显示为cscd显示为“cscd”，北大核心显示“北大核心”，这样更加直观。
同时希望信息能够储存在同一字段里面，多个核心能够自动叠加。例如某一期刊同时为cscd和北大核心，而软件设置为“”☑显示CSCD于索书号字段☑显示北大核心于索书号字段”，此时期刊只会显示“核心库”（即cscd）不会显示“中文核心期刊”（北大核心），而在唯问版当中则会显示为“CSCD，北大核心”

**Comment by redleafnew** [comment]
一般中心核心期刊就是指北大核心，而cscd分为核心库和扩展库，只显示cscd不适当。
多个信息贮存同一字段实现起来比较麻烦，所以暂时先不搞了。
