### ISSUE TITLE
更新条目元数据导致期刊名称错误

### ISSUE THREAD

**Issue by tanyuhe** [redleafnew/zotero-updateifsE#180]
在更新条目元数据时，期刊名称本来是Investigative **Ophthalmology** & Visual Science，更新后变成Investigative **Opthalmology** & Visual Science，少了个h

**Comment by redleafnew** [comment]
https://getquicker.net/Sharedaction?code=78da8f40-e73a-46e8-da6b-08da76a0d1ac 源代码来源，可以向他反馈
