### ISSUE TITLE
所有中文期刊不显示影响因子

### ISSUE THREAD

**Issue by valscox** [redleafnew/zotero-updateifsE#181]
对所有中文期刊更新信息都不显示影响因子，但英文期刊正常显示，如图1&2，目前的设置如图3，不知道是不是我的设置问题，求解，谢谢
![image](https://github.com/user-attachments/assets/2ccbae6b-d2be-4c39-90c6-a560cd79d3d6)
![image](https://github.com/user-attachments/assets/8ea71891-7b19-401a-800e-9dd004047cd0)
![image](https://github.com/user-attachments/assets/a31ecd25-04cf-4b9b-ba93-c1251abc2d40)

**Comment by redleafnew** [comment]
给个期刊名称

**Comment by redleafnew** [comment]
应该是知网更新了

**Comment by valscox** [comment]
中国电机工程学报、电力系统自动化、电网技术 等

**Comment by redleafnew** [comment]
试下最新版本

**Comment by valscox** [comment]
可以了👍十分感谢，更新很及时
