### ISSUE TITLE
从ISSN号匹配是否会更好

### ISSUE THREAD

**Issue by zoelir729** [redleafnew/zotero-updateifsE#2]
对于期刊名称有符号的来说比如Alzheimer's & Dementia
名称匹配不会match到
用ISSN作为变量匹配可能会更好
<img width="646" alt="image" src="https://user-images.githubusercontent.com/36666968/173529175-1ce32ca6-d8c6-43a5-9d61-798d792f841b.png">

**Comment by redleafnew** [comment]
以前在做从[唯问](https://github.com/redleafnew/zotero-updateifs)更新期刊的时候试过用issn匹配，但是唯问的ISSN和Zotero条目中的有可能不一样，也匹配不到。ISSN有在线版的和打印版的。
而[easyScholar]](https://easyscholar.cc/)版本目前只能通过期刊名称搜索，用的[easyScholar]](https://easyscholar.cc/)的数据接口中只能通过期刊名检索。
