### ISSUE TITLE
取消消息提醒或者自定义提醒频率

### ISSUE THREAD

**Issue by LamFTS** [redleafnew/zotero-updateifsE#21]
开发者你好，请问可以关闭这个更新结果的消息窗口吗？不知道为何我在阅读做标注的时候，每次高亮一下，就有弹出这个提示，能不能设置一个开关，关闭这个提示或者自定义提示的方式、时间、频次呢？
![图片](https://user-images.githubusercontent.com/53118840/205419086-5576525f-dbd4-425a-a4d2-06d271187656.png)

**Comment by redleafnew** [comment]
我的没有啊，是用的Zotero内置阅读器？
更新一下插件，
或关闭这个选项
![image](https://user-images.githubusercontent.com/22135631/205419357-2f35ccf8-9809-4b18-80c6-fc60ad22ba69.png)

**Comment by LamFTS** [comment]
已经是最新的0.3.4版了，用的是zotero内置阅读器，我遇到的问题时，在我进行高亮的时候，就会弹出这个提示，而且我正在阅读的这篇文章是有影响因子信息的，也会提示更新失败，换其他文章也会有类似的问题。而且我还是想保留添加时自动更新的功能：）
![Peek 2022-12-03 11-09](https://user-images.githubusercontent.com/53118840/205419683-1da1c73c-1bc2-4fe9-9acf-9a8e65ed043d.gif)

**Comment by redleafnew** [comment]
先关闭一下，看看是不是这的原因，我这没有这个问题。

**Comment by redleafnew** [comment]
应该是这个原因，我有时间看一下。

**Comment by redleafnew** [comment]
3ba029770002d34223bd88d9d9405fd601ec6b52

**Comment by LamFTS** [comment]
问题解决了。谢谢开发者。
