### ISSUE TITLE
请问easyscholar可以增加中科院小类分区嘛

### ISSUE THREAD

**Issue by yuzixieshouhuajiaqi** [redleafnew/zotero-updateifsE#22]

**Comment by redleafnew** [comment]
easyScholar网站上有吗？用的他的接口。
justScience版本有。
影响因子查询、数据目录，配置目录及其它小工具：https://github.com/redleafnew/zotero-updateifs

**Comment by yuzixieshouhuajiaqi** [comment]
easyScholar网站上没有中科院小类分区，justScience版本没法批量查询，都是美中不足╯︿╰

**Comment by redleafnew** [comment]
最好不要批量。easyScholar也是，对网站不公平。本来网站可以希望通过点击广告获取收入的。
