### ISSUE TITLE
请问以下最多能一次更新多少个文献条目信息？

### ISSUE THREAD

**Issue by swenqing** [redleafnew/zotero-updateifsE#23]
在利用本插件进行更新时，更新全部700多个文献条目时，出现停止并似乎不再运行，是一次性最多，只能更新界面内大概30多个文献条目吗？

**Comment by redleafnew** [comment]
一次太多会被封IP，具体多少没有试过。没有必要每个条目显示吧。

不要批量搞，对服务器也不公平。
