### ISSUE TITLE
您好，2022版中科院新分区已经发布了，可以更新吗？感谢

### ISSUE THREAD

**Issue by jorismq** [redleafnew/zotero-updateifsE#24]
您好，2022版中科院新分区已经发布了，可以更新吗？感谢

**Comment by redleafnew** [comment]
数据来源于[easyscholar](https://easyscholar.cc/)，要等[easyscholar](https://easyscholar.cc/)支持了才可以。

**Comment by redleafnew** [comment]
作者说已经是2022的了，你可以找个期刊试试。
