### ISSUE TITLE
有的文献用PMID不能找到分区信息，换成DOI才可以，但是就损失了PMID信息了

### ISSUE THREAD

**Issue by jorismq** [redleafnew/zotero-updateifsE#25]
例如这一篇PMID：22914533
Zotero可以找到这一篇，但是插件提示没有找到期刊信息
换成DOI：10.1136/heartjnl-2012-302483重新加载一次，插件就找到了

**Comment by redleafnew** [comment]
插件是根据期刊的名称进行检索的与PMID还是DOI无关。刚才试了一下，用两种方式导入的文献期刊名称是不同的。
