### ISSUE TITLE
您好！Ctrl + D 这个快捷键被该插件“show data directory”占用了，请问有解除该快捷键的方式吗？

### ISSUE THREAD

**Issue by Jason-Study** [redleafnew/zotero-updateifsE#26]
您好！Ctrl + D 这个快捷键是我在zotero中很常用的一个快捷键，但安装该插件后，此快捷键被该插件“show data directory”占用覆盖了，请问有解除该快捷键的方式吗？

**Comment by redleafnew** [comment]
可以禁用或修改为其他的快捷键。
你用作什么功能了？

**Comment by Jason-Study** [comment]
请问如何禁用“show data directory”的快捷键为Ctrl + D，或修改为其他的快捷键？我试了好像除非禁用此插件，不然此快捷键一直开启。

我用zutilo设置了Ctrl + D为打开附件所在文件夹。并且“show data directory”功能对我来说用处很小，我有快捷打开data directory的方式，给这设个Ctrl + D感觉也占用了个顺手的快捷键键位。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/blob/3ba029770002d34223bd88d9d9405fd601ec6b52/chrome/content/overlay.xul#L18
可以把下载的xpi文件用解压软件解压，找到overlay.xul这个文件，用记事本打开，将第18行这个删除或注释，或将<code>D</code>改为其他字母。再将有文件重复压缩为zip，最后改名为xpi，再安装就可以了。

**Comment by Jason-Study** [comment]
好了好了，解决啦，非常感谢大佬帮助！
