### ISSUE TITLE
部分期刊缩写有误

### ISSUE THREAD

**Issue by skymagician** [redleafnew/zotero-updateifsE#27]
例如 World Economy 缩写不是 “World Economy” 而是 WORLD ECON (JCR) 或者 World Econ. (ISO)
Annals of Mathematics 缩写不是 “Ann. of Math. (2)” 而是 ANN MATH (JCR) 或者 Ann. Math. (ISO)

**Comment by redleafnew** [comment]
期刊缩写功能由@l0o0友情提供
请将期刊全称，缩写不带点，缩写带点详细列出，请@l0o0加到数据库，谢谢。

**Comment by skymagician** [comment]
全称：World Economy 不带点：WORLD ECON 带点：World Econ. 
全称：Annals of Mathematics 不带点：ANN MATH 带点：Ann. Math.

**Comment by redleafnew** [comment]
@l0o0 麻烦给加到数据库中？

**Comment by l0o0** [comment]
已添加成功
[image: 图片.png]


redleafnew ***@***.***> 于2023年2月22日周三 15:47写道：

**Comment by redleafnew** [comment]
谢谢。
@skymagician 试一下是否可以了，如果可以请关闭此issue

**Comment by skymagician** [comment]
> 谢谢。 @skymagician 试一下是否可以了，如果可以请关闭此issue

目前还是不行。

**Comment by redleafnew** [comment]
@l0o0 我的也不行呢

**Comment by l0o0** [comment]
@redleafnew @skymagician 我应该是数据库添加后，后台没有重新启动。我这边测试后，已经正常
![图片](https://user-images.githubusercontent.com/2743744/221414349-e280a0a4-4f14-4469-aefd-40d84a2fcaf2.png)

**Comment by redleafnew** [comment]
@l0o0 
World Economy 没有变化
Annals of Mathematics 返回Ann of Math (2) 和Ann. of Math. (2) 多了个（2）

**Comment by skymagician** [comment]
@l0o0 我这也还没有变化，而且数学年刊的缩写是 Ann. Math. 没有 of 的。

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/221416779-607b09f3-fbd0-4175-9591-7194fbdcfd1c.png)
是这样调用的

**Comment by l0o0** [comment]
我发现问题了，这两个新增的期刊，已经存在了数据库里，我没有去掉。现在应该恢复了

**Comment by redleafnew** [comment]
@l0o0 谢谢。
@skymagician 我这可以了，你呢。

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/221460102-83e12b64-c79a-4ec6-897d-7c046a8cf409.png)
好像带点，不带点不对，大小写也成了大写。

**Comment by skymagician** [comment]
@l0o0  数据已经更新了，只是不管设置了带点还是不带点更新的缩写都是不带点的。
@redleafnew 不带点的标准写法就是大写的（JCR缩写)，大小写我觉得问题不大，或许你后续可以出个期刊缩写全大写和首字母大写切换的功能。

**Comment by l0o0** [comment]
![图片](https://user-images.githubusercontent.com/2743744/221876592-afcf99e6-eb4a-4f96-b633-99b842d2d380.png)
![图片](https://user-images.githubusercontent.com/2743744/221876738-cdeb430b-bbae-485f-a268-492948e5bb8f.png)
我后台返回的两个是和前面更新的一样的。@skymagician

**Comment by skymagician** [comment]
@l0o0 with dot 和 no dot 貌似弄反了。

**Comment by l0o0** [comment]
💔是我数据搞错了。@skymagician 我已经更新好了
![图片](https://user-images.githubusercontent.com/2743744/221883614-c765ebb4-eb14-45fd-81d7-e335230e0e29.png)

**Comment by redleafnew** [comment]
> 💔是我数据搞错了。@skymagician 我已经更新好了 ![图片](https://user-images.githubusercontent.com/2743744/221883614-c765ebb4-eb14-45fd-81d7-e335230e0e29.png)

前面的是不是都是期刊名称首字母大写的？

**Comment by l0o0** [comment]
|ID| FullName| abb_with_dot | abb_no_dot|
|---|--------|-------------|--------------------|
|96158|World Economy|World Econ.|WORLD ECON|
|96159|Annals of Mathematics|Ann. Math.|ANN MATH|


@redleafnew 你看这个格式有没有问题？

**Comment by redleafnew** [comment]
不带点的建议：
World Econ 
Ann Math
我也加了处理函数，改成这样了，所以你这不改也可以。

**Comment by l0o0** [comment]
没事，我可以更新一下
