### ISSUE TITLE
Green Frog每次打开都要加载半天

### ISSUE THREAD

**Issue by zys1346** [redleafnew/zotero-updateifsE#28]
更新完最新的Green Frog，每次打开zotero都要加载半天

**Comment by redleafnew** [comment]
是的，可能是因为要注册显示的列的原因。

**Comment by zys1346** [comment]
> 是的，可能是因为要注册显示的列的原因。

有办法解决吗

**Comment by redleafnew** [comment]
经过咨询，用的插件模板上有个2s的延时。我去掉试试。
https://www.jianguoyun.com/p/DSQbmLsQtOD-BRj-mPcEIAA
你试试有没有效果。

**Comment by zys1346** [comment]
> 经过咨询，用的插件模板上有个2s的延时。我去掉试试。 https://www.jianguoyun.com/p/DSQbmLsQtOD-BRj-mPcEIAA 你试试有没有效果。

可以了，瞬间加载完成，感谢👍
![image](https://user-images.githubusercontent.com/60969400/221532862-4948f22c-4b8e-40ca-84f5-09c8cad5f367.png)
这个加载显示其实也没有必要显示吧，去掉感觉启动会更无感，体验更好

**Comment by redleafnew** [comment]
这个还是保留了。主要是插件加载的显示。不影响使用，如果有强迫症，可以自行修改源代码。
