### ISSUE TITLE
‘其他’字段被占用

### ISSUE THREAD

**Issue by MrGongqi** [redleafnew/zotero-updateifsE#29]
你好，我的其他字段被引用量占用了，也没法自定义调整。我希望您能设置一下让我可以自定义调整期刊类型和影响因子放置的位置。谢谢

**Comment by redleafnew** [comment]
这个没有办法了，显示的列字段从其它中调用内容，显示在列中。
而且其它就是用来放置不在上面字段中的东西。
![image](https://user-images.githubusercontent.com/22135631/221786092-d75572a3-4260-4cef-a724-2f2e2492d341.png)

**Comment by Dr-Yulun** [comment]
其他字段有我的大量笔记，执行之后被清空了，很伤心。希望插件覆盖的时候能提醒一下

**Comment by redleafnew** [comment]
执行什么的时候清空了？

从自动备份中恢复:
https://www.zotero.org/support/zotero_data#restoring_from_the_last_automatic_backup

**Comment by Dr-Yulun** [comment]
> 

在执行“update journa information from easyScholar”时候全部清空的。

已经从自动备份中恢复了，谢谢~

**Comment by redleafnew** [comment]
最新版本已经不再清空Extra了。
