### ISSUE TITLE
希望能够实现”添加条目时添加期刊信息“

### ISSUE THREAD

**Issue by BasaltCompass** [redleafnew/zotero-updateifsE#30]
这个发灰的选择框要是能打上勾，那可真是太酷了！
![image](https://user-images.githubusercontent.com/94948049/222959965-5b966a78-0ecc-49a3-a5c3-249514722b11.png)

**Comment by redleafnew** [comment]
容易误用，被封IP，也不建议大量更新。

**Comment by BasaltCompass** [comment]
原来如此，那还是手动点好了

**Comment by Hayes-Mao** [comment]
> 容易误用，被封IP，也不建议大量更新。

还是希望能够开放这个选项，之前唯问版拉取期刊时一条龙就挺好，可惜没更新了还是旧版分区，换了这个每次都攒够一些后才手动点下（因为每拉取一个就更新下太麻烦了），感觉这样反而更容易大量访问导致被封

**Comment by redleafnew** [comment]
有人会批量导入，数量比较大，暂不开放

**Comment by redleafnew** [comment]
下个版本开放。
