### ISSUE TITLE
可以增加一个将期刊简称改为全字母大写的功能嘛

### ISSUE THREAD

**Issue by yuzixieshouhuajiaqi** [redleafnew/zotero-updateifsE#31]
![image](https://user-images.githubusercontent.com/76084234/223507422-671d3aa5-46e2-41e7-9a23-05a844b6e0b6.png)

我在检索引擎中添加了JCR搜索，方便一键从JCR官网查询详细期刊信息，但是只有期刊简称是所有字母大写时才能搜索，请问可以在engines.json中通过修改代码实现大小写转换吗，或者可以在插件中增加一个将期刊简称改为全字母大写的功能嘛

**Comment by redleafnew** [comment]
这个功能增加不麻烦，但是在csl引用期刊缩写时会产生一定麻烦。

**Comment by yuzixieshouhuajiaqi** [comment]
有道理，那可以在不改变期刊简称的情况下，只修改检索引擎中的代码，实现上面图片中的检索嘛

**Comment by redleafnew** [comment]
检索引擎中的我不知道，我有时间做一下转换大小写吧，写论文的时候不行再转回来。

**Comment by yuzixieshouhuajiaqi** [comment]
好的，谢谢啦～

**Comment by redleafnew** [comment]
你用quicker吗？给您写个动作？改插件太烦了。

**Comment by yuzixieshouhuajiaqi** [comment]
用，写动作麻烦嘛，麻烦的话就算了，感谢~

**Comment by redleafnew** [comment]
写动作很快。给我个条目例子吧。

**Comment by yuzixieshouhuajiaqi** [comment]
S. Micheletti, P. Accorsi, L. Giordano, et al. Cognitive improvement after cochlear implantation in deaf children with associated disabilities. Developmental Medicine and Child Neurology, 2020, 62(12): 1429-1436

**Comment by yuzixieshouhuajiaqi** [comment]
这种可以嘛

**Comment by redleafnew** [comment]
https://getquicker.net/Sharedaction?code=93f42e57-6c8b-42ed-b46d-08db1f77435a 全部大写

https://getquicker.net/Sharedaction?code=e3830a68-73fd-40bd-b46e-08db1f77435a&fromMyShare=True  词首字母大写

**Comment by yuzixieshouhuajiaqi** [comment]
![image](https://user-images.githubusercontent.com/76084234/223703526-d90ca32d-17b5-41b8-9030-d0dd19b54d90.png)

谢谢大佬，不过运行失败了，看不懂怎么回事😭😭

**Comment by yuzixieshouhuajiaqi** [comment]
刚看到需要配置环境，我再试一下

**Comment by yuzixieshouhuajiaqi** [comment]
谢谢大佬，成功啦，您真厉害，什么都懂👍👍👍
