### ISSUE TITLE
[特性请求]增加依据ISSN匹配期刊的检索策略

### ISSUE THREAD

**Issue by jiaojiaodubai** [redleafnew/zotero-updateifsE#33]
## 问题描述
1. 我有一条使用Zotero Connector抓取的题录，其包括“期刊”和“ISSN”这两个字段，但Green Frog无法更新出分区信息。
2. 核对该刊的[主页地址](https://www.mdpi.com/journal/applsci)发现“期刊”字段的期刊名称与官网一致。
3. 在[LetPub](http://www.letpub.com.cn/index.php?page=journalapp&view=search)搜索`Applied Sciences`，经对比ISSN号发现其在分区数据库中记录为`Applied Sciences-Basel`，而非官网上的“Applied Sciences”，手动将题录的“期刊”字段改为`Applied Sciences-Basel`后，Green Frog可正常获取分区信息。

## 特性建议
一些期刊有着相似的名称且刊名本身存在各种拼写形式，在此情况下，ISSN是比刊名更准确无歧义的期刊标识符，建议在Green Frog中增加这样的检索逻辑：如果使用刊名更新分区信息未成功，则自动尝试以“ISSN”字段匹配期刊分区信息。（当然，一些Zotero插件会滥用“ISSN”字段存放其他信息，在用ISSN字段值查找之前有必要校验一下它是否是ISSN号的格式）

**Comment by redleafnew** [comment]
数据来源于[easyScholar](https://easyscholar.cc/)，它提供的接口，只是用来检索期刊题目。如果有问题可以让他把期刊题目增加或修改。
