### ISSUE TITLE
是否可以由用户自定义分区和影响因子的存放字段？

### ISSUE THREAD

**Issue by Sifan798** [redleafnew/zotero-updateifsE#36]
![image](https://user-images.githubusercontent.com/59358565/226282089-718a261e-5d4b-4560-9b0d-72904ff775c1.png)
刚刚升级到小绿蛙，真的速度超快，作者给力！
不过有一个小小的问题，新的版本各个分区和影响因子独立成为一个字段，虽然非常清晰，但是对于在有限的空间想要呈现南大核心/北大核心/科技核心以及英文的分区等内容来说，需要很长的列数。建议作者是否可以与0.36版本一样，将分区和影响因子存放字段由用户自定义设置（如上图）？这样可以在几个字段里呈现比较多的东西。
再次感谢作者！

**Comment by redleafnew** [comment]
新版本不支持了，Zotero官方不建议用其它字段，让其它信息都放在Extra中。
新的可以显示到列上。
![image](https://user-images.githubusercontent.com/22135631/226314005-5938b3ba-75ad-4651-ae8b-8b6659e35c63.png)

**Comment by Sifan798** [comment]
理解！Extra列的信息清晰而且很完备，但是在面板化的页面中无法完全呈现，以分区或影响因子排序有些不便。可不可以**设置一到两个字段，让用户自定义**呀？
比如说设置**分区**字段，用户可以将南大/北大/科技核心或者中科院，QCR分区放进去，设置**影响因子**字段，用户将影响因子、复合因子等放进去。
再次感谢作者辛苦劳动！

**Comment by redleafnew** [comment]
显示到列上可以排序，
不再搞复杂的功能的了。

**Comment by Sifan798** [comment]
好的，仅作为用户使用建议供您参考。
