### ISSUE TITLE
更新0.5.1后，插件无法获得JCR分区

### ISSUE THREAD

**Issue by zhm111** [redleafnew/zotero-updateifsE#37]
你好，绿青蛙更新0.5.1之后，从easyScholar更新期刊信息无法获取JCR分区

**Comment by redleafnew** [comment]
请提供测试的条目，我的是显示的。

**Comment by zhm111** [comment]
Astrocytic MicroRNAs and Transcription Factors in Alzheimer's Disease and Therapeutic Interventions.

**Comment by zhm111** [comment]
我试了几篇不同的，既往使用绿青蛙可以正常获取各个信息的文献，但更新后就无法获取JCR了

**Comment by redleafnew** [comment]
导出Zotero条目，最好以JSON格式，我可以导入的。

**Comment by zhm111** [comment]
链接：https://pan.baidu.com/s/1IbGZ8aCw4W9YVR2fgoY6-A?pwd=k83f 
提取码：k83f 
--来自百度网盘超级会员V5的分享
抱歉，不知道怎么发文件，就用的这个

**Comment by zhm111** [comment]
全部的条目都无法获取JCR，像IF，中科院升级版都是正常的，我也把情况反馈给了easyScholar的客服，他那边说测试一下给我回复

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/226316942-290dd2a4-053a-46fc-a833-b43a306bfb4c.png)
有的啊

**Comment by zhm111** [comment]
![image](https://user-images.githubusercontent.com/128362110/226318048-abdd21f7-c764-4a1d-8c0a-0f944625b0d2.png)
为什么呀，插件冲突？
![image](https://user-images.githubusercontent.com/128362110/226318277-c4068dc0-85be-48ac-81af-d605276d2f0f.png)

**Comment by redleafnew** [comment]
Extra中有吗？

**Comment by zhm111** [comment]
都没有，其它里面同步的没有，那边客服也回我了，数据是没问题的
![cb47b431fb136a415eff8ca675d8653](https://user-images.githubusercontent.com/128362110/226359373-e3551313-8607-482a-8223-3395e94689df.jpg)
我不知道什么情况了，0.5.0的时候还是好的，我已经把整个zotero全删了重装，只安装绿青蛙插件，还是无法获取JCR分区，我手边没有第二台电脑测试

**Comment by redleafnew** [comment]
选中条目，运行一下代码试试，secretKey引号内替换为你的key
```
  var items = ZoteroPane.getSelectedItems();
  var item = items[0]; 
  let secretKey = '修改为你的key';
  publicationTitle = encodeURI(item.getField('publicationTitle'));
  var url = `https://easyscholar.cc/open/getPublicationRank?secretKey=${secretKey}&publicationName=${publicationTitle}`;
    var resp = await Zotero.HTTP.request("GET", url);
  
    try {
        var updateJson = JSON.parse(resp.responseText);
        return updateJson;
    } catch (e) {


    }
```

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/226364223-2d7fdc93-6217-473e-9ca2-b9925ff2491b.png)
看看返回什么？

**Comment by zhm111** [comment]
{
    "code": 200
    "msg": "SUCCESS"
    "data": {
        "customRank": {
            "rankInfo": []
            "rank": []
        }
        "officialRank": {
            "all": {
                "sciif": "11.01"
                "sciUp": "生物学1区"
                "sciif5": "11.072"
                "jci": "1.68"
            }
            "select": {
                "sciif": "11.01"
                "sciUp": "生物学1区"
                "sciif5": "11.072"
                "jci": "1.68"
            }
        }
    }
}没有JCR！。。

**Comment by redleafnew** [comment]
> 都没有，其它里面同步的没有，那边客服也回我了，数据是没问题的 ![cb47b431fb136a415eff8ca675d8653](https://user-images.githubusercontent.com/128362110/226359373-e3551313-8607-482a-8223-3395e94689df.jpg) 我不知道什么情况了，0.5.0的时候还是好的，我已经把整个zotero全删了重装，只安装绿青蛙插件，还是无法获取JCR分区，我手边没有第二台电脑测试

用这个期刊来试。

**Comment by redleafnew** [comment]
要用给easyScholar反馈的期刊名称来试。或是把不显示JCR的期刊反馈给easySchoar.

**Comment by zhm111** [comment]
{
    "code": 200
    "msg": "SUCCESS"
    "data": {
        "customRank": {
            "rankInfo": []
            "rank": []
        }
        "officialRank": {
            "all": {
                "sciif": "7.67"
                "sciUp": "生物学2区"
                "sciif5": "7.677"
                "jci": "0.74"
            }
            "select": {
                "sciif": "7.67"
                "sciUp": "生物学2区"
                "sciif5": "7.677"
                "jci": "0.74"
            }
        }
    }
}

**Comment by zhm111** [comment]
这下是同一个期刊，Cells，刚才没考虑到
![image](https://user-images.githubusercontent.com/128362110/226367851-e8bb48d2-05c9-4a8c-946a-977552d65a62.png)

**Comment by redleafnew** [comment]
奇怪，我的结果是：
```
{
    "code": 200
    "msg": "SUCCESS"
    "data": {
        "customRank": {
            "rankInfo": []
            "rank": []
        }
        "officialRank": {
            "all": {
                "cug": "生物T2"
                "sciif": "7.67"
                "sci": "Q2"
                "sciBase": "生物2区"
                "sciUp": "生物学2区"
                "sciif5": "7.677"
                "jci": "0.74"
            }
            "select": {
                "cug": "生物T2"
                "sciif": "7.67"
                "sci": "Q2"
                "sciBase": "生物2区"
                "sciUp": "生物学2区"
                "sciif5": "7.677"
                "jci": "0.74"
            }
        }
    }
}
```

**Comment by redleafnew** [comment]
`https://easyscholar.cc/open/getPublicationRank?secretKey=Yourkey&publicationName=cells`
直接在浏览器中输入这个呢？Yourkey替换为你的key。

**Comment by zhm111** [comment]
![image](https://user-images.githubusercontent.com/128362110/226371753-f0437637-b70b-4a96-b343-35bdbeb519be.png)
我现在怀疑是不是密钥有问题。。

**Comment by Nixiak-nan** [comment]
不是。easyScholar返回的数据问题，all和select都是一个内容，zhm111没有选中JCR分区，所以all字段里没有JCR（理应是有的）。让那边处理一下就好了

**Comment by redleafnew** [comment]
所以还是数据来源的问题，这个可以问问easyScholar，难道不同key权限不一样？我也是一般用户。

**Comment by zhm111** [comment]
![image](https://user-images.githubusercontent.com/128362110/226372853-64597927-eb6b-415c-bc83-2b29918bd463.png)
笑了，我换了个谷歌邮箱

**Comment by redleafnew** [comment]
唉，没想到是这样。

**Comment by zhm111** [comment]
感谢感谢！您做的插件非常好，麻烦了

**Comment by redleafnew** [comment]
> 不是。easyScholar返回的数据问题，all和select都是一个内容，zhm111没有选中JCR分区，所以all字段里没有JCR（理应是有的）。让那边处理一下就好了

按说没有选中all应该中也有吧。

**Comment by redleafnew** [comment]
> 感谢感谢！您做的插件非常好，麻烦了

我们一起感谢
@Nixiak-nan 提供的接口吧。

**Comment by Nixiak-nan** [comment]
> 

对，设计应该是这样的。但是后端处理错误了，all和select是一致的，今晚就更新后端
