### ISSUE TITLE
请问更新期刊缩写功能怎么实现呢

### ISSUE THREAD

**Issue by PlumPhoebe** [redleafnew/zotero-updateifsE#39]

**Comment by redleafnew** [comment]
右键：更新期刊信息，如果查到期刊缩写会填充到期刊缩写字段。

**Comment by PlumPhoebe** [comment]
> 右键：更新期刊信息，如果查到期刊缩写会填充到期刊缩写字段。

我测试了很多都没有填充期刊缩写

**Comment by redleafnew** [comment]
给个例子？

**Comment by PlumPhoebe** [comment]
我试了Science、Optics Letters、IEEE Antennas and Wireless Propagation Letters、IEEE Transactions on Antennas and Propagation等等很多个期刊我都试了，期刊缩写字段不会填充，只会填充其它字段，我也打开了更新期刊缩写功能，请问是我有哪里设置不对吗

**Comment by redleafnew** [comment]
@l0o0 是不能获取缩写了吗？

**Comment by l0o0** [comment]
> @l0o0 是不能获取缩写了吗？

服务器不知道什么原因重启了，已经正常了

**Comment by redleafnew** [comment]
谢谢。已经可以了。奇怪的是没有获取到也不报错，好像一直重试。
