### ISSUE TITLE
更新带点的期刊缩写数据列表

### ISSUE THREAD

**Issue by dawnlh** [redleafnew/zotero-updateifsE#4]
我又把jabref维护的所有的带点的期刊缩写列表整理了下，一共9w多条，这次应该比较全了
[abbr_formated_full_list.csv](https://github.com/redleafnew/zotero-updateifsE/files/8905405/abbr_formated_full_list.csv)
。

**Comment by redleafnew** [comment]
@l0o0 麻烦再更新一下列表吧。谢谢。

**Comment by l0o0** [comment]
@redleafnew 已更新

**Comment by redleafnew** [comment]
@l0o0 感谢提供数据接口。
