### ISSUE TITLE
分区与影响因子设置中“南农核心”的疑问

### ISSUE THREAD

**Issue by 56125a** [redleafnew/zotero-updateifsE#43]
在首选项-绿青蛙-分区与影响因子设置中左列第5行为“南农核心”，是否指南大核心？
![image](https://user-images.githubusercontent.com/127916962/229400861-24d760be-d7e3-4fe7-bddb-393d9448a72b.png)

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/229402861-4c8d25ea-3b95-4199-b268-2ffb0743a26b.png)
应该是的，笔误。

**Comment by redleafnew** [comment]
已更新。

**Comment by 56125a** [comment]
> 已更新。

十分感谢！
