### ISSUE TITLE
关于选项是灰色的？

### ISSUE THREAD

**Issue by veristagnum** [redleafnew/zotero-updateifsE#44]
插件已经安装到Zotero上。
easyScholar的密钥也设置了。
但是更新的两个选项是灰色的？

**Comment by redleafnew** [comment]
截图一下，是不是文献类型不是期刊？期刊才可以用的。

**Comment by veristagnum** [comment]
好吧，确实是会议。这有点遗憾，我的方向会议文章受关注更大 :(

能不能把会议也加上去呢？

**Comment by veristagnum** [comment]
另外，我看有的权威书籍，或者领域内有名的调研机构也有被引用。

个人感觉把所有的体裁都开放API好像也可以？

**Comment by redleafnew** [comment]
> 好吧，确实是会议。这有点遗憾，我的方向会议文章受关注更大 :(
> 
> 能不能把会议也加上去呢？

会议论文也可以查影响因子之类的？给我个例子我试试

**Comment by redleafnew** [comment]
> 另外，我看有的权威书籍，或者领域内有名的调研机构也有被引用。
> 
> 个人感觉把所有的体裁都开放API好像也可以？

这个插件不获取引用次数的。

**Comment by AiArtisan** [comment]
会议有ccf分类，如果后续可以加上，实用性更上一层楼了

**Comment by redleafnew** [comment]
现在有ccf，给我个具体的例子，我试试，

**Comment by AiArtisan** [comment]
2021'ICCV《Swin Transformer: Hierarchical Vision Transformer using Shifted Windows》

**Comment by redleafnew** [comment]
给我个json格式的条目吧，我可以导入到Zotero中的

**Comment by AiArtisan** [comment]
没找到json文件，这个网页如果可以访问，可以直接下载到zotero里面https://openaccess.thecvf.com/content/ICCV2021/html/Liu_Swin_Transformer_Hierarchical_Vision_Transformer_Using_Shifted_Windows_ICCV_2021_paper.html

**Comment by redleafnew** [comment]
可以从自己的Zotero中导出为csl json格式

**Comment by AiArtisan** [comment]
ok

**Comment by AiArtisan** [comment]
[swin.zip](https://github.com/redleafnew/zotero-updateifsE/files/11145964/swin.zip)

**Comment by redleafnew** [comment]
这个是查询会议名称吗？
easyScholar  https://easyscholar.cc/     会获取到信息吗？
现在数据来源于easyScholar

**Comment by AiArtisan** [comment]
是查询会议名称，从期刊等级查询那可以查到

**Comment by AiArtisan** [comment]
但缩写简称不行，要全称

**Comment by redleafnew** [comment]
用哪个字段检索的，Proceedings of the IEEE/CVF International Conference on Computer Vision 没有结果。需要用到Zotero中的字段来检索。
```
[
	{
		"id": "http://zotero.org/users/4181482/items/C7SLY22Q",
		"type": "paper-conference",
		"event-title": "Proceedings of the IEEE/CVF International Conference on Computer Vision",
		"language": "en",
		"page": "10012-10022",
		"source": "openaccess.thecvf.com",
		"title": "Swin Transformer: Hierarchical Vision Transformer Using Shifted Windows",
		"title-short": "Swin Transformer",
		"URL": "https://openaccess.thecvf.com/content/ICCV2021/html/Liu_Swin_Transformer_Hierarchical_Vision_Transformer_Using_Shifted_Windows_ICCV_2021_paper.html",
		"author": [
			{
				"family": "Liu",
				"given": "Ze"
			},
			{
				"family": "Lin",
				"given": "Yutong"
			},
			{
				"family": "Cao",
				"given": "Yue"
			},
			{
				"family": "Hu",
				"given": "Han"
			},
			{
				"family": "Wei",
				"given": "Yixuan"
			},
			{
				"family": "Zhang",
				"given": "Zheng"
			},
			{
				"family": "Lin",
				"given": "Stephen"
			},
			{
				"family": "Guo",
				"given": "Baining"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2023",
					4,
					4
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2021"
				]
			]
		}
	}
]
```

**Comment by AiArtisan** [comment]
用了“event-title”中的International Conference on Computer Vision
![image](https://user-images.githubusercontent.com/55339205/229780599-c76cba33-772e-4f81-bbeb-6848164a997b.png)

**Comment by redleafnew** [comment]
不是完整的“event-title”字段内容，不好处理啊，取里面的什么内容有什么规律吗？

**Comment by AiArtisan** [comment]
如果带IEEE或者ACM字样的那取IEEE或ACM之后的字符，如果不带就取整个？字符少了可能没事，但如果多了可能就搜不到了。

**Comment by redleafnew** [comment]
规则太复杂了，你把可以查询的写到某个字段中？如Proceedings Title，我直接从这个字段取值？会议论文很很多吗？

**Comment by redleafnew** [comment]
这个cvf也需要删除？

**Comment by AiArtisan** [comment]
cvf看上去也是要删除的，会议论文很多，或许可以只把ccf会议的单独拿出来匹配？

**Comment by redleafnew** [comment]
最好从某一个字段直接取值，或是有规律做什么处理，但复杂的规则我不会写。

**Comment by AiArtisan** [comment]
或许可以查表然后正则匹配

**Comment by redleafnew** [comment]
查什么表？我用这个会议不多，或是你写一个如何得到最终查询的会议名

**Comment by AiArtisan** [comment]
[中国计算机学会推荐国际学术会议和期刊目录-2022.pdf](https://github.com/redleafnew/zotero-updateifsE/files/11148870/-2022.pdf)
查这个里面会议列表中会议全称，有没有匹配的，应该就可以了吧

**Comment by redleafnew** [comment]
这个插件基本没有本地数据，大都是从easyscholar取的数据，

**Comment by AiArtisan** [comment]
那没辙，后续升级倒是可以考虑下

**Comment by redleafnew** [comment]
我只会从某个字段取值或仅做简单的处理，复杂的搞不定。

**Comment by redleafnew** [comment]
如果你能把可以检索的会议名称放入某个字段，再开放这个issue.
