### ISSUE TITLE
只能占用extra条目吗？

### ISSUE THREAD

**Issue by whliao5am** [redleafnew/zotero-updateifsE#45]
请问作者是否可以设置占用哪个条目呢？因为我再使用[Zotero Citation Counts Manager](https://github.com/eschnett/zotero-citationcounts)这个插件，其获取文献的被引用次数，也是占用的extra条目，这样就会互相覆盖，无法同时使用了

**Comment by redleafnew** [comment]
本插件不会覆盖Extra原有内容，只是在原有内容上添加。而且只能放在这个字段，列的内容要从这取值。
其它软件不清楚。

**Comment by whliao5am** [comment]
尝试了一下，本插件确实是进行覆盖写入的。

另外一款插件是在文件头再写入引用数内容，不会覆盖本插件的IF等内容。

redleafnew ***@***.***> 于2023年4月4日周二 21:39写道：

**Comment by redleafnew** [comment]
给我个带Extra内容的条目，我导入试试，最好CSL JSON格式，我试试。

**Comment by redleafnew** [comment]
好像是覆盖，以前是不覆盖的，我问问框架作者。

**Comment by redleafnew** [comment]
会覆盖原来不规范的内容，如果是 key： value这样的字段是不会覆盖的。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.6.7
请更新。

**Comment by whliao5am** [comment]
感谢！
