### ISSUE TITLE
Aging这个期刊无法获取期刊信息

### ISSUE THREAD

**Issue by zhm111** [redleafnew/zotero-updateifsE#46]
链接：https://pan.baidu.com/s/1nNI57bNKFzZKQolYjZzbTg?pwd=l0qi 
提取码：l0qi 
--来自百度网盘超级会员V5的分享
这个是无法获取信息的条目，在Pubmed上是可以通过easy scholar看见期刊信息的，在zotero运行那个javascript，结果是空的，麻烦大佬有时间帮忙看一下。

**Comment by redleafnew** [comment]
我的不显示呢，获取不了信息。
https://easyscholar.cc/ 问一下客服，

**Comment by redleafnew** [comment]
https://sci.justscience.cn/list?sci=1&q=Aging#0    也找不到这个期刊

**Comment by zhm111** [comment]
应该是这个  Aging-US

**Comment by redleafnew** [comment]
但抓取的期刊名不是这个，所以获取不了

**Comment by zhm111** [comment]
好像是的，问过客服了，手动更改zotero里的期刊名就可以获取了，那这种情况有办法解决吗？能不能改成自动获取全名呢

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/229953003-14120292-41ff-4577-aeab-d0aa15d50611.png)
![image](https://user-images.githubusercontent.com/22135631/229953211-5efc3fef-4f06-4087-8445-4fb760e6a626.png)

选中条目后，可以用这个菜单修改期刊题目为正确的。
