### ISSUE TITLE
新版插件使用效果极佳，点赞

### ISSUE THREAD

**Issue by MrGongqi** [redleafnew/zotero-updateifsE#47]
更新插件后感觉使用效果很好，和Zotero Citation Counts Manager的引用量虽然都在extra栏目里，但是期刊信息总是排在引用量后面，这样一来，在主窗口条目里就不影响直接观察到引用量了，所以这个自动排在引用量后面的设计真的很不错。点赞！
![image](https://user-images.githubusercontent.com/49467246/230262087-d86e3286-5dc1-4d8c-bed3-422a0f87e45d.png)

**Comment by redleafnew** [comment]
主要是@windingwind
写的工具箱好用，  https://github.com/windingwind/zotero-plugin-toolkit

**Comment by MrGongqi** [comment]
你们都是牛人，以后有空我也去学学，这样自己编写想要的功能插件。

**Comment by redleafnew** [comment]
大家都是自己用着方便，然后分享。
