### ISSUE TITLE
希望能在工具箱中添加一个功能。

### ISSUE THREAD

**Issue by TLightFire** [redleafnew/zotero-updateifsE#48]
英文期刊中，作者为中国人三个字的姓名一般会分为姓氏和名字，但是两个字的名字部分只有名字的第一个字的拼音首字字母会大写。有的国内英文期刊会要求姓为全显示，名字为首字母，例如Nano Reseach。这就导致引用的时候只显示姓和名字的第一个字的拼音首字母大写，修改引用格式也不能达到这个目的。有的国内英文期刊引用格式会要求名字的三个字都要有，例如Nano Reseach。能不能通过拼音转汉字再转回拼音的形式将名字部分的第二个字的拼音首字母大写，填入作者字段。这样引用的时候就会显示完全。

**Comment by redleafnew** [comment]
这个功能当前难以实现，现在只能在作者字段自己拆分，两个字的名字加空格，拼音转汉字也有很多可能性。

有些拼音不好拆分， 就像shangan可以为上岸，也可以为伤感
