### ISSUE TITLE
Bug 反馈，当语言缺省时

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/zotero-updateifsE#5]
当自动导入的题录不包含语言信息时，会默认将此题录视为中文，生成中文的期刊信息，而实际上此题录为英文，应该生成JCR相关信息

解决办法：由于中文文献几乎都是从知网导入，建议加入一个选项，将未导入语言信息的题录自动设为en-US，这样更新的期刊信息应该正确了

用于导入的示例：https://journals.aom.org/doi/abs/10.5465/amr.2020.0314?af=R

<img width="243" alt="image" src="https://user-images.githubusercontent.com/13982749/173838374-3e8c2ea5-e6c5-4ffe-afd0-c91ffde5ac85.png">
英文期刊的信息，中科院分区 缺少了是否为Top
而唯问数据就是可以导入是否为Top的
http://sci.justscience.cn/details.html?sci=1&id=285

感谢作者！！

**Comment by fredericky123** [comment]
PS:如果能给权利选择哪些信息显示在Extra中就更好了，毕竟文科专业的文献当中，几乎是不可能被EI（Engineer index）检索的，每个题录都带个EI否，显得有些冗余了

**Comment by fredericky123** [comment]
> 1. 语言可以通过插件 [delitemwithatt](https://github.com/redleafnew/delitemwithatt) 来修改，茉莉花在导入时应该也可以设置语言。
> 2. 精力有限，不再搞那么复杂了。

茉莉花设置的是中文题录，中文题录不存在问题
语言通过第三方插件可以修改为英语，只是当导入时候由于英文语言缺省，自动更新的期刊信息都是错的 ε=(´ο｀*))) 只能每次补充完语言为英语后，再删除extra，再手动更新期刊信息，比较繁琐了
期待老师有空时能把这个错误看看怎么修复，感恩！

**Comment by redleafnew** [comment]
> 将未导入语言信息的题录自动设为en-US
这会出问题的，还是亲自设置一下语言靠谱。

导出后还是手动设置一下语言。

**Comment by fredericky123** [comment]
因为我的理解是中文题录都是通过知网导入的，而茉莉花的知网导入功能很完备了，剩下的文献应该都为英文的（确实存在漏洞不合理之处）

**Comment by redleafnew** [comment]
不一定，中文有可能从其他网站导入。

**Comment by fredericky123** [comment]
哦哦
