### ISSUE TITLE
英文期刊信息不显示

### ISSUE THREAD

**Issue by huredext** [redleafnew/zotero-updateifsE#51]
更新后，中文期刊信息显示正常，而英文期刊信息不显示
同样的期刊之前是有的，现在没有了
这是以前的：
<img width="436" alt="截屏2023-04-11 上午11 50 58" src="https://user-images.githubusercontent.com/130427360/231051551-fbd9ae40-1568-46fd-a32e-bcf31e347173.png">

现在的：
<img width="420" alt="image" src="https://user-images.githubusercontent.com/130427360/231051756-24b26030-3020-494b-a13d-73581d117cfe.png">

**Comment by redleafnew** [comment]
哪个期刊？
将条目csl json格式贴上来。

**Comment by huredext** [comment]
所有的英文期刊都不显示了
<img width="635" alt="截屏2023-04-11 下午3 13 30" src="https://user-images.githubusercontent.com/130427360/231084100-4f4b1294-5b0f-4970-b5b2-220250e11b6d.png">

**Comment by redleafnew** [comment]
右击更新时有什么提示？

**Comment by redleafnew** [comment]
不要搞图片，我要导入测试。

**Comment by redleafnew** [comment]
或是在更新时，把debug信息发上来。

**Comment by huredext** [comment]
今天早上更新的，已经成功更新了

非图片格式的csl json：
[导出的条目.txt](https://github.com/redleafnew/zotero-updateifsE/files/11198380/default.txt)

**Comment by redleafnew** [comment]
现在没有问题了？

**Comment by huredext** [comment]
更新后英文期刊还是不显示

**Comment by redleafnew** [comment]
有什么提示吗？

**Comment by redleafnew** [comment]
选中条目，运行下面代码结果是什么？

Tools-Developer-Run Javascript

```
  var items = ZoteroPane.getSelectedItems();
  var item = items[0]; 
  let secretKey = Zotero.Prefs.get('extensions.zotero.greenfrog.secretkey', true);
  publicationTitle =encodeURIComponent(item.getField('publicationTitle'));
  var url = `https://easyscholar.cc/open/getPublicationRank?secretKey=${secretKey}&publicationName=${publicationTitle}`;
  let req = await Zotero.HTTP.request('GET', url, { responseType: 'json' });
  return req.response;
```

**Comment by huredext** [comment]
工具-开发者-运行Javascript运行结果：

{
    "code": 40002
    "msg": "Key错误"
    "data": null
}

**Comment by redleafnew** [comment]
没有将从easyScholar获得的密钥填入到Green Forg的首选项中或key不正确？

这个更新条目时应该会有提示。

**Comment by huredext** [comment]
green frog 这里的密钥是已经填入的
<img width="298" alt="image" src="https://user-images.githubusercontent.com/130427360/231385511-3ecfab24-4a4b-403b-939c-4823ac4df44a.png">
 
但是更新的时候是没有任何提示的

**Comment by redleafnew** [comment]
那个不是的，需要自己申请，填入。

更新的时候右下角应该会提示，请填入密钥的。

**Comment by redleafnew** [comment]
看插件主页的使用说明

**Comment by huredext** [comment]
谢谢，已经解决，十分感谢
