### ISSUE TITLE
如果批量更新元数据，可能导致部分数据错乱

### ISSUE THREAD

**Issue by dreistein543** [redleafnew/zotero-updateifsE#53]
从更新的过程看，该插件应该是如下工作流程 :

通过某（些）字段从网络抓取元数据 ->
利用抓取到的元数据生成一个新条目（临时生成）->
对比原条目与新条目的差异，使用新条目内容覆盖特定field的内容->
删除新条目

但是，正由于 生成一个新条目 、覆盖特定内容、 删去新条目 的操作可能是通过类似“在下方生成”、“覆盖上方条目”、“删去下方条目”完成的，因此，如果大批量更新元数据，不同条目的更新过程耗时有长有短，从而很可能导致这一流程发生错乱，我目前遇到的问题是：

- 可能会将A条目的新数据更新到B条目
- 可能将A条目当作是B条目的临时条目予以删除

**Comment by redleafnew** [comment]
1. 不建议批量，可能会被IP
2. 代码是借用的quicker动作，可以向原作者提一下
3. 后面Zotero可能会推出更新元数据功能， 这个只是临时用的。
