### ISSUE TITLE
 '从easySchool检索期刊信息失败' 

### ISSUE THREAD

**Issue by MrGongqi** [redleafnew/zotero-updateifsE#54]
![image](https://user-images.githubusercontent.com/49467246/232368073-7fa432a7-d89a-418a-a2b0-3bc225ea95cd.png)
![image](https://user-images.githubusercontent.com/49467246/232368520-e41ce08a-7684-4832-bf3c-d4b2686b6a2b.png)

如上图所示，右击显示可以更新期刊信息，但是点击更新后，却屡次跳出 '从easySchool检索期刊信息失败' 的提示，不知道是为啥这样的。

**Comment by redleafnew** [comment]
所有期刊都是这样？

**Comment by MrGongqi** [comment]
并不是，但是碰到不少期刊都这样，我怀疑有可能这些期刊在easyschool里查不出来，但是具体情况我也不清楚

**Comment by redleafnew** [comment]
有可能，可能这些期刊没有被SCI收录，或是期刊名称有问题。
可以问一下easyScholar，

**Comment by redleafnew** [comment]
如果有问题，把条目的csl json格式上传，
如果没有问题了，请关闭此issue
