### ISSUE TITLE
现在似乎不支持更新会议论文的元数据？

### ISSUE THREAD

**Issue by jimmydengpeng** [redleafnew/zotero-updateifsE#56]
右键会议论文条目”更新条目元数据“的选项为灰色，似乎不支持更新会议论文的元数据。如果不支持的话，未来是否考虑支持呢？

**Comment by jimmydengpeng** [comment]
我在easyScholar的官方接口搜索了一些会议名称，有点是有结果的，比如显示会议的基本，对于会议论文，增加更新会议级别的功能应该是很方便的，如果需要代码贡献，是否可以PR？

**Comment by redleafnew** [comment]
现在只是期刊类型才可以用。

把条目发过来，csl joson格式贴过来，我试一下，看看能不能获得数据。

以前也讨论过会议论文，但会议名称什么的和easyScholar中的不一致，获取不到。

https://github.com/redleafnew/zotero-updateifsE/issues/44

**Comment by jimmydengpeng** [comment]
这是一篇会议论文的csl:
```json
[
	{
		"id": "liSafeHierarchicalPlanning2021",
		"type": "paper-conference",
		"abstract": "Autonomous vehicles need to handle various traffic conditions and make safe and efficient decisions and maneuvers. However, on the one hand, a single optimization/sampling-based motion planner cannot efficiently generate safe trajectories in real time, particularly when there are many interactive vehicles near by. On the other hand, end-to-end learning methods cannot assure the safety of the outcomes. To address this challenge, we propose a hierarchical behavior planning framework with a set of low-level safe controllers and a high-level reinforcement learning algorithm (H-CtRL) as a coordinator for the low-level controllers. Safety is guaranteed by the low-level optimization/sampling-based controllers, while the high-level reinforcement learning algorithm makes H-CtRL an adaptive and efficient behavior planner. To train and test our proposed algorithm, we built a simulator that can reproduce traffic scenes using real-world datasets. The proposed HCtRL is proved to be effective in various realistic simulation scenarios, with satisfying performance in terms of both safety and efficiency.",
		"container-title": "2021 IEEE International Conference on Robotics and Automation (ICRA)",
		"DOI": "10.1109/ICRA48506.2021.9561195",
		"event-title": "IEEE International Conference on Robotics and Automation",
		"note": "ISSN: 2577-087X",
		"page": "2660-2666",
		"source": "IEEE Xplore",
		"title": "A Safe Hierarchical Planning Framework for Complex Driving Scenarios based on Reinforcement Learning",
		"author": [
			{
				"family": "Li",
				"given": "Jinning"
			},
			{
				"family": "Sun",
				"given": "Liting"
			},
			{
				"family": "Chen",
				"given": "Jianyu"
			},
			{
				"family": "Tomizuka",
				"given": "Masayoshi"
			},
			{
				"family": "Zhan",
				"given": "Wei"
			}
		],
		"issued": {
			"date-parts": [
				[
					"2021",
					5
				]
			]
		}
	}
]
```

其中`"container-title"`字段是包含该文章的会议论文集，`"event-title"`是会议名称，有的时候通过Zotero浏览器插件自动抓取的元信息可能不全，或者抓取到的会议字段中带有年份，比如有的可能是”2021 IEEE  International Conference on Robotics and Automation (ICRA)“，如果直接用这个string去easyScholar的接口去查，可能查不到，但只要把年份和缩写让用户手动删掉，就可以查到了，比如用上述的`"event-title"`字段的 `"IEEE International Conference on Robotics and Automation"`就可以查到对应的CCF等级：
<img width="892" alt="image" src="https://user-images.githubusercontent.com/18304993/234195109-fb13d3e1-f24f-4516-97a4-12644c1c91ee.png">

也就是说，如果用户发现查不到，可以让用户自己将规范会议名称填入`event-title`（会议名称）字段：
<img width="338" alt="image" src="https://user-images.githubusercontent.com/18304993/234195807-95d89e39-d0ab-455a-a9b2-dc1d518c7865.png">

所以只需用`event-title`里的会议名去查就行了，在使用方法上说明一下即可~

**Comment by redleafnew** [comment]
是不是论文集一般都查不到？
那是不是只直接从会议名称取值就可以了。

**Comment by jimmydengpeng** [comment]
是的，论文集的名称里面可能带有第几届、proceedings、advances等字样，easyscholar上可能差不到最新的会议论文集名称，会议名一般不会变

**Comment by redleafnew** [comment]
多给几个条目吧，我试试。我从会议名称中取值。会议名称保证正确。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.9.1

**Comment by jimmydengpeng** [comment]
试了一下，有的会议比如我上面发的ICRA已经可以了，有的会议手动改过元数据之后还是查不到，因为easySchloar本身数据库的问题，这个可能只有等他们更新了.... anyway，十分感谢这次更新，辛苦了~~ 👍   这个issue应该可以close了

**Comment by redleafnew** [comment]
可以联系easyScholar，请他添加上。

**Comment by YQisme** [comment]
> 可以联系easyScholar，请他添加上。

![image](https://github.com/redleafnew/zotero-updateifsE/assets/80308783/3d8b935a-c99e-450b-b1d0-d060af0ecf37)
问过官方，官方那边是不会做修改了。有没有可能创建一个映射表作为适配？
这个会议查询的功能对我们人工智能专业挺重要的，毕竟大部分都是会议论文而不是期刊论文😥
![image](https://github.com/redleafnew/zotero-updateifsE/assets/80308783/28e3872d-51da-492e-ae93-8e439673144d)

**Comment by redleafnew** [comment]
如果能提供类似这样一个，我可以想办法实现。
 ```
var fullAbb: any = [
        {
            'full': 'Proceedings of the National Academy of Sciences',
            'abb_no_dot': 'Proc Natl Acad Sci',
              "record": 1
        },
        {
            'full': 'Business Strategy and the Environment',
            'abb_no_dot': 'Busi Stra Envir',
       
            "record": 1
        },
        {
            'full': 'Journal of Energy Storage',
            'abb_no_dot': 'J Energy Storage',
         
            "record": 1
        },

        {
            'full': 'test',
            'abb_no_dot': 'tt',
   
            "record": 1
        }
    ]
```

**Comment by YQisme** [comment]
> 如果能提供类似这样一个，我可以想办法实现。
> 
> ```
> var fullAbb: any = [
>        {
>            'full': 'Proceedings of the National Academy of Sciences',
>            'abb_no_dot': 'Proc Natl Acad Sci',
>              "record": 1
>        },
>        {
>            'full': 'Business Strategy and the Environment',
>            'abb_no_dot': 'Busi Stra Envir',
>       
>            "record": 1
>        },
>        {
>            'full': 'Journal of Energy Storage',
>            'abb_no_dot': 'J Energy Storage',
>         
>            "record": 1
>        },
> 
>        {
>            'full': 'test',
>            'abb_no_dot': 'tt',
>   
>            "record": 1
>        }
>    ]
> ```

其实我更建议的是开放用户自定义UI，这样就可以一劳永逸了

![image](https://github.com/redleafnew/zotero-updateifsE/assets/80308783/c170ad97-716e-46d6-9bcf-5ca22d93c91c)

全称对应easyscholar要求的CCF中的全称。
别名可以是缩写，也可以是自定义的名字，多个名字用逗号隔开（当然，如果可以模糊匹配是最好了）

**Comment by redleafnew** [comment]
匹配只是简单的json，没有涉及数据库读写。full对应现在Zotero中的字段值，缩写对应可以在easyScholar检索到的值。
