### ISSUE TITLE
部分生化环材期刊缩写有问题

### ISSUE THREAD

**Issue by gzzaxyz** [redleafnew/zotero-updateifsE#58]
主要是四个问题：
1、美国化学会旗下以ACS 开头的期刊，缩写里面会变成Acs，但是ACS是美国化学会的英文缩写，应该全部大写。比如ACS Nano缩写就变成Acs Nano，ACS Applied Materials & Interfaces变成Acs Appl. Mater. Interfaces；ACS Central Science变成Acs Central Science。包括但不限于ACS Photonics，ACS Sustainable Chemistry & Engineering，ACS Applied Nano Materials；
类似的还有美国物理学会旗下的APL materials缩写会变成Apl Mater.，英国皇家化学会旗下的RSC Advances会变成Rsc Adv.；
2、有些从pubmed获取的论文条目，期刊名里非第一个单词的首字母会变成小写，然后插件就无法识别。必须手动把期刊名里所有实词都改成首字母大写才能正常获取缩写。比如ACS Central Science如果是ACS central science就无法获取缩写；
3、著名的综合期刊美国科学院院刊“Proceedings of the National Academy of Sciences”没有缩写数据；
4、美国化学会旗下的The Journal of Organic Chemistry，The Journal of Physical Chemistry系列期刊（A/B/C/Letters）正式名称是有定冠词The的，但是插件无法识别，去除The才能识别。

**Comment by redleafnew** [comment]
1,除了ACS、APL还有哪些名词需要全部大写的，现在只是手动添加到源代码，指定大写。
2.手动修改为正确的大小写吧，也方便后面引用。

3. 4 麻烦提供正确的缩写，包括全称，不带点的缩写，带点的缩写是什么？然后
@l0o0 麻烦处理一下吧。

**Comment by gzzaxyz** [comment]
> 1,除了ACS、APL还有哪些名词需要全部大写的，现在只是手动添加到源代码，指定大写。 2.手动修改为正确的大小写吧，也方便后面引用。
> 
> 3. 4 麻烦提供正确的缩写，包括全称，不带点的缩写，带点的缩写是什么？然后
>    @l0o0 麻烦处理一下吧。

感谢及时回复。
1、RSC旗下需要大写的期刊是：
RSC Advances; 
RSC Applied Interfaces; 
RSC Applied Polymers; 
RSC Chemical Biology; 
RSC Medical Chemistry; 
RSC Sustainabilily。

AIP旗下需要大写的期刊是
AIP Advances;
AIP Conference Proceedings; 
APL Bioengineering; 
APL Energy; 
APL Machine Learning; 
APL Materials; 
APL Photonics; 
AVS Quantum Science。

ACS旗下名称带“ACS”的期刊就比较多了，官方网站有期刊列表
https://pubs.acs.org/action/showPublications?pubType=journal&pageSize=20&startPage=&alphabetRange=a
链接里的44本期刊除了Accounts of Chemical Research; Accounts of Materials Research; Analytical Chemistry这三本之外剩下的缩写均要大写ACS。

3、全称：Proceedings of the National Academy of Sciences
      缩写：Proc. Natl. Acad. Sci. 
4、全称：The Journal of Organic Chemistry
     缩写：J. Org. Chem.

**Comment by gzzaxyz** [comment]
> 1,除了ACS、APL还有哪些名词需要全部大写的，现在只是手动添加到源代码，指定大写。 2.手动修改为正确的大小写吧，也方便后面引用。
> 
> 3. 4 麻烦提供正确的缩写，包括全称，不带点的缩写，带点的缩写是什么？然后
>    @l0o0 麻烦处理一下吧。

4. 少了四个期刊
全称：The Journal of Physical Chemistry A
缩写：J. Phys. Chem. A

全称：The Journal of Physical Chemistry B
缩写：J. Phys. Chem. B

全称：The Journal of Physical Chemistry C
缩写：J. Phys. Chem. C

全称：The Journal of Physical Chemistry Letters
缩写：J. Phys. Chem. Lett.

**Comment by redleafnew** [comment]
> > 1,除了ACS、APL还有哪些名词需要全部大写的，现在只是手动添加到源代码，指定大写。 2.手动修改为正确的大小写吧，也方便后面引用。
> > 
> > 3. 4 麻烦提供正确的缩写，包括全称，不带点的缩写，带点的缩写是什么？然后
> >    @l0o0 麻烦处理一下吧。
> 
> 感谢及时回复。 1、RSC旗下需要大写的期刊是： RSC Advances; RSC Applied Interfaces; RSC Applied Polymers; RSC Chemical Biology; RSC Medical Chemistry; RSC Sustainabilily。
> 
> AIP旗下需要大写的期刊是 AIP Advances; AIP Conference Proceedings; APL Bioengineering; APL Energy; APL Machine Learning; APL Materials; APL Photonics; AVS Quantum Science。
> 
> ACS旗下名称带“ACS”的期刊就比较多了，官方网站有期刊列表 https://pubs.acs.org/action/showPublications?pubType=journal&pageSize=20&startPage=&alphabetRange=a 链接里的44本期刊除了Accounts of Chemical Research; Accounts of Materials Research; Analytical Chemistry这三本之外剩下的缩写均要大写ACS。
> 
> 3、全称：Proceedings of the National Academy of Sciences 缩写：Proc. Natl. Acad. Sci. 4、全称：The Journal of Organic Chemistry 缩写：J. Org. Chem.

这个只要添加共有的错误的就可以了，下面的已经添加：

   replace('Acs', 'ACS').  //替换ACS
            replace('Aip', 'AIP').  //替换AIP
            replace('Apl', 'APL'). //替换APL
            replace('Avs', 'AVS'). //替换AVS
            replace('Rsc', 'RSC') //替换RSC

**Comment by gzzaxyz** [comment]
> > > 1,除了ACS、APL还有哪些名词需要全部大写的，现在只是手动添加到源代码，指定大写。 2.手动修改为正确的大小写吧，也方便后面引用。
> > > 
> > > 3. 4 麻烦提供正确的缩写，包括全称，不带点的缩写，带点的缩写是什么？然后
> > >    @l0o0 麻烦处理一下吧。
> > 
> > 
> > 感谢及时回复。 1、RSC旗下需要大写的期刊是： RSC Advances; RSC Applied Interfaces; RSC Applied Polymers; RSC Chemical Biology; RSC Medical Chemistry; RSC Sustainabilily。
> > AIP旗下需要大写的期刊是 AIP Advances; AIP Conference Proceedings; APL Bioengineering; APL Energy; APL Machine Learning; APL Materials; APL Photonics; AVS Quantum Science。
> > ACS旗下名称带“ACS”的期刊就比较多了，官方网站有期刊列表 https://pubs.acs.org/action/showPublications?pubType=journal&pageSize=20&startPage=&alphabetRange=a 链接里的44本期刊除了Accounts of Chemical Research; Accounts of Materials Research; Analytical Chemistry这三本之外剩下的缩写均要大写ACS。
> > 3、全称：Proceedings of the National Academy of Sciences 缩写：Proc. Natl. Acad. Sci. 4、全称：The Journal of Organic Chemistry 缩写：J. Org. Chem.
> 
> 这个只要添加共有的错误的就可以了，下面的已经添加：
> 
> replace('Acs', 'ACS'). //替换ACS replace('Aip', 'AIP'). //替换AIP replace('Apl', 'APL'). //替换APL replace('Avs', 'AVS'). //替换AVS replace('Rsc', 'RSC') //替换RSC

非常感谢！剩下就是5个带定冠词the的期刊名的识别问题。

**Comment by redleafnew** [comment]
> > > > 1,除了ACS、APL还有哪些名词需要全部大写的，现在只是手动添加到源代码，指定大写。 2.手动修改为正确的大小写吧，也方便后面引用。
> > > > 
> > > > 3. 4 麻烦提供正确的缩写，包括全称，不带点的缩写，带点的缩写是什么？然后
> > > >    @l0o0 麻烦处理一下吧。
> > > 
> > > 
> > > 感谢及时回复。 1、RSC旗下需要大写的期刊是： RSC Advances; RSC Applied Interfaces; RSC Applied Polymers; RSC Chemical Biology; RSC Medical Chemistry; RSC Sustainabilily。
> > > AIP旗下需要大写的期刊是 AIP Advances; AIP Conference Proceedings; APL Bioengineering; APL Energy; APL Machine Learning; APL Materials; APL Photonics; AVS Quantum Science。
> > > ACS旗下名称带“ACS”的期刊就比较多了，官方网站有期刊列表 https://pubs.acs.org/action/showPublications?pubType=journal&pageSize=20&startPage=&alphabetRange=a 链接里的44本期刊除了Accounts of Chemical Research; Accounts of Materials Research; Analytical Chemistry这三本之外剩下的缩写均要大写ACS。
> > > 3、全称：Proceedings of the National Academy of Sciences 缩写：Proc. Natl. Acad. Sci. 4、全称：The Journal of Organic Chemistry 缩写：J. Org. Chem.
> > 
> > 
> > 这个只要添加共有的错误的就可以了，下面的已经添加：
> > replace('Acs', 'ACS'). //替换ACS replace('Aip', 'AIP'). //替换AIP replace('Apl', 'APL'). //替换APL replace('Avs', 'AVS'). //替换AVS replace('Rsc', 'RSC') //替换RSC
> 
> 非常感谢！剩下就是5个带定冠词the的期刊名的识别问题。

期刊缩写是通过@l0o0提供的接口，需要麻烦@l0o0放到他服务器中才可以获取到。

**Comment by northword** [comment]
可以把数据源里的期刊全称改为全小写的，请求前把publicationTitle字段也小写后再请求，这样就可以避免大小写导致匹配不上。
the同理，我目前在format-metadata里就是这么写的，直接小写，去掉the 再匹配。

**Comment by redleafnew** [comment]
但是这样再转回为Title case也会存在问题，如ACS会转为Acs了。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.9.1

**Comment by gzzaxyz** [comment]
> https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.9.1

非常感谢。问题1、2、4都解决了，问题3，即《美国科学院院刊》缩写还没有加到数据库里。我又测试了一下，缩写数据库里《美国科学院院刊》应该是最全的名称“Proceedings of the National Academy of Sciences of the United States of America”，如果手动把题录信息改为全称，可以获取缩写Proc. Natl. Acad. Sci. U. S. A.，但是因为全称太长，而且考虑到美国在科学界的绝对影响力，大部分时候名称里都会去掉of the United States of America，杂志官网也是采用Proceedings of the National Academy of Sciences这个名称，所以缩写会变成Proc. Natl. Acad. Sci.

**Comment by redleafnew** [comment]
全称Proceedings of the National Academy of Sciences
带点：Proc. Natl. Acad. Sci.
不带点：Proc Natl Acad Sci

这样吗

@l0o0  能加到你的服务器吗？

**Comment by gzzaxyz** [comment]
> 全称Proceedings of the National Academy of Sciences 带点：Proc. Natl. Acad. Sci. 不带点：Proc Natl Acad Sci
> 
> 这样吗
> 
> @l0o0 能加到你的服务器吗？

对的

**Comment by redleafnew** [comment]
我记得缩写是 PANS

**Comment by northword** [comment]
> 我记得缩写是 PANS

PNAS 不是 ISO4 标准缩写，只是这个缩写更知名

> 但是这样再转回为Title case也会存在问题，如ACS会转为Acs了。

我的意思是仅小写全称，缩写仍然保持正确的大小写，这样可以部分解决问题 2

**Comment by gzzaxyz** [comment]
> 我记得缩写是 PANS

PNAS是最简版，一般用在ppt里，节省空间，就像化学领域顶刊《美国化学会志》“Journal of the American Chemical Society”在ppt里缩写为JACS，但是论文的文献列表里不会用这种只有首字母的缩写形式。

**Comment by redleafnew** [comment]
> > 我记得缩写是 PANS
> 
> PNAS 不是 ISO4 标准缩写，只是这个缩写更知名
> 
> > 但是这样再转回为Title case也会存在问题，如ACS会转为Acs了。
> 
> 我的意思是仅小写全称，缩写仍然保持正确的大小写，这样可以部分解决问题 2

哦，明白了。这还要修改@l0o0的服务器数据。

**Comment by redleafnew** [comment]
> > 我记得缩写是 PANS
> 
> PNAS是最简版，一般用在ppt里，节省空间，就像化学领域顶刊《美国化学会志》“Journal of the American Chemical Society”在ppt里缩写为JACS，但是论文的文献列表里不会用这种只有首字母的缩写形式。

已经联系@l0o0，他加到服务器就可以查询更新缩写了

**Comment by redleafnew** [comment]
easyScolar用的也是Proceedings of the National Academy of Sciences of the United States of America吧，
用Proceedings of the National Academy of Sciences这个可能检索不到影响因子

**Comment by redleafnew** [comment]
抓取的是哪个名称？

**Comment by gzzaxyz** [comment]
> easyScolar用的也是Proceedings of the National Academy of Sciences of the United States of America吧， 用Proceedings of the National Academy of Sciences这个可能检索不到影响因子

IF无所谓的，PNAS的IF波动不大，而且这本期刊的地位基本不靠IF，所以IF的数据可有可无。但是不能自动添加期刊名缩写就很不方便了。Zotero里用ctrl+shift+C快捷复制引用信息时，无法像Word的Zotero插件那样调取Medline期刊缩写数据，如果题录里没有缩写信息，粘贴之后只有期刊名全称，这样在ppt里插入引文就要手动改为缩写。

**Comment by redleafnew** [comment]
用Zotero抓取的是什么名称？

**Comment by northword** [comment]
> 用Zotero抓取的是什么名称？

Proceedings of the National Academy of Sciences

![image](https://user-images.githubusercontent.com/44738481/234773964-7f2a08f4-92c8-4039-8511-d1f8a498c885.png)

**Comment by northword** [comment]
且 doi 导入的信息里，期刊缩写是  ` <abbrev_title>Proc. Natl. Acad. Sci. U.S.A.</abbrev_title>` ，是正确的

**Comment by redleafnew** [comment]
@northword @gzzaxyz 那全称为Proceedings of the National Academy of Sciences，缩写写成什么？
是否需要写带USA

**Comment by northword** [comment]
> @northword @gzzaxyz 那全称为Proceedings of the National Academy of Sciences，缩写写成什么？ 是否需要写带USA

我个人倾向于都缩写为 Proc. Natl. Acad. Sci. U.S.A.

**Comment by redleafnew** [comment]
如果不带点，结尾是USA还是 U S A，就是有没有空格

**Comment by gzzaxyz** [comment]
> @northword @gzzaxyz 那全称为Proceedings of the National Academy of Sciences，缩写写成什么？ 是否需要写带USA

如果题录里全称是Proceedings of the National Academy of Sciences of the United States of America，那缩写是Proc. Natl. Acad. Sci. U. S. A.；如果全称是Proceedings of the National Academy of Sciences，缩写是Proc. Natl. Acad. Sci.
我从官网通过zotero connector添加的条目，全称都是Proceedings of the National Academy of Sciences。

**Comment by northword** [comment]
> 如果不带点，结尾是USA还是 U S A，就是有没有空格

应该不加空格

**Comment by gzzaxyz** [comment]
> 如果不带点，结尾是USA还是 U S A，就是有没有空格

带点和不带点的时候USA之间都没有空格。 
（下面这个耶鲁的网站里给了好几种缩写。缩写标准写法里USA是不加空格的。
https://cgsc.biology.yale.edu/Publication.php?ID=4429）

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.9.2

Proceedings of the National Academy of Sciences也可以了

**Comment by gzzaxyz** [comment]
> https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.9.2
> 
> Proceedings of the National Academy of Sciences也可以了

都解决了，非常感谢！
