### ISSUE TITLE
太好用啦！请问可否增加“CLSCI”“AMI”以及“国家社科基金”的选项？

### ISSUE THREAD

**Issue by yzy-lex** [redleafnew/zotero-updateifsE#59]

**Comment by redleafnew** [comment]
easyScholar提供这个数据吗？

请提供条目的csl json格式，粘在这。

**Comment by yzy-lex** [comment]
有的，但是请问怎么提供条目的csl json格式呢？
![CleanShot 2023-04-29 at 11 23 24@2x](https://user-images.githubusercontent.com/50101175/235281274-0c9a59e6-144f-4336-841e-8003f298884f.png)

**Comment by redleafnew** [comment]
Zotero右击条目，导出，

另外，试一下下面代码，看返回什么：Tools-Developper-JS
```
  var items = ZoteroPane.getSelectedItems();
  var item = items[0]; 
  let secretKey = Zotero.Prefs.get('extensions.zotero.greenfrog.secretkey', true);
  //publicationTitle =encodeURIComponent(item.getField('publicationTitle'));
  var publicationTitle = Zotero.ItemTypes.getName(item.itemTypeID) == 'journalArticle' ?
      encodeURIComponent(item.getField('publicationTitle')) :
      encodeURIComponent(item.getField('conferenceName') );
   
  var url = `https://easyscholar.cc/open/getPublicationRank?secretKey=${secretKey}&publicationName=${publicationTitle}`;
  let req = await Zotero.HTTP.request('GET', url, { responseType: 'json' });
  return req.response;
```

**Comment by yzy-lex** [comment]
抱歉。但是：1.zotero里面没有这个数据呀。2.第二个代码我看不懂，不会用(*/ω＼*)

**Comment by redleafnew** [comment]
1.你要查询哪个期刊或参考文献，就导出哪个

2.选中要查询的条目，按步骤运行，我看一下结果是什么

**Comment by yzy-lex** [comment]
> 1.你要查询哪个期刊或参考文献，就导出哪个
> 
> 2.选中要查询的条目，按步骤运行，我看一下结果是什么

但是zotero本身没有增加这些数据集的数据，导出也没有作用吧？

**Comment by redleafnew** [comment]
没有的话，没有办法查啊。

**Comment by yzy-lex** [comment]
是easyScholar有这个数据，zotero没有的呀。

**Comment by redleafnew** [comment]
导出的是的Zotero的参考文献条目，

**Comment by yzy-lex** [comment]
啊，我没有看懂，这个和easyscholar的数据有什么关联吗？

**Comment by yzy-lex** [comment]
而且应该导出什么条目呢？随便导出一篇条目吗，但那和数据集有什么关系呢？
导出这些评价体系包含的期刊吗，但那数据量也太大了吧？

**Comment by redleafnew** [comment]
要查询哪个条目，导出哪个，用来测试的

**Comment by redleafnew** [comment]
这种自定义的数据集没有搞过，测试一下输出结果。

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/235283854-065583de-0b67-46c1-9152-48faf0b5b9af.png)

![image](https://user-images.githubusercontent.com/22135631/235283899-206bcad4-2458-403d-8eb4-f3a7b93dbc45.png)

**Comment by yzy-lex** [comment]
哦哦 好的
[
	{
		"id": "http://zotero.org/users/11021824/items/HP37A5WW",
		"type": "article-journal",
		"abstract": "近年兴起的数字法学，无疑是工商社会迈向数字社会这一重大时代变革的理论反映。数字法学不是现代法学的理论增补，也不是现代法学的新兴分支，而是现代法学适应数字时代变革发展的转型升级。它通过现代法学基础上的迁移、改造、更新和创生，实现了对现代法学的理论重建，展现着信息中枢、数字行为、算法秩序、节点治理等数字生活逻辑，具有理论体系、价值体系、学科体系的数字知识构架，从而为数字时代的法律发展和秩序构建提供理论解说和规范指引。",
		"container-title": "中国法学",
		"DOI": "10.14111/j.cnki.zgfx.20220511.008",
		"ISSN": "1003-1707",
		"issue": "3",
		"language": "zh",
		"note": "👍16[2023-4-6]📗<北大核心, CSSCI, AMI>",
		"page": "119-144",
		"source": "CNKI",
		"title": "数字法学的理论表达",
		"URL": "https://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2022&filename=ZGFX202203007&v=",
		"author": [
			{
				"family": "马长山",
				"given": ""
			}
		],
		"issued": {
			"date-parts": [
				[
					"2022"
				]
			]
		}
	}
]

**Comment by yzy-lex** [comment]
{
    "code": 200
    "msg": "SUCCESS"
    "data": {
        "customRank": {
            "rankInfo": [
                "0": {
                    "uuid": "1642199434173014016"
                    "abbName": "CLSCI"
                    "oneRankText": " "
                }
                "1": {
                    "uuid": "1648920625629810688"
                    "abbName": "AMI"
                    "oneRankText": "顶级"
                    "twoRankText": "权威"
                    "threeRankText": "核心"
                    "fourRankText": "扩展"
                    "fiveRankText": "入库"
                }
                "2": {
                    "uuid": "1648936694851489792"
                    "abbName": "国家社科基金"
                    "oneRankText": "优秀"
                    "twoRankText": "合格"
                }
            ]
            "rank": [
                "0": "1642199434173014016&&&1"
                "1": "1648920625629810688&&&2"
                "2": "1648936694851489792&&&1"
            ]
        }
        "officialRank": {
            "all": {
                "swufe": "A+"
                "cufe": "AA"
                "sdufe": "A1"
                "swjtu": "A"
                "ruc": "A"
                "xmu": "XMU一类"
                "sjtu": "A"
                "fdu": "A"
                "cqu": "A"
                "xju": "一区"
                "cug": "法学T1"
                "cssci": "CSSCI"
                "pku": "1"
                "zhongguokejihexin": "中国科技核心期刊"
                "zju": "国内一级学术期刊"
            }
            "select": {
                "cssci": "CSSCI"
                "pku": "1"
            }
        }
    }
}

**Comment by redleafnew** [comment]
再给几个其它的条目吧，“CLSCI”“AMI”以及“国家社科基金”收录的，我再测试下。

**Comment by yzy-lex** [comment]
[
	{
		"id": "http://zotero.org/users/11021824/items/TKI874A8",
		"type": "article-journal",
		"abstract": "我国司法实践中关于差额补足、流动性支持等增信措施有保证合同说、无名合同说、债务加入说和对赌协议说四种学说构造。从《民法典担保制度解释》第36条的上下文看,该条文的内容有可能导致司法实践中将增信措施解释为保证合同。但增信措施的运用领域复杂多样,应根据其交易结构、交易习惯和行为目的进行意思表示解释。在结构化金融和信托管理计划中使用增信措施,并不存在被担保的主债权,不需要按照保证合同解释。资产管理业务中的增信措施起到合法的保底作用,也不宜解释为保证合同。即使在一般的金融交易领域,增信措施有避免担保被计入企业财务报告、上市公司信息披露、保证合同各项限制性规则等意义,于此应尊重当事人的意思自治,将增信措...",
		"archive_location": "2",
		"container-title": "现代法学",
		"ISSN": "1001-2397",
		"issue": "2",
		"language": "zh",
		"note": "👍4[2023-4-28]📗<北大核心, CSSCI, AMI>",
		"page": "133-151",
		"source": "CNKI",
		"title": "增信措施担保化的反思与重构——基于我国司法裁判的实证研究",
		"URL": "https://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2022&filename=XDFX202202009&v=",
		"volume": "44",
		"author": [
			{
				"literal": "朱晓喆"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2023",
					2,
					3
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2022"
				]
			]
		}
	}
]

**Comment by yzy-lex** [comment]
{
    "code": 200
    "msg": "SUCCESS"
    "data": {
        "customRank": {
            "rankInfo": [
                "0": {
                    "uuid": "1642199434173014016"
                    "abbName": "CLSCI"
                    "oneRankText": " "
                }
                "1": {
                    "uuid": "1648920625629810688"
                    "abbName": "AMI"
                    "oneRankText": "顶级"
                    "twoRankText": "权威"
                    "threeRankText": "核心"
                    "fourRankText": "扩展"
                    "fiveRankText": "入库"
                }
                "2": {
                    "uuid": "1648936694851489792"
                    "abbName": "国家社科基金"
                    "oneRankText": "优秀"
                    "twoRankText": "合格"
                }
            ]
            "rank": [
                "0": "1642199434173014016&&&1"
                "1": "1648920625629810688&&&3"
                "2": "1648936694851489792&&&2"
            ]
        }
        "officialRank": {
            "all": {
                "swufe": "B"
                "cufe": "A"
                "sdufe": "A2"
                "swjtu": "A"
                "ruc": "B"
                "xmu": "XMU一类"
                "sjtu": "B"
                "fdu": "B"
                "cqu": "B"
                "xju": "三区"
                "cug": "法学T3"
                "cssci": "CSSCI"
                "pku": "1"
                "zhongguokejihexin": "中国科技核心期刊"
                "zju": "国内核心期刊"
            }
            "select": {
                "cssci": "CSSCI"
                "pku": "1"
            }
        }
    }
}

**Comment by redleafnew** [comment]
这两个期刊在三个库中都是什么级别？下面显示得对吗？
![image](https://user-images.githubusercontent.com/22135631/235335695-3727f9c8-20e8-4837-8b92-64d564aeea21.png)

**Comment by redleafnew** [comment]
如果非AMI、NSSF显示空格还是显示`否`？是否还需要写入`Extra`

**Comment by yzy-lex** [comment]
是对滴

>

**Comment by yzy-lex** [comment]
> 如果非AMI、NSSF显示空格还是显示`否`？是否还需要写入`Extra`

哇哦 还可以写入extra的嘛，太赞啦，感谢开发者大大❤️

**Comment by yzy-lex** [comment]
> 如果非AMI、NSSF显示空格还是显示`否`？是否还需要写入`Extra`

感觉显示否，可能会比较方便导入extra?

**Comment by redleafnew** [comment]
> > 如果非AMI、NSSF显示空格还是显示`否`？是否还需要写入`Extra`
> 
> 感觉显示否，可能会比较方便导入extra?

现在是如果是非AMI、NSSF就不在Extra显示，列中也是空白，这样更清爽一些。

> 哇哦 还可以写入extra的嘛

写入extra主要是为了同步方便。

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/235350197-7cd6f148-c371-4e5d-baf6-c4f76e29ab81.png)

**Comment by yzy-lex** [comment]
好滴 感谢❤️ 请问这个功能未来在zotero if pro max也会有吗？

**Comment by redleafnew** [comment]
不知道啊，那个插件不是我做的啊

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.10.0

**Comment by yzy-lex** [comment]
哦哦哦 抱歉(*/ω＼*) 我以为你也是那个插件的作者

> 不知道啊，那个插件不是我做的啊

**Comment by yzy-lex** [comment]
> https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.10.0

感谢开发者大大❤️
