### ISSUE TITLE
更新卡住，出现无效更新。

### ISSUE THREAD

**Issue by llity** [redleafnew/zotero-updateifsE#60]
<img width="351" alt="image" src="https://user-images.githubusercontent.com/11771112/235706667-2a8b1352-d8b3-4e9d-9e47-59ec90d7f290.png">
发现已经是最新版，但是还能检测到更新。
更新完很卡，需要重启zotero。

**Comment by redleafnew** [comment]
可能是源代码更新了，但release没有更新的原因。回头我上传一下。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.10.2
再更新试试。

**Comment by llity** [comment]
一样的卡住哦，等下次更新看看

**Comment by llity** [comment]
更新完就跳出这个30%，disable/enable，又跳出来一个。会导致zotero很卡。

**Comment by redleafnew** [comment]
应该还是更新了源代码版本但没有更新release的原因。重启可以解决吗？

**Comment by llity** [comment]
启动软件还是会卡30%，等上一会儿就好了，软件不卡了
![image](https://github.com/redleafnew/zotero-updateifsE/assets/11771112/9e8dbd40-cd4a-47f3-bb7f-f1ba014bb524)

好几个插件会一直检测到更新

**Comment by redleafnew** [comment]
应该还是更新了源代码版本但没有更新release的原因。刚更新了版本。

**Comment by llity** [comment]
好呢
