### ISSUE TITLE
感觉启用插件后，Zotero用起来很卡

### ISSUE THREAD

**Issue by baileichao** [redleafnew/zotero-updateifsE#61]
启用了该插件，Zotero用起来很卡，而且一直显示下图的对话框，半天都不消失。
![image](https://user-images.githubusercontent.com/57392772/236106388-c7a7f13a-c7b4-48c6-99d9-257b4e5b44ee.png)

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.10.2
再更新试试。

**Comment by llity** [comment]
等下一次更新看，刚才的更新还是这样卡

**Comment by redleafnew** [comment]
应该还是更新了源代码版本但没有更新release的原因。重启可以解决吗？

**Comment by llity** [comment]
重启正常了
