### ISSUE TITLE
easyScholar现已推出订阅制，请问其他好兄弟有别的办法可以继续使用吗

### ISSUE THREAD

**Issue by Petrichor728** [redleafnew/zotero-updateifsE#62]
easyScholar现已推出订阅制（6.1开始实施），且普通订阅每天仅可调用5次查询，多次使用需要145买断，请问其他好兄弟有别的办法可以继续使用吗

**Comment by Nixiak-nan** [comment]
5次/日指的是后台的期刊等级查询功能。api是单独的，不和会员服务捆绑。

**Comment by redleafnew** [comment]
如果有能力还是支持一下，我已经买了永久会员了。

**Comment by Petrichor728** [comment]
> 

哦，是这样的，那普通的订阅（非永久）就可以用api吧

**Comment by Petrichor728** [comment]
> 如果有能力还是支持一下，我已经买了永久会员了。

快毕业了，永久太不划算了

**Comment by Petrichor728** [comment]
> 5次/日指的是后台的期刊等级查询功能。API 是单独的，不和会员服务捆绑。

哦，是这样的，那普通的订阅（非永久）就可以用api吧

**Comment by Nixiak-nan** [comment]
> > 5次/日指的是后台的期刊等级查询功能。API 是单独的，不和会员服务捆绑。
> 
> 哦，是这样的，那普通的订阅（非永久）就可以用api吧

嗯嗯，免费的也能用

**Comment by Petrichor728** [comment]
> 



> > > 5次/日指的是后台的期刊等级查询功能。API 是单独的，不和会员服务捆绑。
> > 
> > 
> > 哦，是这样的，那普通的订阅（非永久）就可以用api吧
> 
> 嗯嗯，免费的也能用

好的，谢谢
