### ISSUE TITLE
可不可以在工具箱中加一个删除期刊栏中某些字符后的文字的功能

### ISSUE THREAD

**Issue by a21344** [redleafnew/zotero-updateifsE#64]
比如在导入文献之后有的期刊名后会有冒号和其他字段，还有的会在名称后出现括号，这样就没办法查找他们的分区，因为和数据库里的期刊名称对应不上，如果可以增加这个功能的话，就会很方便地查找分区信息了，谢谢！
![屏幕截图 2023-05-08 195159](https://user-images.githubusercontent.com/67033553/236816831-d7733f4b-77e2-43a6-8bc0-1056b5c9cc1d.png)

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/236959132-ca5c8c93-38b2-497f-95fb-e24c832a18a1.png)

![image](https://user-images.githubusercontent.com/22135631/236959168-27cb9089-4f3f-40d0-a35a-9a44db661975.png)
用期刊查找替换试一下，如果不行，可以提供条目csl json格式。
