### ISSUE TITLE
老师跪求指点，已经安装的绿青蛙0.10.3为啥都显示不了

### ISSUE THREAD

**Issue by chuting1207** [redleafnew/zotero-updateifsE#65]
老师好，我装了绿青蛙插件，也从easyscholar复制了秘钥，可是界面上分区、影响因子都没有，得怎么设置啊
![image](https://github.com/redleafnew/zotero-updateifsE/assets/133352760/31a6a5f0-7137-407a-b4c0-bdb5c204260b)
![image](https://github.com/redleafnew/zotero-updateifsE/assets/133352760/2ecd2458-4765-490d-a5c1-975345865c9d)

**Comment by redleafnew** [comment]
需要右击条目，更新....

**Comment by chuting1207** [comment]
可以出来啦，让老师见笑了，那老师啊，怎么样才能像下面那样有颜色地显示啊，类似我们在网页上看一样，一目了然比较清楚
![image](https://github.com/redleafnew/zotero-updateifsE/assets/133352760/4dcdbbfc-8167-4acc-93c0-637eeabb8260)

**Comment by redleafnew** [comment]
这个应该是Zotero style插件的功能？

**Comment by chuting1207** [comment]
明白了明白了，谢谢老师
