### ISSUE TITLE
能否把这个和另一个插件优点结合一下

### ISSUE THREAD

**Issue by yvancham** [redleafnew/zotero-updateifsE#69]
zotero更新影响因子可以选择放的位置，但是经常更新失败，这一个插件更新没问题，但是只能放在其他里边，看起来不方便，作者能否改进一下，谢谢

**Comment by redleafnew** [comment]
Zotero官方不建议借用其它字段，建议放在Extra，而且放在Extra中也是方便列中显示时取数据。
