### ISSUE TITLE
类似 easyScholar 可自选单位分级的功能需求

### ISSUE THREAD

**Issue by northword** [redleafnew/zotero-updateifsE#7]
easyScholar 是支持自定义显示字段的
![image](https://user-images.githubusercontent.com/44738481/177694508-eb42c385-f8d5-4970-920b-40c694c1a73e.png)

而目前 zotero-updateifsE 对单位分级仅支持南大核心、北大核心，期望可以自选显示哪些单位的分级
![image](https://user-images.githubusercontent.com/44738481/177694762-67d73906-147e-4687-8524-3ba6ee63868a.png)

**Comment by redleafnew** [comment]
不整那么复杂了。如果需要可以自行Fork，联系easyScholar提供接口。
