### ISSUE TITLE
请问可否区别一下cssci以及cssci扩展。

### ISSUE THREAD

**Issue by yzy-lex** [redleafnew/zotero-updateifsE#72]
二者级别差别较大，一般认为cssci＞北大核心=cssci扩展

**Comment by redleafnew** [comment]
easyScholar有提供这个数据吗？

**Comment by yzy-lex** [comment]
![CleanShot 2023-05-29 at 19 23 31@2x](https://github.com/redleafnew/zotero-updateifsE/assets/50101175/8f33564d-12e1-418f-8c77-963a04e96c74)
有的，就是南大核心

**Comment by yzy-lex** [comment]
南大核心本身存在“CSSCI”以及“CSSCI扩展”两个级别

**Comment by redleafnew** [comment]
运行这个代码，看看，你需要哪些数据？
```
  var items = ZoteroPane.getSelectedItems();
  var item = items[0]; 
  let secretKey = Zotero.Prefs.get('extensions.zotero.greenfrog.secretkey', true);
  //publicationTitle =encodeURIComponent(item.getField('publicationTitle'));
  var publicationTitle = Zotero.ItemTypes.getName(item.itemTypeID) == 'journalArticle' ?
      encodeURIComponent(item.getField('publicationTitle')) :
      encodeURIComponent(item.getField('conferenceName') );
   
  var url = `https://easyscholar.cc/open/getPublicationRank?secretKey=${secretKey}&publicationName=${publicationTitle}`;
  let req = await Zotero.HTTP.request('GET', url, { responseType: 'json' });
  return req.response;
```

**Comment by redleafnew** [comment]
` "cssci": "CSSCI"`这个结果会有<code>cssci扩展</code>和`"CSSCI"`两个结果？

**Comment by yzy-lex** [comment]
会有的

**Comment by yzy-lex** [comment]
比如说这一篇[1] 黄锫. 大数据时代个人数据权属的配置规则[J]. 法学杂志, 2021, 42(1): 99-110.
{
    "code": 200
    "msg": "SUCCESS"
    "data": {
        "customRank": {
            "rankInfo": [
                "0": {
                    "uuid": "1642199434173014016"
                    "abbName": "CLSCI"
                    "oneRankText": " "
                }
                "1": {
                    "uuid": "1648920625629810688"
                    "abbName": "AMI"
                    "oneRankText": "顶级"
                    "twoRankText": "权威"
                    "threeRankText": "核心"
                    "fourRankText": "扩展"
                    "fiveRankText": "入库"
                }
                "2": {
                    "uuid": "1652662162603773952"
                    "abbName": "SWUPL"
                    "oneRankText": "A"
                    "twoRankText": "B"
                    "threeRankText": "C"
                    "fourRankText": "D1"
                    "fiveRankText": "D2"
                }
                "3": {
                    "uuid": "1653331955333984256"
                    "abbName": "AMI集刊"
                    "oneRankText": "核心"
                    "twoRankText": "入库"
                }
                "4": {
                    "uuid": "1653331106809507840"
                    "abbName": "CSSCI集刊"
                    "oneRankText": " "
                }
                "5": {
                    "uuid": "1648936694851489792"
                    "abbName": "国家社科基金"
                    "oneRankText": "优秀"
                    "twoRankText": "合格"
                }
            ]
            "rank": [
                "0": "1642199434173014016&&&1"
                "1": "1648920625629810688&&&4"
            ]
        }
        "officialRank": {
            "all": {
                "swufe": "C"
                "sdufe": "B"
                "swjtu": "B"
                "sjtu": "B"
                "fdu": "B"
                "cqu": "C"
                "xju": "五区"
                "cug": "法学T5"
                "cssci": "CSSCI扩展版"
                "pku": "1"
                "zhongguokejihexin": "中国科技核心期刊"
                "zju": "国内核心期刊"
            }
            "select": {
                "cssci": "CSSCI扩展版"
                "pku": "1"
                "zhongguokejihexin": "中国科技核心期刊"
            }
        }
    }
}

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.10.4

**Comment by yzy-lex** [comment]
非常感谢❤️

**Comment by redleafnew** [comment]
如果解决了请关闭
