### ISSUE TITLE
能否给toolbox加一些个快捷键

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/zotero-updateifsE#73]
尤其，将title改为sentence case，能否设置command/ctrl + T?

**Comment by redleafnew** [comment]
还需要哪些快捷键。

**Comment by fredericky123** [comment]
其他暂时没有特别的需要了

**Comment by fredericky123** [comment]
如果默认添加期刊信息时，自动先清除extra里的信息就好了；也就是覆盖extra字段

**Comment by redleafnew** [comment]
> 如果默认添加期刊信息时，自动先清除extra里的信息就好了；也就是覆盖extra字段

这个不麻烦，我回头加个选项。

**Comment by fredericky123** [comment]
感谢韩老师！

**Comment by redleafnew** [comment]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/22135631/e3561c50-c7b1-4c72-ad40-37a029becd01)
![image](https://github.com/redleafnew/zotero-updateifsE/assets/22135631/5c0503cb-f3c3-4a0a-b2eb-d042af0c0e73)
大概界面。

**Comment by fredericky123** [comment]
可以的

**Comment by redleafnew** [comment]
你是哪个学校的？

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.11.0

**Comment by fredericky123** [comment]
谢谢哈！我毕业啦

**Comment by fredericky123** [comment]
我是mac，刚测试用command +t没效果，是不是没有设置mac系统的快捷键哈

**Comment by redleafnew** [comment]
我没有Mac，不知道command对应哪个键。

**Comment by fredericky123** [comment]
> command

我猜测是在原始的快捷键上设置为2个，即ctrl+t和command+t具有相同的效果就好了

**Comment by redleafnew** [comment]
https://www.jianguoyun.com/p/DSQbmLsQtOD-BRj-mPcEIAA

你试试这个

**Comment by fredericky123** [comment]
不行唉，我刚测试了下，由于mac上有ctrl command option三个键
我用ctrl U是有效果的，而ctrl t是不起效果的
而实际使用的时候想将win下的ctrl替换为command,alt替换为option
这个插件保存位置在哪里呢，我想测试了反馈给您~

**Comment by redleafnew** [comment]
随便保存到哪，下载后安装就可以了。

**Comment by fredericky123** [comment]
对哦，打开了/greenfrog/chrome/content 却不知道在哪里修改，没看懂

**Comment by fredericky123** [comment]
我用的坚果云那个，发现了，这里是不是忽略设置错了
<img width="472" alt="image" src="https://github.com/redleafnew/zotero-updateifsE/assets/13982749/f542447c-aba4-418d-9c90-d850e26f7bb3">

**Comment by redleafnew** [comment]
那个原来就是control，你说不行才做了判断，如果是mac取为accel，是mac的command

**Comment by fredericky123** [comment]
哦哦 理解了 您这边能修改accel为command或cmd试试么，我这边mac上不好修改xpi

**Comment by redleafnew** [comment]
cmd的：
[greenfrog.zip](https://github.com/redleafnew/zotero-updateifsE/files/11678699/greenfrog.zip)
command的
[greenfrog.zip](https://github.com/redleafnew/zotero-updateifsE/files/11678720/greenfrog.zip)

都是zip的，需要解压为xpi再安装。

**Comment by redleafnew** [comment]
你那js 窗口运行` Zotero.isMac` 结果是`true`吗？

**Comment by fredericky123** [comment]
不知道这个怎么运行检测唉

**Comment by fredericky123** [comment]
> greenfrog.zip

就是在mac上不知道如何解压为xpi

**Comment by fredericky123** [comment]
> 你那js 窗口运行` Zotero.isMac` 结果是`true`吗？

以上两个都不行，难道真是这里的问题

**Comment by redleafnew** [comment]
> 不知道这个怎么运行检测唉

Tools-Developer-Java Script

**Comment by redleafnew** [comment]
> > greenfrog.zip
> 
> 就是在mac上不知道如何解压为xpi

直接解压就是xpi文件，附件是zip格式的。

**Comment by redleafnew** [comment]
你有没有安装zutilo？方便测试一下快捷键吗？

**Comment by fredericky123** [comment]
安装了 怎么测试哈
<img width="611" alt="image" src="https://github.com/redleafnew/zotero-updateifsE/assets/13982749/51c4aa6b-04d3-48a1-9a44-8fcbdd6d1029">

**Comment by redleafnew** [comment]
方便远程吗？加q1361942015

**Comment by fredericky123** [comment]
这会儿在开会唉 机会合适的话 我联系您

**Comment by redleafnew** [comment]
ok

**Comment by redleafnew** [comment]
在zutilo中设置copy tags的快捷键为command + T 
![image](https://github.com/redleafnew/zotero-updateifsE/assets/22135631/68fd2469-56ac-4808-a967-dea0cadefde7)
然后
Tools-Developer-Run Java Script
Zotero.Prefs.get('extensions.zutilo.shortcut.copyTags',true)
看看结果是什么？

**Comment by fredericky123** [comment]
<img width="880" alt="image" src="https://github.com/redleafnew/zotero-updateifsE/assets/13982749/3994cd88-41d6-4f13-8f3f-7a8188f4c947">

**Comment by redleafnew** [comment]
难道mac快捷键是 meta？

**Comment by redleafnew** [comment]
https://www.jianguoyun.com/p/DSQbmLsQtOD-BRj-mPcEIAA

重复下载安装这个试试，把modifiers改为meta了。

**Comment by fredericky123** [comment]
可以了！！

**Comment by redleafnew** [comment]
我回头发布正式版

**Comment by fredericky123** [comment]
感谢！！
