### ISSUE TITLE
老师你好，我在知乎邀请您了，怕您没看到，又跑来这里找您，可以帮我指点下zoo for Zotero 无法看文献的问题吗

### ISSUE THREAD

**Issue by chuting1207** [redleafnew/zotero-updateifsE#74]
我的安卓手机安装了zoo，也按照教程设置了电脑端Zotero坚果云同步，现在电脑端的文献附件已经都转化为坚果云链接形式了，手机装完zoo后，可以看到My library的所有文献题录，但是点击文献附件，大部分都看不了，显示无法连接到附件，只有偶尔几个caj的能够打开，打开了也是乱码，该怎么处理好啊？
![image](https://github.com/redleafnew/zotero-updateifsE/assets/133352760/0e7d7116-0da5-4e57-a4d1-f5b52b98ad38)
![image](https://github.com/redleafnew/zotero-updateifsE/assets/133352760/bcc31cae-1704-49dc-964c-60988f1ad285)
![image](https://github.com/redleafnew/zotero-updateifsE/assets/133352760/1866eda4-a44b-4012-bae5-d4aa7e103bb0)
![image](https://github.com/redleafnew/zotero-updateifsE/assets/133352760/8843cf3b-a0d7-4a71-a239-b9e5d7ace32e)
![image](https://github.com/redleafnew/zotero-updateifsE/assets/133352760/72b06c6d-464c-48f2-8677-bb41b67eb73e)

**Comment by redleafnew** [comment]
zoo没有用过啊

**Comment by chuting1207** [comment]
好忧桑，还是很谢谢老师
