### ISSUE TITLE
速度超快！可不可以设置前缀加或不加

### ISSUE THREAD

**Issue by Sifan798** [redleafnew/zotero-updateifsE#8]
嘿嘿，**这版加了影响因子，真的好香**！😍不过既然综合影响因子跟复合影响因子可以设置显示字段，**那么是不是可以把前缀去掉**，不然在字段里显得冗长。

**Comment by redleafnew** [comment]
我还特意加上的，不然分不清是什么影响因子。

**Comment by Sifan798** [comment]
好有心！其实原来设置中可以选择将复合和影响放在哪个字段中，应该不会弄混，加上前缀一方面显得冗长，另一方面不方便对影响因子进行排序。或者也可以设置加前缀或不加
![image](https://user-images.githubusercontent.com/59358565/178146238-d9c3e72b-ff92-4006-92ce-8bbebe83bd93.png)

**Comment by Sifan798** [comment]
![image](https://user-images.githubusercontent.com/59358565/178146333-d4c9b91e-c147-4352-ab48-55d43f6ca84e.png)
shi'zh'ge是这个页面

**Comment by redleafnew** [comment]
好的，我没有想到排序这个。
我删除 一下。

**Comment by Sifan798** [comment]
嘿嘿嘿，好嘞！

**Comment by redleafnew** [comment]
已更新。

**Comment by Sifan798** [comment]
<img width="261" alt="image" src="https://user-images.githubusercontent.com/59358565/178146871-1cf446b0-c9e0-49a6-90ef-031f6614e1f2.png">
第一个吃到螃蟹�
![Suggestion (2)](https://user-images.githubusercontent.com/59358565/178146902-ff79e74f-7f19-47df-9eff-a5a45c01fb73.gif)
�
