### ISSUE TITLE
更新期刊缩写

### ISSUE THREAD

**Issue by AnnaSun777** [redleafnew/zotero-updateifsE#80]
麻烦您更新一下期刊缩写，Business Strategy and the Environment期刊简写是Bus Strategy Environ。谢谢您！
如果需要其他资料，我尽可能去提供。

**Comment by redleafnew** [comment]
还有其它哪些期刊缩写不对吗？

**Comment by redleafnew** [comment]
还有这个期刊，麻烦@l0o0  [l0o0](https://github.com/l0o0)更新一下吧，谢谢。
Journal of Energy Storage
J Energy Storage
J. Energy Storage

**Comment by redleafnew** [comment]
> Business Strategy and the Environment

这个期刊带点和不带点的的缩写是什么？

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/blob/bootstrap/src/modules/abb.ts

可以修改这些代码，添加期刊全称，不带点和带点的期刊缩写，然后PR

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.14.0  看看可以了吗？
