### ISSUE TITLE
论文题目中的上下标问题

### ISSUE THREAD

**Issue by kakaccc** [redleafnew/zotero-updateifsE#81]
标题：Form-stable phase change material based on Na2CO3·10H2O-Na2HPO4·12H2O eutectic hydrated salt/expanded graphite oxide composite: The influence of chemical structures of expanded graphite oxide
问题：其中Na2CO3·10H2O-Na2HPO4·12H2O这样的化学式应该有下标，作为参考文献引用的时候会有要求。希望作者大大可以解决，感谢感谢！！

**Comment by northword** [comment]
参考官方文档：https://www.zotero.org/support/kb/rich_text_bibliography
参考已有实现：https://github.com/northword/zotero-format-metadata#shortcut-to-set-subscripts-bold-and-italic-etc

**Comment by redleafnew** [comment]
https://zhuanlan.zhihu.com/p/57638901
也可以手动操作。

**Comment by kakaccc** [comment]
> 参考官方文档：https://www.zotero.org/support/kb/rich_text_bibliography 参考已有实现：https://github.com/northword/zotero-format-metadata#shortcut-to-set-subscripts-bold-and-italic-etc

好的感谢感谢

**Comment by kakaccc** [comment]
> https://zhuanlan.zhihu.com/p/57638901 也可以手动操作。

感谢大佬
