### ISSUE TITLE
点击更新期刊信息或者元数据无法更新

### ISSUE THREAD

**Issue by sylvianeur** [redleafnew/zotero-updateifsE#82]
点击更新期刊信息或者元数据无法更新

**Comment by redleafnew** [comment]
请上传条目的json格式

**Comment by sylvianeur** [comment]
这个在哪里上传呀

**Comment by sylvianeur** [comment]
> 

这个在哪里上传呀

**Comment by sylvianeur** [comment]
如何上传附件？

**Comment by redleafnew** [comment]
粘贴到这或上传附件都可以。

**Comment by sylvianeur** [comment]
无法粘贴，也没看见上传附件的标志，能否指出一下，万分感谢

**Comment by redleafnew** [comment]
用记事本打开导出的json文件，复制内容，粘贴过来就可以

**Comment by sylvianeur** [comment]
[
	{
		"_name": "CNKI新版",
		"_alias": "CNKI",
		"_description": "CNKI新版",
		"_icon": "http://kns8.cnki.net/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "http://kns8.cnki.net/kns/DefaultResult/Index?dbcode=SCDB&kw={z:title}&korder=SU",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "http://kns8.cnki.net/favicon.ico"
	},
	{
		"_name": "南京师范大学图书馆",
		"_alias": "南京师范大学图书馆",
		"_description": "南京师范大学图书馆",
		"_icon": "http://lib.njnu.edu.cn/images/njnulogo.png",
		"_hidden": false,
		"_urlTemplate": "http://opac.njnu.edu.cn/opac/openlink.php?strSearchType=title&match_flag=forward&historyCount=1&strText={z:title}&doctype=ALL&with_ebook=on&displaypg=20&showmode=list&sort=CATA_DATE&orderby=desc&location=ALL&csrf_token=%29lW1vOCx%7B%2F",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#"
		},
		"_iconSourceURI": "http://lib.njnu.edu.cn/images/njnulogo.png"
	},
		{
		"_name": "豆瓣读书",
		"_alias": "豆瓣读书",
		"_description": "豆瓣读书",
		"_icon": "https://book.douban.com/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "https://search.douban.com/book/subject_search?search_text={z:title}&cat=1001",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#"
		},
		"_iconSourceURI": "https://book.douban.com/favicon.ico"
	},		
		{
		"_name": "国学数典",
		"_alias": "国学数典",
		"_description": "国学数典",
		"_icon": "https://bbs.ugxsd.com/static/image/common/logo_gxsd.png",
		"_hidden": false,
		"_urlTemplate": "https://bbs.ugxsd.com/search.php?mod=forum&searchid=2634&orderby=lastpost&ascdesc=desc&searchsubmit=yes&kw={z:title}",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#"
		},
		"_iconSourceURI": "https://bbs.ugxsd.com/static/image/common/logo_gxsd.png"
	},		
		{
		"_name": "读秀图书",
		"_alias": "读秀图书",
		"_description": "读秀图书",
		"_icon": "https://book.duxiu.com/images/small0408.jpg",
		"_hidden": false,
		"_urlTemplate": "https://book.duxiu.com/search?Field=all&channel=search&sw={z:title}&ecode=utf-8&edtype=&searchtype=&view=0",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#"
		},
		"_iconSourceURI": "https://book.duxiu.com/images/small0408.jpg"
	},
	{
		"_name": "Obsidian",
		"_alias": "Obsidian",
		"_description": "在Obsidian中搜索",
		"_icon": "https://obsidian.md/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "obsidian://search?vault=Zotero&query={z:title}",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#"
		},
		"_iconSourceURI": "https://obsidian.md/favicon.ico"
	},	
	{
		"_name": "Open Notes",
		"_alias": "Open Notes",
		"_description": "笔记路径放在Rights字段",
		"_icon": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201017133213.png",
		"_hidden": false,
		"_urlTemplate": "file:///{z:rights}",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201017133213.png"
	},
		{
		"_name": "TOC of Notes",
		"_alias": "TOC of Notes",
		"_description": "打开所有笔记的目录",
		"_icon": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201025110921.png",
		"_hidden": false,
		"_urlTemplate": "file:////Users/a40781/Zotero/Obsidian",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201025110921.png"
	},
		{
		"_name": "N-Connected Papers",
		"_alias": "Connected Papers文献网络",
		"_description": "Connected Papers文献网络",
		"_icon": "https://www.connectedpapers.com/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "https://www.connectedpapers.com/search?q={z:title}+{z:year}",
		"_urlParams": [],
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://www.connectedpapers.com/favicon.ico"
	},
	{
		"_name": "CrossRef",
		"_alias": "CrossRef",
		"_description": "CrossRef Search",
		"_icon": "https://www.crossref.org/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "http://crossref.org/openurl?{z:openURL}&pid=zter:zter321",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "http://crossref.org/favicon.ico"
	},
	{
		"_name": "Google Scholar",
		"_alias": "Google Scholar",
		"_description": "Google Scholar Search",
		"_icon": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016230633.png",
		"_hidden": false,
		"_urlTemplate": "http://scholar.google.com/scholar?as_q=&as_epq={z:title}&as_occt=title&as_sauthors={rft:aufirst?}+{rft:aulast?}&as_ylo={z:year?}&as_yhi={z:year?}&as_sdt=1.&as_sdtp=on&as_sdtf=&as_sdts=22&",
		"_urlParams": [],
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016230633.png"
	},
	{
		"_name": "Google Scholar - Title Only",
		"_alias": "Google Scholar",
		"_description": "Google Scholar Search - Title Only",
		"_icon": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016230633.png",
		"_hidden": false,
		"_urlTemplate": "http://scholar.google.com/scholar?as_q=&as_epq={z:title}&as_occt=title&as_sdt=1.&as_sdtp=on&as_sdtf=&as_sdts=22&",
		"_urlParams": [],
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016230633.png"
	},
		{
		"_name": "Google Patent",
		"_alias": "Google Scholar",
		"_description": "Google Patent - Search",
		"_icon": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201017210030.png",
		"_hidden": false,
		"_urlTemplate": "https://patents.google.com/?q=({z:title})&oq=({z:title})",
		"_urlParams": [],
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201017210030.png"
	},
		{
		"_name": "Semantic Scholar - DOI",
		"_alias": "Semantic Scholar",
		"_description": "Semantic Scholar",
		"_icon": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201017165044.png",
		"_hidden": false,
		"_urlTemplate": "https://api.semanticscholar.org/{z:DOI}",
		"_urlParams": [],
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201017165044.png"
	},
	{
		"_name": "Google",
		"_alias": "Google",
		"_description": "Google Search",
		"_icon": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016230909.png",
		"_hidden": false,
		"_urlTemplate": "https://www.google.com/#q={z:title}+{rft:aufirst?}+{rft:aulast?}",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#"
		},
		"_iconSourceURI": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016230909.png"
	},
	{
		"_name": "Web of Science",
		"_alias": "WOS",
		"_description": "Web of Science Search",
		"_icon": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016231207.png",
		"_hidden": false,
		"_urlTemplate": "http://ws.isiknowledge.com/cps/openurl/service?url_ver=Z39.88-2004&{z:openURL}",
		"_urlParams": [],
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#"
		},
		"_iconSourceURI": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016231207.png"
	},
	{
		"_name": "WOS Citing Articles",
		"_alias": "WOS Citing Articles",
		"_description": "Web of Science Citing Articles Search",
		"_icon": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016231207.png",
		"_hidden": false,
		"_urlTemplate": "http://ws.isiknowledge.com/cps/openurl/service?url_ver=Z39.88-2004&svc_val_fmt=info:ofi/fmt:kev:mtx:sch_svc&svc.citing=yes&{z:openURL}",
		"_urlParams": [],
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#"
		},
		"_iconSourceURI": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016231207.png"
	},
	{
		"_name": "WOS Related Articles",
		"_alias": "WOS Related Articles",
		"_description": "Web of Science Related Articles Search",
		"_icon": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016231207.png",
		"_hidden": false,
		"_urlTemplate": "http://ws.isiknowledge.com/cps/openurl/service?url_ver=Z39.88-2004&svc_val_fmt=info:ofi/fmt:kev:mtx:sch_svc&svc.related=yes&{z:openURL}",
		"_urlParams": [],
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#"
		},
		"_iconSourceURI": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016231207.png"
	},
	{
		"_name": "Sci-Hub DOI",
		"_alias": "Sci-Hub DOI",
		"_description": "SciHub Lookup Lookup",
		"_icon": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016200912.png",
		"_hidden": false,
		"_urlTemplate": "http://sci-hub.shop/{z:DOI}",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#"
		},
		"_iconSourceURI": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016200912.png"
	},
	{
		"_name": "Sci-Hub URL",
		"_alias": "Sci-Hub URL",
		"_description": "SciHub URL Lookup",
		"_icon": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016200912.png",
		"_hidden": false,
		"_urlTemplate": "http://sci-hub.shop/{z:url}",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#"
		},
		"_iconSourceURI": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016200912.png"
	},
			{
		"_name": "Sci-Hub最新网址",
		"_alias": "Sci-Hub最新网址",
		"_description": "Sci-Hub最新网址",
		"_icon": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016200912.png",
		"_hidden": false,
		"_urlTemplate": "https://iseex.github.io/scihub/",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016200912.png"
	},
		{
		"_name": "Connected Papers（手动输入doi）",
		"_alias": "Connected Papers文献网络",
		"_description": "Connected Papers文献网络",
		"_icon": "https://www.connectedpapers.com/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "https://www.connectedpapers.com",
		"_urlParams": [],
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://www.connectedpapers.com/favicon.ico"
	},
		{
		"_name": "Connected Papers（Title Only）",
		"_alias": "Connected Papers文献网络",
		"_description": "Connected Papers文献网络",
		"_icon": "https://www.connectedpapers.com/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "https://www.connectedpapers.com/search?q={z:title}",
		"_urlParams": [],
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://www.connectedpapers.com/favicon.ico"
	},
		{
		"_name": "iJournal期刊影响因子（首选1）",
		"_alias": "iJournal期刊影响因子",
		"_description": "期刊影响因子查询（仅支持搜索ISSN）",
		"_icon": "https://ijournal.topeditsci.com/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "https://ijournal.topeditsci.com/search?keywordType=title&keyword={rft:jtitle}&ifStart2019=&ifEnd2019=&jcr=&sub=&isDomestic=&selfCitingRate=all&compatriotRate=all&totalReviewRatio=all&categoryId=&pageNum=1&order=&orderType=",
		"_urlParams": [],
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://ijournal.topeditsci.com/favicon.ico"
	},
		{
		"_name": "JustScience影响因子（首选2）",
		"_alias": "JustScience期刊影响因子（首选2）",
		"_description": "JustScience期刊影响因子（首选2）",
		"_icon": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201017105103.png",
		"_hidden": false,
		"_urlTemplate": "https://sci.justscience.cn/index.php?q={rft:jtitle}&sci=1",
		"_urlParams": [],
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201017105103.png"
	},
		{
		"_name": "中文期刊搜索",
		"_alias": "中文期刊搜索",
		"_description": "JustScience中文期刊搜索",
		"_icon": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201017105103.png",
		"_hidden": false,
		"_urlTemplate": "https://sci.justscience.cn/index.php?q={rft:jtitle}&sci=0",
		"_urlParams": [],
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201017105103.png"
	},
		{
		"_name": "Letpub期刊搜索",
		"_alias": "Letpub期刊搜索",
		"_description": "Letpub期刊搜索（仅支持搜索ISSN）",
		"_icon": "https://www.letpub.com.cn/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "http://www.letpub.com.cn/index.php?page=journalapp&view=search&searchname={rft:jtitle}",
		"_urlParams": [],
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://www.letpub.com.cn/favicon.ico"
	},
		{
		"_name": "期刊影响因子查询",
		"_alias": "期刊影响因子查询",
		"_description": "期刊影响因子查询（仅支持搜索ISSN）",
		"_icon": "https://www.xueky.com/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "https://www.xueky.com/rank.php?qk={rft:jtitle}",
		"_urlParams": [],
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://www.xueky.com/favicon.ico"
	},
			{
		"_name": "期刊近五年影响因子",
		"_alias": "期刊近五年影响因子",
		"_description": "期刊近五年影响因子",
		"_icon": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016200307.png",
		"_hidden": false,
		"_urlTemplate": "http://www.greensci.net/search?kw={rft:jtitle}",
		"_urlParams": [],
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016200307.png"
	},
		{
		"_name": "Unpaywall",
		"_alias": "Unpaywall",
		"_description": "Unpaywall Lookup",
		"_icon": "https://oadoi.org/static/img/favicon.png",
		"_hidden": false,
		"_urlTemplate": "https://oadoi.org/{z:DOI}",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#"
		},
		"_iconSourceURI": "https://oadoi.org/static/img/favicon.png"
	},
		{
		"_name": "LibGen",
		"_alias": "LibGen",
		"_description": "Look up books on Library Genesis",
		"_icon": "http://gen.lib.rus.ec/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "http://gen.lib.rus.ec/search.php?req={rft:aufirst?}+{rft:aulast?}+{rft:title?}+{z:ISBN?}",
		"_urlParams": [],
		"_method": "GET",
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:book",
			"xmlns": "http://a9.com/-/spec/opensearch/1.1/",
			"z": "http://www.zotero.org/namespaces/openSearch#"
		},
		"_iconSourceURI": "http://gen.lib.rus.ec/favicon.ico"
	},
		{
		"_name": "Wikipedia",
		"_alias": "Wikipedia",
		"_description": "Wikipedia",
		"_icon": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016232045.png",
		"_hidden": false,
		"_urlTemplate": "https://zh.wikipedia.org/wiki/{z:title}",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://figurebed-iseex.oss-cn-hangzhou.aliyuncs.com/img/20201016232045.png"
	},
	{
		"_name": "ProQuest",
		"_alias": "ProQuest",
		"_description": "ProQuest Search",
		"_icon": "https://www.proquest.com/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "http://proquest.umi.com/pqdweb?SQ=TI(+{z:title}+)+YR(+{z:year?}+)&RQT=305&querySyntax=PQ&searchInterface=1&moreOptState=CLOSED&TS=1139706667&JSEnabled=1&DBId=-1",
		"_urlParams": [],
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#"
		},
		"_iconSourceURI": "http://www.proquest.com/favicon.ico"
	},
			{
		"_name": "Zlibrary Book",
		"_alias": "Zlibrary Book",
		"_description": "Zlibrary Book",
		"_icon": "https://z-lib.org/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "https://b-ok.cc/s/{z:title}",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://z-lib.org/favicon.ico"
	},
		{
		"_name": "Zlibrary Articles",
		"_alias": "Zlibrary Articles",
		"_description": "Zlibrary Articles",
		"_icon": "https://z-lib.org/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "https://booksc.xyz/s/{z:title}",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://z-lib.org/favicon.ico"
	},
		{
		"_name": "SooPAT专利搜索",
		"_alias": "SooPAT专利搜索",
		"_description": "SooPAT专利搜索",
		"_icon": "http://www.soopat.com/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "http://www.soopat.com/Home/Result?SearchWord={z:title}&FMZL=Y&SYXX=Y&WGZL=Y&FMSQ=Y",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "http://www.soopat.com/favicon.ico"
	},
	{
		"_name": "百度学术搜索",
		"_alias": "BaiDu",
		"_description": "百度学术搜索",
		"_icon": "http://xueshu.baidu.com/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "https://xueshu.baidu.com/s?wd={z:title}&rsv_bp=0&tn=SE_baiduxueshu_c1gjeupa&rsv_spt=3&ie=utf-8&f=8&rsv_sug2=0&sc_f_para=sc_tasktype%3D%7BfirstSimpleSearch%7D",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "http://xueshu.baidu.com/favicon.ico"
	},
			{
		"_name": "万方搜索",
		"_alias": "万方搜索",
		"_description": "万方搜索",
		"_icon": "http://www.wanfangdata.com.cn/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "http://www.wanfangdata.com.cn/search/searchList.do?searchType=all&showType=&pageSize=&searchWord={z:title}&isTriggerTag=",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "http://www.wanfangdata.com.cn/favicon.ico"
	},
	{
		"_name": "谷粉学术",
		"_alias": "谷粉学术",
		"_description": "谷粉学术",
		"_icon": "https://img.99lb.net/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "https://cc.gufenxueshu.com/scholar?q={z:title}",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://img.99lb.net/favicon.ico"
	},
		{
		"_name": "Glgoo学术",
		"_alias": "Glgoo学术",
		"_description": "Glgoo学术",
		"_icon": "https://xue.glgoo.org/favicon.ico",
		"_hidden": false,
		"_urlTemplate": "https://xue.xiayige.org/scholar?hl=zh-CN&q={z:title}&btnG=&lr=",
		"_urlParams": [],
		"_urlNamespaces": {
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://xue.glgoo.org/favicon.ico"
	}
]

**Comment by redleafnew** [comment]
你是正常的条目吗？有作者，有期刊名称，有题目？
不用都导出，导出不能更新的条目就可以。

**Comment by sylvianeur** [comment]
现在所以条目均不能更新影响因子和JCR分区了

**Comment by redleafnew** [comment]
看样子你条目不正常，条目类型为期刊或会议论文才可以。

**Comment by redleafnew** [comment]
[
	{
		"id": "http://zotero.org/users/4181482/items/E6838YIU",
		"type": "article-journal",
		"container-title": "Food Reviews International",
		"DOI": "10.1105/tpc.15.00404",
		"ISSN": "1532-298X",
		"issue": "2",
		"journalAbbreviation": "Food Rev. Int.",
		"language": "en-US",
		"note": "JCR分区: Q1\n中科院分区升级版: 农林科学2区\n中科院分区基础版: 工程技术2区\n影响因子: 6.04\n5年影响因子: 6.790\nEI: 是\n南农高质量: A",
		"page": "537-556",
		"title": "Pectin biosynthesis is critical for cell wall integrity and immunity in arabidopsis thaliana",
		"volume": "28",
		"author": [
			{
				"family": "Bethke",
				"given": "Gerit"
			},
			{
				"family": "Thao",
				"given": "Amanda"
			},
			{
				"family": "Xiong",
				"given": "Guangyan"
			},
			{
				"family": "Li",
				"given": "Baohua"
			},
			{
				"family": "Soltis",
				"given": "Nicole E."
			},
			{
				"family": "Hatsugai",
				"given": "Noriyuki"
			},
			{
				"family": "Hillmer",
				"given": "Rachel A."
			},
			{
				"family": "Katagiri",
				"given": "Fumiaki"
			},
			{
				"family": "Kliebenstein",
				"given": "Daniel J."
			},
			{
				"family": "Pauly",
				"given": "Markus"
			},
			{
				"family": "Glazebrook",
				"given": "Jane"
			}
		],
		"issued": {
			"date-parts": [
				[
					"2016",
					2
				]
			]
		}
	}
]

**Comment by redleafnew** [comment]
正常条目类型是这样的

**Comment by sylvianeur** [comment]
我的条目类型是期刊文章呀

**Comment by redleafnew** [comment]
粘贴一个期刊条目的。前面的太多了

**Comment by redleafnew** [comment]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/22135631/fb959884-d3e7-4dc3-88ba-1a5f4bd2864d)

**Comment by sylvianeur** [comment]
导出格式没有json格式

**Comment by redleafnew** [comment]
CSL JSON

**Comment by sylvianeur** [comment]
[
	{
		"id": "http://zotero.org/users/10424914/items/MM6MUTZF",
		"type": "article-journal",
		"abstract": "Depression represents the number one cause of disability worldwide and is often fatal. Inflammatory processes have been implicated in the pathophysiology of depression. It is now well established that dysregulation of both the innate and adaptive immune systems occur in depressed patients and hinder favorable prognosis, including antidepressant responses. In this review, we describe how the immune system regulates mood and the potential causes of the dysregulated inflammatory responses in depressed patients. However, the proportion of never-treated major depressive disorder (MDD) patients who exhibit inflammation remains to be clarified, as the heterogeneity in inflammation findings may stem in part from examining MDD patients with varied interventions. Inflammation is likely a critical disease modifier, promoting susceptibility to depression. Controlling inflammation might provide an overall therapeutic benefit, regardless of whether it is secondary to early life trauma, a more acute stress response, microbiome alterations, a genetic diathesis, or a combination of these and other factors.",
		"call-number": "1",
		"container-title": "Neuron",
		"DOI": "10.1016/j.neuron.2020.06.002",
		"ISSN": "08966273",
		"issue": "2",
		"journalAbbreviation": "Neuron",
		"language": "en",
		"note": "PMID: 32553197\nPMCID: PMC7381373",
		"page": "234-256",
		"source": "18.688",
		"title": "The Bidirectional Relationship of Depression and Inflammation: Double Trouble",
		"title-short": "The Bidirectional Relationship of Depression and Inflammation",
		"URL": "https://linkinghub.elsevier.com/retrieve/pii/S0896627320304311",
		"volume": "107",
		"author": [
			{
				"family": "Beurel",
				"given": "Eléonore"
			},
			{
				"family": "Toups",
				"given": "Marisa"
			},
			{
				"family": "Nemeroff",
				"given": "Charles B."
			}
		],
		"issued": {
			"date-parts": [
				[
					"2020",
					7
				]
			]
		}
	}
]

**Comment by redleafnew** [comment]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/22135631/0c8f41e7-7a15-40a4-be1f-592e3654ffc2)
可以更新啊

**Comment by redleafnew** [comment]
你的不能更新有什么提示？

**Comment by sylvianeur** [comment]
没有任何提示就是不能更新，不知道是不是插件哪里设置有误

**Comment by sylvianeur** [comment]
![1686834612136](https://github.com/redleafnew/zotero-updateifsE/assets/136702977/6f0d0aa4-fef2-4fef-ac64-0fd5c29ca0b5)

**Comment by redleafnew** [comment]
条目上右击，更新....

**Comment by sylvianeur** [comment]
还是如此

**Comment by redleafnew** [comment]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/22135631/322ba39f-50bf-4d9c-b4d5-307541d45141)
先打开它，然后右击更新一下条目，看看有没有报错信息

**Comment by sylvianeur** [comment]
没有显示报错，但仍然不行。最新一版本的xpi插件是0.13.0么

**Comment by redleafnew** [comment]
有时间远程一下吧。1361942015 qq。安装todesk。
