### ISSUE TITLE
zotero7 的preference中没有显示Green Frog配置页面

### ISSUE THREAD

**Issue by jlu511** [redleafnew/zotero-updateifsE#87]
如题，大佬能适配下吗

**Comment by redleafnew** [comment]
是Mac吗？Win是正常的啊。

**Comment by nextkdy** [comment]
一样的情况。windows 11
我是第一次从zotero 6 升级到zotero 7，插件还有配置页面。
后来软件全卸载，插件全删除后重装zotero7就没配置界面了，几乎所有的插件的控制界面都是一片白。
可能和那个ftl文件有关。

唯一显示配置界面的是https://github.com/northword/zotero-format-metadata/issues/29

**Comment by redleafnew** [comment]
升级到最新Zotero 7 beta试试。

**Comment by redleafnew** [comment]
现在的版本只是支持到Zotero 6.0
最新的14.0还没有上传。

**Comment by jlu511** [comment]
zotero 7 beta 10 的时候，这个插件还有其它几个支持7的插件都有设置界面，在7 升级到beta 13以后，现在是最新版 zotero beta 14，设置界面就是空白了。

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.14.0

**Comment by jlu511** [comment]
> https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.14.0

ok了，谢谢
