### ISSUE TITLE
greenfrog插件无法更新影响因子

### ISSUE THREAD

**Issue by chuting1207** [redleafnew/zotero-updateifsE#88]
老师您好，我在新电脑装了zotero，也把greenfrog和style插件都装好了，按照之前的配置把easyscholar的密钥也输进去了，登录zotero账号同步旧电脑的文献到新电脑上面，但是影响因子始终没有显示，更新条目元数据，从easyscholar更新期刊信息都点了，也还是显示不出来，得怎么处理好呢
![9d0209739fcdf6fb8fe8fe6bfc8cc98](https://github.com/redleafnew/zotero-updateifsE/assets/133352760/adf93b87-182f-4a53-a6c1-bd43a3505c51)
![b5530fec66b7e773a7fd37740884c30](https://github.com/redleafnew/zotero-updateifsE/assets/133352760/35e98bbb-b197-4513-8003-477380b86e97)
但是也能显示greenfrog更新期刊信息成功
![ca923d6ead68301b9c6180463d95275](https://github.com/redleafnew/zotero-updateifsE/assets/133352760/e83358bf-3d98-4601-8c7a-e756ab4d9b0c)
可是Style的PublicationTags就是不会出来期刊的信息
![ea601d89f68aef22e974a1d939cdc00](https://github.com/redleafnew/zotero-updateifsE/assets/133352760/ec3fe407-c5a2-48da-afef-765d831d4f4b)

**Comment by redleafnew** [comment]
这是两个不同的插件，尽管都用了easyScholar的数据。如果更新后Extra中期刊的数据，说明GreenFrog就没有问题，详细使用见Readme
