### ISSUE TITLE
关于使用Zotcard配置模板时候无法获取影响因子、中科院分区等元数据

### ISSUE THREAD

**Issue by yjan2088** [redleafnew/zotero-updateifsE#89]
在使用Zotcard自己编写模板时候，只能够读取${extra}字段的值，其他如影响因子的字段从代码中找不到，能不能麻烦作者把一些相关的字段公开一下？
![QQ图片20230707095319](https://github.com/redleafnew/zotero-updateifsE/assets/39473202/12b84c1d-31d3-4453-af17-374ec3aee1de)

**Comment by redleafnew** [comment]
什么意思？源代码中有啊

**Comment by yjan2088** [comment]
就他这个插件这边提取的应该是zotero的元数据，然后咱这个插件是将相关内容存储在extra中，然后对其进行split后存储在新的列中嘛

**Comment by redleafnew** [comment]
插件获致的期刊名称或会议名称，从easyScholar获取数据，
影响因子数据都是来源于easyScholar，写入到extra的。

**Comment by yjan2088** [comment]
对，然后在标题那添加了新的影响因子列嘛，  那么如何读取这个新建的列呢？这个列是否写入到了元数据当中呢

**Comment by redleafnew** [comment]
https://github.com/windingwind/zotero-plugin-toolkit/blob/master/docs/zotero-plugin-toolkit.md  工具箱的功能。

**Comment by yjan2088** [comment]
感谢作者解答，我去看看这个工具箱。

**Comment by northword** [comment]
这些信息全部存储在 extra 字段，每行一个键值对，键值以`:`分隔。
插件自定义的列（如影响因子）和字段（如标题翻译等）也是通过读取 extra 获取数据的。
我想你可能需要向 Zotcard 仓库提 feature request，请求支持读取 extra 的某一个值。

**Comment by yjan2088** [comment]
> 

是的，因为我发现extra字段中的数据被分割后单独的加在zotero中作为了一列存在，我想单独提取如影响因子、中科院分区这两列数据。
