### ISSUE TITLE
可否增加学位论文信息抓取

### ISSUE THREAD

**Issue by Sifan798** [redleafnew/zotero-updateifsE#9]
建议博主在插件中增加**硕博论文的引用量**，可以从知网抓取。这样能进一步完善插件，对毕业生更加友好😉

**Comment by redleafnew** [comment]
意义不大吧

**Comment by Sifan798** [comment]
我是社科类研究生，写毕业论文参考知网学位论文也较多。具体要不要上新功能还需博主评估后决定，当然现在也是很好用的

**Comment by redleafnew** [comment]
https://github.com/l0o0/jasminum
可以抓取知网引用数，你试试是不是支持学位论文
