### ISSUE TITLE
【Bug】唯问更新期刊信息

### ISSUE THREAD

**Issue by ljs-fjmu-edu-cn** [redleafnew/zotero-updateifsE#92]
![影响因子Bug0](https://github.com/redleafnew/zotero-updateifsE/assets/140003842/8f757a52-3da6-495d-811d-b11c15364590)
![影响因子Bug](https://github.com/redleafnew/zotero-updateifsE/assets/140003842/3c695230-d4d8-499b-970f-70fca767654c)
![影响因子Bug2](https://github.com/redleafnew/zotero-updateifsE/assets/140003842/c2a21eec-b9fd-438f-8177-b99292fb0bf9)
中文的和官网查询结果比对都有误，插件不再更新了吗？

**Comment by redleafnew** [comment]
唯问那个不更新了。7.0以后就不兼容了。

**Comment by ljs-fjmu-edu-cn** [comment]
> 唯问那个不更新了。7.0以后就不兼容了。

明白。笔记模板按需调用“档案”、“版权”等字段好用，之后只能从“其他”字段提取了。
