### ISSUE TITLE
journal update增加一个选项：自动更新题录为首字母大写

### ISSUE THREAD

**Issue by fredericky123** [redleafnew/zotero-updateifsE#93]
<img width="603" alt="image" src="https://github.com/redleafnew/zotero-updateifsE/assets/13982749/dc563bb0-8e22-43a4-a22e-c0265cce2da9">

经常需要手动将题目改为sentence case，能否在这个多个复选框设置
谢谢啊

**Comment by redleafnew** [comment]
给个网页例子，我有空的时候试试。

**Comment by fredericky123** [comment]
https://journals.sagepub.com/doi/abs/10.1177/01492063231180836
非常感谢！

**Comment by redleafnew** [comment]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/22135631/743dea01-3c5c-4307-a9fd-86d1088ee20a)
选中这个后，每次导入条目都会有
![image](https://github.com/redleafnew/zotero-updateifsE/assets/22135631/7ea712b3-d8c3-4b06-b1a4-cf1100c9dad1)
提示，可以接受吧。

**Comment by fredericky123** [comment]
非常赞！

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.15.0

**Comment by fredericky123** [comment]
感谢！
