### ISSUE TITLE
需求：自定义查询数据分隔符

### ISSUE THREAD

**Issue by xuejiahua** [redleafnew/zotero-updateifsE#96]
本人在obsidian中使用dataview插件，对于数据格式有一定要求：

> key:: value

中间分隔符可以添加自定义功能吗，感谢！

P.S. 想法是对于网站返回数据分割为 key、value 两部分，再根据自定义格式对 {key}{value} 进行填充替换，这样也可以更方便的添加点号、数字列表等，例如

> “- {key}:: {value}”

可以在markdown中创建列表。

**Comment by redleafnew** [comment]
Extra中就是key：value配对的，间隔符由[工具箱模板](https://github.com/windingwind/zotero-plugin-toolkit)规定的。
