### ISSUE TITLE
从easyScholar更新期刊信息失败

### ISSUE THREAD

**Issue by Javen-7** [redleafnew/zotero-updateifsE#97]
为什么点击更新按钮后 一直报错 Error：从easyScholar更新期刊信息失败
密匙已经配置好了

**Comment by redleafnew** [comment]
是所有都不行还是有的期刊不行？

**Comment by redleafnew** [comment]
把条目JSOS格式上传上来试一下。

**Comment by CarhoJohn** [comment]
我也遇到了同样的问题，选择更新metadata后，能够自动更新信息，但最后仍然会弹出“Retriving journal information fromeasyScholar failed.”，所有期刊都如此

**Comment by CarhoJohn** [comment]
我还遇到了另一个问题，可能是和期刊名称有关的。PNAS期刊获取IF过程会失败（应该是检索不到这个期刊），我的publication一栏的期刊名是“Proceedings of the National Academy of Sciences”，```Update Item Metadata```后也是这个期刊名，此时再运行```Update Journal Information from easyScholar```，会显示更新成功，但数据并没有添加。
我怀疑是easyScholar那边的期刊信息造成的原因，如下图所示，如果使用第一行的“Proceedings Of The National Academy Of Sciences Of The United States Of America”是能够获取IF的，但这很明显是一个BUG，因为使用从easyScholar更新的数据却导致无法返回影响因子；另一方面，使用完整全称实在太长了，文献里的清单大多数要么用缩写，要么只写到“Proceedings of the National Academy of Sciences”，不知道大佬对此有无解决办法？

![image](https://github.com/redleafnew/zotero-updateifsE/assets/45853320/5013b3ad-d4c4-45dc-bb0b-cc745e384b4e)

**Comment by redleafnew** [comment]
可以和easyScholar那边反馈一下。
把条目信息JSON格式也上传，我试一下。

**Comment by redleafnew** [comment]
请提供条目供测试。

**Comment by CarhoJohn** [comment]
> 请提供条目供测试。

抱歉回复晚了，PNAS获取IF的问题刚刚我试了一下，又成功了，不知道原理是什么。但有些期刊获取分区失败，只能取得IF，我猜会不会是因为有多个分区？以下是获取分区失败的条目json

```json

{
"id": "http://zotero.org/users/11571815/items/RWXWNFD2",
"type": "article-journal",
"container-title": "Behavior Research Methods",
"DOI": "10.3758/s13428-018-1107-7",
"ISSN": "1554-3528",
"issue": "3",
"journalAbbreviation": "Behav Res Methods",
"language": "English",
"note": "影响因子: 5.4",
"page": "1399-1425",
"title": "A comparison of homonym meaning frequency estimates derived from movie and television subtitles, free association, and explicit ratings",
"URL": "http://link.springer.com/10.3758/s13428-018-1107-7",
"volume": "51",
"author": [
	{
		"family": "Rice",
		"given": "Caitlin A."
	},
	{
		"family": "Beekhuizen",
		"given": "Barend"
	},
	{
		"family": "Dubrovsky",
		"given": "Vladimir"
	},
	{
		"family": "Stevenson",
		"given": "Suzanne"
	},
	{
		"family": "Armstrong",
		"given": "Blair C."
	}
],
"accessed": {
	"date-parts": [
		[
			"2022",
			3,
			10
		]
	]
},
"issued": {
	"date-parts": [
		[
			"2019",
			6
		]
	]
}
}
```

**Comment by CarhoJohn** [comment]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/45853320/4606b280-1917-4d6c-9b3f-d66a9dbc04ea)
![image](https://github.com/redleafnew/zotero-updateifsE/assets/45853320/5256d43b-fe57-4548-b61a-5f55f0ca18b3)

**Comment by redleafnew** [comment]
> ```json
> {
> "id": "http://zotero.org/users/11571815/items/RWXWNFD2",
> "type": "article-journal",
> "container-title": "Behavior Research Methods",
> "DOI": "10.3758/s13428-018-1107-7",
> "ISSN": "1554-3528",
> "issue": "3",
> "journalAbbreviation": "Behav Res Methods",
> "language": "English",
> "note": "影响因子: 5.4",
> "page": "1399-1425",
> "title": "A comparison of homonym meaning frequency estimates derived from movie and television subtitles, free association, and explicit ratings",
> "URL": "http://link.springer.com/10.3758/s13428-018-1107-7",
> "volume": "51",
> "author": [
> 	{
> 		"family": "Rice",
> 		"given": "Caitlin A."
> 	},
> 	{
> 		"family": "Beekhuizen",
> 		"given": "Barend"
> 	},
> 	{
> 		"family": "Dubrovsky",
> 		"given": "Vladimir"
> 	},
> 	{
> 		"family": "Stevenson",
> 		"given": "Suzanne"
> 	},
> 	{
> 		"family": "Armstrong",
> 		"given": "Blair C."
> 	}
> ],
> "accessed": {
> 	"date-parts": [
> 		[
> 			"2022",
> 			3,
> 			10
> 		]
> 	]
> },
> "issued": {
> 	"date-parts": [
> 		[
> 			"2019",
> 			6
> 		]
> 	]
> }
> }
> ```

PANS我联系一下easyScholar，他们应该处理了一下。

**Comment by redleafnew** [comment]
这个返回结果应该是什么？

我的是这样的：
> 中科院分区升级版: 心理学2区
> 影响因子: 5.4
> 5年影响因子: 7.7
> 南农高质量: A

**Comment by CarhoJohn** [comment]
> Owner

由于我们方向主要看JCR分区，所以我的设置里只勾选了JCR分区和IF，这篇文章的返回结果只有`影响因子: 5.4`，没有获取到JCR分区，所以之前传的图片里分区空了。有一部分期刊会出现这样的问题。

我猜想，是不是也和easyScholar上的数据，或JCR分区的爬取栏目有关？如下图，Behavior Research Methods这个期刊，它有且仅有一个JCR Q1分区，但属于SSCI，会不会是小青蛙插件默认爬取了SCI而不是SSCI？（纯属猜测）


![image](https://github.com/redleafnew/zotero-updateifsE/assets/45853320/96566f5a-331c-4849-ae6a-16bb5bf5f4b3)

**Comment by redleafnew** [comment]
如果easyScholar上也没有，插件也会没有。可以给他们提供数据。

**Comment by redleafnew** [comment]
SSCI可以获取到，但green frog默认没有选中，需要在插件中设置一下。
![image](https://github.com/redleafnew/zotero-updateifsE/assets/22135631/041956a2-bffa-4a1e-89a3-c758e35c5a67)

**Comment by CarhoJohn** [comment]
> Owner

那我猜我遇到的问题，可能就是因为SCI和SSCI的区分了。Anyway，能够获得IF就好，感谢大佬开发的工具！
