### ISSUE TITLE
zotero7 右键标题栏没有显示影响因子的列

### ISSUE THREAD

**Issue by medicialcoder** [redleafnew/zotero-updateifsE#98]
<img width="1280" alt="image" src="https://github.com/redleafnew/zotero-updateifsE/assets/131216222/f646a2ea-0681-47ae-aedd-52ad14dbbb66">
这是什么原因啊大佬

**Comment by redleafnew** [comment]
重启或在偏好设置中设置后等一会儿再右击试试

**Comment by medicialcoder** [comment]
> 重启或在偏好设置中设置后等一会儿再右击试试

重启没有用  偏好设置是啥意思啊大佬

**Comment by redleafnew** [comment]
是Mac还是Win

**Comment by liut14** [comment]
我也遇到了这个问题，也没有影响因子的列
系统 win10

**Comment by liut14** [comment]
![image](https://github.com/redleafnew/zotero-updateifsE/assets/52646263/a028bcba-1af9-40e7-9c20-c1a12e5d64ea)

**Comment by redleafnew** [comment]
重新安装可以解决吗？

**Comment by redleafnew** [comment]
Zotero是哪个版本？

**Comment by liut14** [comment]
版本今天刚更新
![image](https://github.com/redleafnew/zotero-updateifsE/assets/52646263/085eb5eb-7b55-438f-a31f-f5bbed0b2901)
我用的是这个zotero，我换成 installer 安装版本试试
![image](https://github.com/redleafnew/zotero-updateifsE/assets/52646263/7d15d3e7-c06e-444b-b066-9d5003d23fc2)

**Comment by redleafnew** [comment]
那就奇怪了，我的Zotero也是最新的beta，用的zip的

**Comment by liut14** [comment]
我刚才把所有其他插件都屏蔽了，只保留了 绿青蛙，发现有了。可能和某个软件不兼容？
![image](https://github.com/redleafnew/zotero-updateifsE/assets/52646263/f0e054aa-ee8c-4ecc-93c0-c3b1fe95e4e9)

您都用的哪些插件啊？
我装了下面这些
![image](https://github.com/redleafnew/zotero-updateifsE/assets/52646263/363061f9-cc8c-4ec0-88d7-7327718cf2b7)
![image](https://github.com/redleafnew/zotero-updateifsE/assets/52646263/b0f518af-ef2f-46e2-b536-d415d81277c8)

**Comment by liut14** [comment]
我目前排查的是貌似和 zotero-PDF-translator 有冲突

**Comment by redleafnew** [comment]
大概是这几个插件都是用的同一个框架，冲突了。

**Comment by medicialcoder** [comment]
嗯嗯应该是冲突了  我今天重启  重新安装都不行  然后我还是用回6了  7还是等他再完善完善吧

**Comment by starc929moon** [comment]
我新安装7.0版本，也没有影响因子的列，只装了greenfrog和style

**Comment by redleafnew** [comment]
两个插件都用了同一个框架，有可能是冲突了。

**Comment by redleafnew** [comment]
试试这个版本，用了新工具箱编译了。

**Comment by starc929moon** [comment]
呜呼！可以了！万分感谢！辛苦啦！
