### ISSUE TITLE
您好，请问大学期刊分类里面可以不可以加个西南政法大学❤️

### ISSUE THREAD

**Issue by yzy-lex** [redleafnew/zotero-updateifsE#99]
![CleanShot 2023-08-13 at 11 38 04@2x](https://github.com/redleafnew/zotero-updateifsE/assets/50101175/343d01ec-3e1d-4df2-a693-15d44608c232)

**Comment by redleafnew** [comment]
easyScholar有提供数据源吗？
给个条目的JSON数据测试一下。

**Comment by yzy-lex** [comment]
有的
![CleanShot 2023-08-13 at 17 14 58@2x](https://github.com/redleafnew/zotero-updateifsE/assets/50101175/4aed3a2f-2880-4586-90fb-3efdef92e476)
[
	{
		"id": "http://zotero.org/users/11021824/items/4J49YDFS",
		"type": "article-journal",
		"abstract": "我国民法典已经确认了数据的民事权益客体属性，为数据确权提供了民事基本法层面的依据。虽然有关数据政策和地方性立法确认了数据权益，但在全国性立法层面并没有对数据确权作出回应。数据确权是数据立法需要解决的关键问题，数据确权有利于保护劳动，可激励数据生产，促进数据流通，强化数据保护。由于现有法律制度如反不正当竞争法、知识产权法、个人信息保护法等无法实现对数据的全面保护，因此数据确权立法势在必行。数据立法要在区分数据来源者和数据处理者权利的基础上，构建数据确权的双重权益结构，尊重和保护数据来源者的在先权益，确认和保护数据处理者的财产权益，包括持有权、使用权、收益权、处置权以及数据财产权遭受侵害或者妨碍时的停止侵害、排除妨碍和消除危险请求权。",
		"container-title": "法学研究",
		"ISSN": "1002-896X",
		"issue": "4",
		"language": "zh",
		"page": "56-73",
		"source": "CNKI",
		"title": "数据何以确权",
		"title-short": "数据何以确权",
		"URL": "https://kns.cnki.net/kcms2/article/abstract?v=XMRxuh29YV8kSRq_JG3bbPKl7h1SYfwjNbvfk6gDbggz1d_cVNMfHYtAnlH2tfeo6vzOoWNHRH7VS3s_yAWpMBytN0uVFAvQkXNktC0S_l-el3dkdvOABw==&uniplatform=NZKPT",
		"volume": "45",
		"author": [
			{
				"literal": "王利明"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2023",
					8,
					13
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2023"
				]
			]
		}
	}
]

**Comment by yzy-lex** [comment]
SWUPL这个就是。
{
    "code": 200
    "msg": "SUCCESS"
    "data": {
        "customRank": {
            "rankInfo": [
                "0": {
                    "uuid": "1642199434173014016"
                    "abbName": "CLSCI"
                    "oneRankText": " "
                }
                "1": {
                    "uuid": "1648920625629810688"
                    "abbName": "AMI"
                    "oneRankText": "顶级"
                    "twoRankText": "权威"
                    "threeRankText": "核心"
                    "fourRankText": "扩展"
                    "fiveRankText": "入库"
                }
                "2": {
                    "uuid": "1652662162603773952"
                    "abbName": "SWUPL"
                    "oneRankText": "A"
                    "twoRankText": "B"
                    "threeRankText": "C"
                    "fourRankText": "D1"
                    "fiveRankText": "D2"
                }
                "3": {
                    "uuid": "1653331955333984256"
                    "abbName": "AMI集刊"
                    "oneRankText": "核心"
                    "twoRankText": "入库"
                }
                "4": {
                    "uuid": "1653331106809507840"
                    "abbName": "CSSCI集刊"
                    "oneRankText": " "
                }
                "5": {
                    "uuid": "1648936694851489792"
                    "abbName": "国家社科基金"
                    "oneRankText": "优秀"
                    "twoRankText": "合格"
                }
            ]
            "rank": [
                "0": "1642199434173014016&&&1"
                "1": "1648920625629810688&&&1"
                "2": "1652662162603773952&&&2"
                "3": "1648936694851489792&&&2"
            ]
        }
        "officialRank": {
            "all": {
                "swufe": "A"
                "cufe": "AA"
                "sdufe": "A1"
                "swjtu": "A"
                "ruc": "A"
                "xmu": "XMU一类"
                "sjtu": "A"
                "fdu": "A"
                "cqu": "A"
                "xju": "二区"
                "cug": "法学T2"
                "cssci": "CSSCI"
                "pku": "1"
                "zhongguokejihexin": "中国科技核心期刊"
                "zju": "国内一级学术期刊"
            }
            "select": {
                "cssci": "CSSCI"
                "pku": "1"
                "zhongguokejihexin": "中国科技核心期刊"
            }
        }
    }
}

**Comment by redleafnew** [comment]
https://github.com/redleafnew/zotero-updateifsE/releases/tag/0.16.0

**Comment by yzy-lex** [comment]
感谢！❤️
